// Industry Templates ("Namene") - Odoo-style pre-configured module sets
// Each template defines which modules are active for a specific industry type.

export interface IndustryTemplateData {
  name: string
  slug: string
  description: string
  icon: string
  category: string
  modules: string[]
  featured: boolean
  sortOrder: number
}

// ============ BIZNIS SERVISI (10) ============
const businessServices: IndustryTemplateData[] = [
  {
    name: 'Računovodstvena firma',
    slug: 'accounting-firm',
    description: 'Kompletno računovodstvo, knjiženje, protokol, fiskalizacija i izveštaji za klijente.',
    icon: 'Calculator',
    category: 'Biznis servisi',
    modules: ['dashboard', 'contacts', 'finance', 'invoices', 'accounting', 'protocol', 'reports', 'calendar', 'documents', 'expenses', 'settings', 'automation', 'bank-sync', 'payments', 'contracts', 'offers', 'subscriptions'],
    featured: true,
    sortOrder: 1,
  },
  {
    name: 'Izrada bilborda',
    slug: 'billboard-rental',
    description: 'Upravljanje bilbordima, zakazivanje kampanja, fakturisanje i praćenje lokacija.',
    icon: 'LayoutDashboard',
    category: 'Biznis servisi',
    modules: ['dashboard', 'contacts', 'invoices', 'offers', 'calendar', 'projects', 'documents', 'finance', 'settings', 'reports', 'crm', 'contracts'],
    featured: false,
    sortOrder: 2,
  },
  {
    name: 'Revizija i sertifikacija',
    slug: 'audit-certification',
    description: 'Revizija finansijskih izveštaja, sertifikacija standarda, praćenje naloga i nalazi.',
    icon: 'ShieldCheck',
    category: 'Biznis servisi',
    modules: ['dashboard', 'contacts', 'finance', 'invoices', 'accounting', 'protocol', 'reports', 'documents', 'standards', 'projects', 'calendar', 'settings', 'automation'],
    featured: false,
    sortOrder: 3,
  },
  {
    name: 'Trgovina fosilnim gorivima',
    slug: 'fossil-fuel-trading',
    description: 'Nabavka, prodaja i praćenje zaliha fosilnih goriva, flota vozila i isporuke.',
    icon: 'Fuel',
    category: 'Biznis servisi',
    modules: ['dashboard', 'contacts', 'invoices', 'inventory', 'fleet', 'delivery', 'routes', 'finance', 'expenses', 'reports', 'settings', 'procurement', 'offers'],
    featured: false,
    sortOrder: 4,
  },
  {
    name: 'Ekološka agencija',
    slug: 'environmental-agency',
    description: 'Praćenje ekoloških standarda, izveštavanje, dozvole i usklađenost.',
    icon: 'Leaf',
    category: 'Biznis servisi',
    modules: ['dashboard', 'contacts', 'projects', 'documents', 'standards', 'reports', 'calendar', 'invoices', 'settings', 'compliance', 'quality'],
    featured: false,
    sortOrder: 5,
  },
  {
    name: 'Zapošljavanje talenata',
    slug: 'talent-acquisition',
    description: 'Regrutacija, selekcija kandidata, intervjui, praćenje i plasman kadrova.',
    icon: 'UserSearch',
    category: 'Biznis servisi',
    modules: ['dashboard', 'contacts', 'recruitment', 'employees', 'calendar', 'crm', 'email-marketing', 'documents', 'reports', 'settings', 'referrals', 'skills'],
    featured: false,
    sortOrder: 6,
  },
  {
    name: 'Advokatska kancelarija',
    slug: 'law-firm',
    description: 'Upravljanje predmetima, klijentima, rokovima, dokumentima i fakturisanje usluga.',
    icon: 'Scale',
    category: 'Biznis servisi',
    modules: ['dashboard', 'contacts', 'projects', 'calendar', 'documents', 'invoices', 'offers', 'contracts', 'time-billing', 'finance', 'reports', 'settings', 'automation', 'signatures'],
    featured: true,
    sortOrder: 7,
  },
  {
    name: 'IT hardver i podrška',
    slug: 'it-hardware-support',
    description: 'Upravljanje IT opremom, tiketi za podršku, evidencija licence i održavanje.',
    icon: 'Monitor',
    category: 'Biznis servisi',
    modules: ['dashboard', 'contacts', 'assets', 'maintenance', 'support', 'projects', 'inventory', 'invoices', 'reports', 'settings', 'service-center', 'knowledge-base', 'contracts'],
    featured: false,
    sortOrder: 8,
  },
  {
    name: 'Marketing agencija',
    slug: 'marketing-agency',
    description: 'Kampanje, CRM, društvene mreže, email marketing, projekti i analitika.',
    icon: 'Megaphone',
    category: 'Biznis servisi',
    modules: ['dashboard', 'crm', 'contacts', 'projects', 'calendar', 'social-media', 'email-marketing', 'marketing-automation', 'surveys', 'events', 'website', 'blog', 'seo', 'invoices', 'reports', 'finance', 'settings', 'automation', 'sms-marketing'],
    featured: true,
    sortOrder: 9,
  },
  {
    name: 'IT konsalting i razvoj',
    slug: 'it-consulting',
    description: 'Projektni menadžment, development timovi, zakazivanje i fakturisanje.',
    icon: 'Code2',
    category: 'Biznis servisi',
    modules: ['dashboard', 'projects', 'contacts', 'employees', 'time-tracking', 'time-billing', 'calendar', 'documents', 'invoices', 'offers', 'reports', 'settings', 'knowledge-base', 'chat', 'automation'],
    featured: false,
    sortOrder: 10,
  },
]

// ============ KULTURA I UMETNOST (8) ============
const cultureArts: IndustryTemplateData[] = [
  {
    name: 'Radnja za umetnost i zanat',
    slug: 'arts-crafts-store',
    description: 'Prodaja umetničkih i zanatskih proizvoda, inventar, online prodaja i kupon sistem.',
    icon: 'Palette',
    category: 'Kultura i umetnost',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'seo', 'website', 'reviews', 'coupons', 'social-media', 'finance', 'reports', 'settings', 'offers', 'expenses'],
    featured: false,
    sortOrder: 11,
  },
  {
    name: 'Koncertne dvorane',
    slug: 'concert-halls',
    description: 'Upravljanje događajima, rezervacije, karte, prodaja ulaznica i marketinške kampanje.',
    icon: 'Music',
    category: 'Kultura i umetnost',
    modules: ['dashboard', 'events', 'calendar', 'reservations', 'contacts', 'invoices', 'pos', 'coupons', 'email-marketing', 'website', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 12,
  },
  {
    name: 'Galerija',
    slug: 'gallery',
    description: 'Izložbe, umetnici, prodaja dela, katalogizacija i praćenje posetilaca.',
    icon: 'Frame',
    category: 'Kultura i umetnost',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'calendar', 'events', 'crm', 'website', 'blog', 'social-media', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 13,
  },
  {
    name: 'Biblioteka',
    slug: 'library',
    description: 'Upravljanje knjigama, članstvo, izdavanje, rezervacije i katalog.',
    icon: 'BookOpen',
    category: 'Kultura i umetnost',
    modules: ['dashboard', 'library', 'contacts', 'calendar', 'reports', 'settings', 'education', 'documents', 'website'],
    featured: false,
    sortOrder: 14,
  },
  {
    name: 'Muzej',
    slug: 'museum',
    description: 'Eksponati, izložbe, karte, posetioci, edukativni programi i donacije.',
    icon: 'Landmark',
    category: 'Kultura i umetnost',
    modules: ['dashboard', 'contacts', 'inventory', 'events', 'calendar', 'invoices', 'education', 'website', 'reports', 'settings', 'reservations'],
    featured: false,
    sortOrder: 15,
  },
  {
    name: 'Fotografija',
    slug: 'photography',
    description: 'Zakazivanje sesija, upravljanje klijentima, galerije, fakturisanje i isporuka.',
    icon: 'Camera',
    category: 'Kultura i umetnost',
    modules: ['dashboard', 'contacts', 'crm', 'calendar', 'appointments', 'invoices', 'offers', 'documents', 'website', 'social-media', 'reports', 'settings'],
    featured: false,
    sortOrder: 16,
  },
  {
    name: 'Tattoo studio',
    slug: 'tattoo-shop',
    description: 'Zakazivanje termina, klijenti, portfolio, galerija, prodaja opreme i nalazi.',
    icon: 'PenTool',
    category: 'Kultura i umetnost',
    modules: ['dashboard', 'contacts', 'appointments', 'scheduler', 'calendar', 'invoices', 'inventory', 'pos', 'social-media', 'website', 'reports', 'settings'],
    featured: false,
    sortOrder: 17,
  },
  {
    name: 'Pozorište',
    slug: 'theater',
    description: 'Predstave, repertoar, karte, glumci, rezervacije i marketing kampanje.',
    icon: 'Drama',
    category: 'Kultura i umetnost',
    modules: ['dashboard', 'events', 'calendar', 'contacts', 'reservations', 'invoices', 'email-marketing', 'website', 'blog', 'social-media', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 18,
  },
]

// ============ OBRAZOVANJE (4) ============
const education: IndustryTemplateData[] = [
  {
    name: 'Radionice i kursevi',
    slug: 'diy-workshops',
    description: 'Organizacija radionica, upis polaznika, raspored, plaćanje i sertifikati.',
    icon: 'Hammer',
    category: 'Obrazovanje',
    modules: ['dashboard', 'education', 'calendar', 'contacts', 'invoices', 'payments', 'enrollment', 'tuition', 'homework', 'website', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 19,
  },
  {
    name: 'Auto škola',
    slug: 'driving-school',
    description: 'Učenici, instruktori, vožnje, raspored, plaćanje i polaganje ispita.',
    icon: 'Car',
    category: 'Obrazovanje',
    modules: ['dashboard', 'education', 'calendar', 'contacts', 'fleet', 'scheduler', 'enrollment', 'tuition', 'invoices', 'payments', 'reports', 'settings'],
    featured: false,
    sortOrder: 20,
  },
  {
    name: 'eLearning platforma',
    slug: 'elearning-platform',
    description: 'Online kursevi, lekcije, testovi, polaznici, certifikati i naplata.',
    icon: 'GraduationCap',
    category: 'Obrazovanje',
    modules: ['dashboard', 'education', 'homework', 'enrollment', 'tuition', 'calendar', 'contacts', 'website', 'blog', 'ecommerce', 'payments', 'subscriptions', 'email-marketing', 'surveys', 'reports', 'settings'],
    featured: true,
    sortOrder: 21,
  },
  {
    name: 'Studentska organizacija',
    slug: 'student-organization',
    description: 'Članstvo, događaji, projekti, komunikacija, dokumenti i finansije.',
    icon: 'Users',
    category: 'Obrazovanje',
    modules: ['dashboard', 'contacts', 'events', 'projects', 'calendar', 'chat', 'forum', 'documents', 'surveys', 'website', 'blog', 'finance', 'reports', 'settings'],
    featured: false,
    sortOrder: 22,
  },
]

// ============ DOGAĐAJI I ZAJEDNICA (9) ============
const eventsCommunity: IndustryTemplateData[] = [
  {
    name: 'Coworking prostor',
    slug: 'coworking',
    description: 'Članstvo, rezervacija radnih mesta, kalendar događaja, fakturisanje i komunikacija.',
    icon: 'Laptop',
    category: 'Događaji i zajednica',
    modules: ['dashboard', 'contacts', 'calendar', 'reservations', 'invoices', 'subscriptions', 'events', 'chat', 'website', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 23,
  },
  {
    name: 'Event menadžment',
    slug: 'event-management',
    description: 'Planiranje i organizacija događaja, klijenti, dobavljači, budžet i logistika.',
    icon: 'PartyPopper',
    category: 'Događaji i zajednica',
    modules: ['dashboard', 'events', 'calendar', 'projects', 'contacts', 'crm', 'invoices', 'offers', 'expenses', 'email-marketing', 'social-media', 'website', 'reports', 'settings', 'marketing-automation'],
    featured: true,
    sortOrder: 24,
  },
  {
    name: 'Klub članova',
    slug: 'members-club',
    description: 'Članstvo, mesečne/ godišnje članarine, događaji, rezervacije i komunikacija.',
    icon: 'UserCheck',
    category: 'Događaji i zajednica',
    modules: ['dashboard', 'contacts', 'subscriptions', 'calendar', 'events', 'reservations', 'invoices', 'payments', 'email-marketing', 'website', 'reports', 'settings'],
    featured: false,
    sortOrder: 25,
  },
  {
    name: 'NVO (Nevladina organizacija)',
    slug: 'nonprofit-organisation',
    description: 'Projekti, donatori, volonteri, izveštaji, događaji i transparentnost.',
    icon: 'Heart',
    category: 'Događaji i zajednica',
    modules: ['dashboard', 'contacts', 'projects', 'documents', 'calendar', 'events', 'invoices', 'reports', 'website', 'blog', 'email-marketing', 'surveys', 'settings'],
    featured: false,
    sortOrder: 26,
  },
  {
    name: 'Sportski događaji',
    slug: 'sport-events',
    description: 'Organizacija takmičenja, ekipe, registar učesnika, karte i sponzori.',
    icon: 'Trophy',
    category: 'Događaji i zajednica',
    modules: ['dashboard', 'events', 'calendar', 'contacts', 'crm', 'invoices', 'offers', 'email-marketing', 'website', 'reports', 'settings'],
    featured: false,
    sortOrder: 27,
  },
  {
    name: 'Sportski klub',
    slug: 'sports-club',
    description: 'Članstvo, treningi, takmičenja, plaćanje, oprema i komunikacija.',
    icon: 'Dumbbell',
    category: 'Događaji i zajednica',
    modules: ['dashboard', 'contacts', 'calendar', 'subscriptions', 'invoices', 'payments', 'inventory', 'events', 'email-marketing', 'website', 'reports', 'settings'],
    featured: false,
    sortOrder: 28,
  },
  {
    name: 'Letnji kampovi',
    slug: 'summer-camps',
    description: 'Učesnici, roditelji, smene, aktivnosti, zdravstveni kartoni i plaćanje.',
    icon: 'Tent',
    category: 'Događaji i zajednica',
    modules: ['dashboard', 'contacts', 'education', 'calendar', 'enrollment', 'invoices', 'payments', 'documents', 'website', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 29,
  },
  {
    name: 'Timski sportovi',
    slug: 'team-sports-club',
    description: 'Ekipni sportovi, treneri, utakmice, statistika, članstvo i finansije.',
    icon: 'Medal',
    category: 'Događaji i zajednica',
    modules: ['dashboard', 'contacts', 'calendar', 'events', 'subscriptions', 'invoices', 'inventory', 'website', 'email-marketing', 'reports', 'settings', 'gamification'],
    featured: false,
    sortOrder: 30,
  },
  {
    name: 'Vjenčanja i proslave',
    slug: 'wedding-planner',
    description: 'Planiranje vjenčanja, klijenti, dobavljači, budžet, raspored i dokumentacija.',
    icon: 'Ring',
    category: 'Događaji i zajednica',
    modules: ['dashboard', 'contacts', 'crm', 'projects', 'calendar', 'invoices', 'offers', 'expenses', 'documents', 'website', 'social-media', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 31,
  },
]

// ============ HRANA I PIĆE (10) ============
const foodBeverage: IndustryTemplateData[] = [
  {
    name: 'Pekara',
    slug: 'bakery',
    description: 'Proizvodnja i prodaja pekarskih proizvoda, sirovine, recepti, isporuke i POS.',
    icon: 'Croissant',
    category: 'Hrana i piće',
    modules: ['dashboard', 'inventory', 'invoices', 'pos', 'manufacturing', 'kitchen', 'procurement', 'contacts', 'expenses', 'reports', 'settings', 'coupons', 'offers', 'ecommerce'],
    featured: true,
    sortOrder: 32,
  },
  {
    name: 'Bar i pub',
    slug: 'bar-pub',
    description: 'Upravljanje restoranskim porudžbinama, piće, rezervacije, POS i zalihe.',
    icon: 'Beer',
    category: 'Hrana i piće',
    modules: ['dashboard', 'restaurant', 'reservations', 'menu', 'kitchen', 'orders', 'pos', 'inventory', 'invoices', 'expenses', 'calendar', 'reports', 'settings', 'coupons'],
    featured: false,
    sortOrder: 33,
  },
  {
    name: 'Distributer pića',
    slug: 'beverages-distributor',
    description: 'Nabavka, skladište, isporuke, flota, fakturisanje i praćenje naloga.',
    icon: 'Wine',
    category: 'Hrana i piće',
    modules: ['dashboard', 'contacts', 'inventory', 'procurement', 'invoices', 'delivery', 'fleet', 'routes', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 34,
  },
  {
    name: 'Poslastičarnica',
    slug: 'cake-store',
    description: 'Porudžbine torta i kolača, recepti, sirovine, zakazivanje preuzimanja i marketing.',
    icon: 'Cake',
    category: 'Hrana i piće',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'kitchen', 'calendar', 'appointments', 'social-media', 'website', 'reports', 'settings', 'offers', 'ecommerce'],
    featured: false,
    sortOrder: 35,
  },
  {
    name: 'Sladara / Prodavnica slatkiša',
    slug: 'candy-shop',
    description: 'Prodaja slatkiša, inventar, online prodaja, kupon sistem i lojalnost.',
    icon: 'Candy',
    category: 'Hrana i piće',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'seo', 'loyalty', 'coupons', 'social-media', 'website', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 36,
  },
  {
    name: 'Ketering',
    slug: 'catering',
    description: 'Porudžbine hrane za evente, meni, sirovine, isporuke, kalendar i klijenti.',
    icon: 'UtensilsCrossed',
    category: 'Hrana i piće',
    modules: ['dashboard', 'contacts', 'crm', 'calendar', 'events', 'invoices', 'offers', 'kitchen', 'inventory', 'procurement', 'delivery', 'reports', 'settings', 'expenses'],
    featured: false,
    sortOrder: 37,
  },
  {
    name: 'Brza hrana',
    slug: 'fast-food',
    description: 'POS, meni, naručivanje, porudžbine, kuhinja, isporuka i zalihe.',
    icon: 'Burger',
    category: 'Hrana i piće',
    modules: ['dashboard', 'restaurant', 'menu', 'orders', 'kitchen', 'pos', 'inventory', 'delivery', 'invoices', 'expenses', 'reports', 'settings', 'coupons', 'loyalty'],
    featured: true,
    sortOrder: 38,
  },
  {
    name: 'Food truck',
    slug: 'food-trucks',
    description: 'Mobilna prodaja, lokacije, meni, inventar, dnevni izveštaji i isporuka.',
    icon: 'Truck',
    category: 'Hrana i piće',
    modules: ['dashboard', 'restaurant', 'menu', 'orders', 'kitchen', 'pos', 'inventory', 'fleet', 'expenses', 'reports', 'settings', 'social-media'],
    featured: false,
    sortOrder: 39,
  },
  {
    name: 'Restoran sa finom kuhinjom',
    slug: 'fine-dining-restaurant',
    description: 'Kompletni restoranski sistem: rezervacije, meni, porudžbine, kuhinja, POS i klijenti.',
    icon: 'ChefHat',
    category: 'Hrana i piće',
    modules: ['dashboard', 'restaurant', 'reservations', 'menu', 'orders', 'kitchen', 'pos', 'inventory', 'contacts', 'invoices', 'expenses', 'calendar', 'reports', 'settings', 'coupons', 'reviews', 'loyalty'],
    featured: false,
    sortOrder: 40,
  },
  {
    name: 'Takeaway restoran',
    slug: 'takeaway-restaurant',
    description: 'Naručivanje hrane, meni, isporuka, online prodaja i plaćanje.',
    icon: 'ShoppingBag',
    category: 'Hrana i piće',
    modules: ['dashboard', 'restaurant', 'menu', 'orders', 'kitchen', 'pos', 'ecommerce', 'delivery', 'inventory', 'expenses', 'coupons', 'reports', 'settings', 'social-media'],
    featured: false,
    sortOrder: 41,
  },
]

// ============ ZDRAVLJE I WELLNESS (9) ============
const healthWellness: IndustryTemplateData[] = [
  {
    name: 'Penjački teretana',
    slug: 'climbing-gym',
    description: 'Članstvo, rezervacija termina, oprema, instruktori i fakturisanje.',
    icon: 'Mountain',
    category: 'Zdravlje i wellness',
    modules: ['dashboard', 'contacts', 'subscriptions', 'calendar', 'reservations', 'invoices', 'payments', 'inventory', 'maintenance', 'website', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 42,
  },
  {
    name: 'Optika',
    slug: 'eyewear-store',
    description: 'Proizvodi, klijenti, pregledi, narudžbenice, inventar i online prodaja.',
    icon: 'Glasses',
    category: 'Zdravlje i wellness',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'appointments', 'offers', 'reviews', 'seo', 'social-media', 'reports', 'settings'],
    featured: false,
    sortOrder: 43,
  },
  {
    name: 'Fitness centar',
    slug: 'fitness-center',
    description: 'Članstvo, treneri, raspored, plaćanje, oprema i komunikacija sa članovima.',
    icon: 'Dumbbell',
    category: 'Zdravlje i wellness',
    modules: ['dashboard', 'contacts', 'subscriptions', 'calendar', 'employees', 'appointments', 'invoices', 'payments', 'inventory', 'maintenance', 'website', 'email-marketing', 'loyalty', 'reports', 'settings'],
    featured: true,
    sortOrder: 44,
  },
  {
    name: 'Frizerski salon',
    slug: 'hair-salon',
    description: 'Zakazivanje termina, klijenti, kozmetika, inventar, plaćanje i marketing.',
    icon: 'Scissors',
    category: 'Zdravlje i wellness',
    modules: ['dashboard', 'contacts', 'appointments', 'scheduler', 'calendar', 'invoices', 'pos', 'inventory', 'expenses', 'loyalty', 'social-media', 'website', 'reports', 'settings'],
    featured: false,
    sortOrder: 45,
  },
  {
    name: 'Personalni trener',
    slug: 'personal-trainer',
    description: 'Klijenti, programi treninga, zakazivanje, napredovanje i plaćanje.',
    icon: 'Activity',
    category: 'Zdravlje i wellness',
    modules: ['dashboard', 'contacts', 'appointments', 'calendar', 'invoices', 'payments', 'subscriptions', 'documents', 'website', 'email-marketing', 'social-media', 'reports', 'settings'],
    featured: false,
    sortOrder: 46,
  },
  {
    name: 'Apoteka',
    slug: 'pharmacy',
    description: 'Lekovi, inventar, rokovi trajanja, recepti, klijenti i prodaja.',
    icon: 'Pill',
    category: 'Zdravlje i wellness',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'procurement', 'reports', 'settings', 'patients', 'prescriptions', 'offers'],
    featured: false,
    sortOrder: 47,
  },
  {
    name: 'Veterinarska ordinacija',
    slug: 'veterinary-clinic',
    description: 'Pacijenti (ljubimci), vlasnici, zakazivanje, tretmani, inventar i fakturisanje.',
    icon: 'Syringe',
    category: 'Zdravlje i wellness',
    modules: ['dashboard', 'contacts', 'appointments', 'calendar', 'inventory', 'invoices', 'pos', 'prescriptions', 'documents', 'website', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 48,
  },
  {
    name: 'Wellness praksa',
    slug: 'wellness-practitioner',
    description: 'Klijenti, zakazivanje, terapije, naplata, dokumentacija i marketing.',
    icon: 'Sparkles',
    category: 'Zdravlje i wellness',
    modules: ['dashboard', 'contacts', 'appointments', 'scheduler', 'calendar', 'invoices', 'payments', 'subscriptions', 'documents', 'website', 'email-marketing', 'social-media', 'reports', 'settings'],
    featured: false,
    sortOrder: 49,
  },
  {
    name: 'Yoga i Pilates studio',
    slug: 'yoga-pilates-studio',
    description: 'Članstvo, raspored časova, rezervacije, plaćanje i komunikacija.',
    icon: 'Flower2',
    category: 'Zdravlje i wellness',
    modules: ['dashboard', 'contacts', 'subscriptions', 'calendar', 'reservations', 'appointments', 'invoices', 'payments', 'website', 'email-marketing', 'social-media', 'reports', 'settings'],
    featured: false,
    sortOrder: 50,
  },
]

// ============ UGOSTITELJSTVO I TURIZAM (10) ============
const hospitalityTourism: IndustryTemplateData[] = [
  {
    name: 'Kuglana',
    slug: 'bowling-alleys',
    description: 'Rezervacije staza, kafić, POS, članstvo, događaji i zalihe.',
    icon: 'Circle',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'reservations', 'pos', 'calendar', 'contacts', 'invoices', 'inventory', 'coupons', 'events', 'reports', 'settings'],
    featured: false,
    sortOrder: 51,
  },
  {
    name: 'Kamp',
    slug: 'campsite',
    description: 'Rezervacije parcela, smene, klijenti, plaćanje, oprema i aktivnosti.',
    icon: 'Tent',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'reservations', 'contacts', 'calendar', 'invoices', 'payments', 'inventory', 'maintenance', 'website', 'reports', 'settings'],
    featured: false,
    sortOrder: 52,
  },
  {
    name: 'Escape room',
    slug: 'escape-rooms',
    description: 'Rezervacije soba, timovi, rang lista, plaćanje i marketing.',
    icon: 'Lock',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'reservations', 'calendar', 'contacts', 'invoices', 'pos', 'coupons', 'gamification', 'website', 'social-media', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 53,
  },
  {
    name: 'Gostinski dom',
    slug: 'guest-house',
    description: 'Sobe, rezervacije, gosti, plaćanje, čišćenje i osnovna hrana.',
    icon: 'Home',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'reservations', 'property', 'contacts', 'calendar', 'invoices', 'payments', 'expenses', 'reports', 'settings', 'reviews'],
    featured: false,
    sortOrder: 54,
  },
  {
    name: 'Vođenje tura',
    slug: 'guided-tours',
    description: 'Ture, vodiči, rezervacije, kalendar, plaćanje i marketing.',
    icon: 'MapPin',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'contacts', 'calendar', 'events', 'reservations', 'invoices', 'payments', 'crm', 'website', 'email-marketing', 'social-media', 'reports', 'settings', 'ecommerce'],
    featured: false,
    sortOrder: 55,
  },
  {
    name: 'Planinski vikendica',
    slug: 'holiday-house',
    description: 'Rezervacije, gosti, cene po sezoni, plaćanje, recenzije i marketing.',
    icon: 'Cabin',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'reservations', 'property', 'calendar', 'contacts', 'invoices', 'payments', 'coupons', 'reviews', 'website', 'social-media', 'reports', 'settings'],
    featured: false,
    sortOrder: 56,
  },
  {
    name: 'Hotel',
    slug: 'hotel',
    description: 'Kompletni hotelski sistem: sobe, rezervacije, gosti, restoran, POS i finansije.',
    icon: 'Hotel',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'reservations', 'restaurant', 'menu', 'orders', 'kitchen', 'pos', 'property', 'contacts', 'calendar', 'invoices', 'payments', 'expenses', 'reports', 'settings', 'reviews', 'coupons', 'loyalty', 'maintenance', 'employees'],
    featured: true,
    sortOrder: 57,
  },
  {
    name: 'Night club',
    slug: 'night-clubs',
    description: 'Događaji, DJ raspored, ulaznice, POS, rezervacije VIP i marketing.',
    icon: 'Disc',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'events', 'calendar', 'reservations', 'pos', 'inventory', 'invoices', 'coupons', 'social-media', 'website', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 58,
  },
  {
    name: 'Outdoor aktivnosti',
    slug: 'outdoor-activities',
    description: 'Avanturističke aktivnosti, rezervacije, oprema, instruktori i bezbednost.',
    icon: 'Trees',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'contacts', 'calendar', 'reservations', 'inventory', 'invoices', 'payments', 'safety', 'website', 'email-marketing', 'social-media', 'reports', 'settings'],
    featured: false,
    sortOrder: 59,
  },
  {
    name: 'Spa resort',
    slug: 'spa-resort',
    description: 'Tretmani, rezervacije, članstvo, restoran, sobe i kompletna ponuda.',
    icon: 'Waves',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'reservations', 'appointments', 'scheduler', 'calendar', 'contacts', 'invoices', 'payments', 'subscriptions', 'restaurant', 'menu', 'pos', 'property', 'reviews', 'loyalty', 'coupons', 'website', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 60,
  },
]

// ============ PROIZVODNJA I LOGISTIKA (9) ============
const manufacturingLogistics: IndustryTemplateData[] = [
  {
    name: '3PL (Logistika trećih lica)',
    slug: 'third-party-logistics',
    description: 'Skladište, prijem, otprema, isporuke, flota i praćenje pošiljki.',
    icon: 'Warehouse',
    category: 'Proizvodnja i logistika',
    modules: ['dashboard', 'inventory', 'shipping', 'delivery', 'fleet', 'loading-dock', 'contacts', 'invoices', 'reports', 'settings', 'routes', 'packaging', 'barcode'],
    featured: false,
    sortOrder: 61,
  },
  {
    name: 'Stolar',
    slug: 'carpenter',
    description: 'Proizvodnja nameštaja, sirovine, narudžbenice, inventar i isporuke.',
    icon: 'Hammer',
    category: 'Proizvodnja i logistika',
    modules: ['dashboard', 'manufacturing', 'inventory', 'contacts', 'invoices', 'offers', 'projects', 'delivery', 'reports', 'settings', 'procurement'],
    featured: false,
    sortOrder: 62,
  },
  {
    name: 'Korporativni pokloni',
    slug: 'corporate-gifts',
    description: 'B2B prodaja poklona, katalog, narudžbine, graviranje i isporuka.',
    icon: 'Gift',
    category: 'Proizvodnja i logistika',
    modules: ['dashboard', 'contacts', 'crm', 'inventory', 'invoices', 'offers', 'ecommerce', 'delivery', 'website', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 63,
  },
  {
    name: 'Proizvodnja nameštaja po meri',
    slug: 'custom-furniture-production',
    description: 'Narudžbenice, proizvodnja, sirovine, projekti, isporuka i fakturisanje.',
    icon: 'Armchair',
    category: 'Proizvodnja i logistika',
    modules: ['dashboard', 'manufacturing', 'projects', 'inventory', 'contacts', 'invoices', 'offers', 'blueprints', 'delivery', 'reports', 'settings', 'procurement', 'quality'],
    featured: false,
    sortOrder: 64,
  },
  {
    name: 'Distribucija hrane',
    slug: 'food-distribution',
    description: 'Nabavka, skladištenje, distribucija, flota, ekipe i praćenje naloga.',
    icon: 'Truck',
    category: 'Proizvodnja i logistika',
    modules: ['dashboard', 'inventory', 'procurement', 'shipping', 'delivery', 'fleet', 'routes', 'contacts', 'invoices', 'expenses', 'reports', 'settings'],
    featured: false,
    sortOrder: 65,
  },
  {
    name: 'Metaloprerađivačka industrija',
    slug: 'metal-fabricator',
    description: 'Proizvodnja, kvalitet, nacrta, inventar sirovina, narudžbenice i isporuke.',
    icon: 'Cog',
    category: 'Proizvodnja i logistika',
    modules: ['dashboard', 'manufacturing', 'quality', 'blueprints', 'inventory', 'contacts', 'invoices', 'offers', 'projects', 'delivery', 'maintenance', 'standards', 'reports', 'settings', 'procurement'],
    featured: false,
    sortOrder: 66,
  },
  {
    name: 'Mikro pivara',
    slug: 'microbrewery',
    description: 'Proizvodnja piva, sirovine, recepti, distribucija, prodaja i marketing.',
    icon: 'Beer',
    category: 'Proizvodnja i logistika',
    modules: ['dashboard', 'manufacturing', 'inventory', 'procurement', 'contacts', 'invoices', 'pos', 'delivery', 'routes', 'website', 'social-media', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 67,
  },
  {
    name: 'Tekstilna industrija',
    slug: 'textile-manufacturing',
    description: 'Proizvodnja, sirovine, kvalitet, inventar, narudžbenice i isporuke.',
    icon: 'Scissors',
    category: 'Proizvodnja i logistika',
    modules: ['dashboard', 'manufacturing', 'quality', 'inventory', 'contacts', 'invoices', 'offers', 'projects', 'delivery', 'labels', 'standards', 'reports', 'settings', 'procurement'],
    featured: false,
    sortOrder: 68,
  },
  {
    name: 'Vinograd',
    slug: 'vineyard',
    description: 'Vinogradarstvo, berba, proizvodnja vina, čuvanje, distribucija i degustacije.',
    icon: 'Grape',
    category: 'Proizvodnja i logistika',
    modules: ['dashboard', 'manufacturing', 'inventory', 'contacts', 'invoices', 'pos', 'ecommerce', 'delivery', 'website', 'social-media', 'email-marketing', 'reports', 'settings', 'coupons', 'offers'],
    featured: false,
    sortOrder: 69,
  },
]

// ============ NEKRETNINE I GRAĐEVINA (9) ============
const realEstateConstruction: IndustryTemplateData[] = [
  {
    name: 'Arhitektonski biro',
    slug: 'architecture-firm',
    description: 'Projekti, nacrti, klijenti, stages, dokumentacija i fakturisanje.',
    icon: 'Compass',
    category: 'Nekretnine i građevina',
    modules: ['dashboard', 'projects', 'contacts', 'blueprints', 'documents', 'calendar', 'invoices', 'offers', 'time-billing', 'reports', 'settings'],
    featured: false,
    sortOrder: 70,
  },
  {
    name: 'Zajednica vlasnika stanova',
    slug: 'property-owner-association',
    description: 'Stanari, računi, održavanje, zadaće, dokumenti i godišnji plan.',
    icon: 'Building',
    category: 'Nekretnine i građevina',
    modules: ['dashboard', 'contacts', 'property', 'work-orders', 'maintenance', 'utilities', 'invoices', 'payments', 'documents', 'calendar', 'reports', 'settings', 'contracts', 'complaints'],
    featured: false,
    sortOrder: 71,
  },
  {
    name: 'Građevinski izvođač',
    slug: 'construction-builder',
    description: 'Gradilišta, radnici, podizvođači, alati, bezbednost i naplata.',
    icon: 'HardHat',
    category: 'Nekretnine i građevina',
    modules: ['dashboard', 'construction-site', 'employees', 'blueprints', 'subcontractors', 'safety', 'fleet', 'inventory', 'maintenance', 'invoices', 'expenses', 'projects', 'calendar', 'reports', 'settings', 'documents'],
    featured: false,
    sortOrder: 72,
  },
  {
    name: 'Građevinski investitor',
    slug: 'construction-developer',
    description: 'Projekti, gradilišta, investitori, prodaja, finansije i praćenje napretka.',
    icon: 'Crane',
    category: 'Nekretnine i građevina',
    modules: ['dashboard', 'construction-site', 'projects', 'property', 'contacts', 'crm', 'blueprints', 'invoices', 'offers', 'finance', 'reports', 'calendar', 'documents', 'settings'],
    featured: false,
    sortOrder: 73,
  },
  {
    name: 'HVAC servisi',
    slug: 'hvac-services',
    description: 'Servis klima i grejanja, zakazivanje, inventar delova, klijenti i fakturisanje.',
    icon: 'Thermometer',
    category: 'Nekretnine i građevina',
    modules: ['dashboard', 'contacts', 'appointments', 'field-service', 'work-orders', 'inventory', 'invoices', 'expenses', 'calendar', 'reports', 'settings', 'contracts'],
    featured: false,
    sortOrder: 74,
  },
  {
    name: 'Upravljanje nekretninama',
    slug: 'property-management',
    description: 'Nekretnine, zakupci, ugovori, održavanje, računi i izveštaji.',
    icon: 'Building2',
    category: 'Nekretnine i građevina',
    modules: ['dashboard', 'property', 'rentals', 'property-viewings', 'contacts', 'contracts', 'maintenance', 'work-orders', 'utilities', 'invoices', 'payments', 'calendar', 'documents', 'reports', 'settings'],
    featured: true,
    sortOrder: 75,
  },
  {
    name: 'Izdavanje mašina i alata',
    slug: 'machine-tools-rental',
    description: 'Inventar opreme, iznajmljivanje, klijenti, rezervacije, održavanje.',
    icon: 'Wrench',
    category: 'Nekretnine i građevina',
    modules: ['dashboard', 'inventory', 'contacts', 'rentals', 'calendar', 'invoices', 'contracts', 'maintenance', 'assets', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 76,
  },
  {
    name: 'Agencija za nekretnine',
    slug: 'real-estate-agency',
    description: 'Nekretnine, pregledi, klijenti, kupoprodaja, zakup i marketing.',
    icon: 'Home',
    category: 'Nekretnine i građevina',
    modules: ['dashboard', 'property', 'property-viewings', 'contacts', 'crm', 'calendar', 'website', 'blog', 'social-media', 'email-marketing', 'reports', 'settings'],
    featured: true,
    sortOrder: 77,
  },
  {
    name: 'Solarni sistemi',
    slug: 'solar-energy-systems',
    description: 'Projektovanje, instalacija, održavanje, klijenti i subvencije.',
    icon: 'Sun',
    category: 'Nekretnine i građevina',
    modules: ['dashboard', 'contacts', 'projects', 'appointments', 'field-service', 'work-orders', 'inventory', 'invoices', 'offers', 'contracts', 'maintenance', 'reports', 'calendar', 'settings', 'documents'],
    featured: false,
    sortOrder: 78,
  },
]

// ============ TRGOVINA (13) ============
const retail: IndustryTemplateData[] = [
  {
    name: 'Poljoprivredna apoteka',
    slug: 'agricultural-store',
    description: 'Prodaja poljoprivredne opreme, inventar, dobavljači, nabavka i online prodaja.',
    icon: 'Sprout',
    category: 'Trgovina',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'procurement', 'offers', 'ecommerce', 'website', 'reports', 'settings', 'expenses'],
    featured: false,
    sortOrder: 79,
  },
  {
    name: 'Auto delovi',
    slug: 'automobile-spare-parts',
    description: 'Inventar delova, katalog, nabavka, prodaja, e-commerce i servis.',
    icon: 'Car',
    category: 'Trgovina',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'procurement', 'service-center', 'ecommerce', 'website', 'seo', 'reports', 'settings', 'offers', 'barcode', 'labels'],
    featured: false,
    sortOrder: 80,
  },
  {
    name: 'Knjižara',
    slug: 'bookstore',
    description: 'Knjige, inventar, ISBN, online prodaja, izdavanje, loyalty i događaji.',
    icon: 'BookOpen',
    category: 'Trgovina',
    modules: ['dashboard', 'library', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'website', 'loyalty', 'coupons', 'events', 'social-media', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 81,
  },
  {
    name: 'Prodavnica odeće',
    slug: 'clothing-store',
    description: 'Inventar, veličine, boje, e-commerce, POS, popusti i lojalnost.',
    icon: 'Shirt',
    category: 'Trgovina',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'seo', 'loyalty', 'coupons', 'reviews', 'social-media', 'website', 'reports', 'settings', 'offers', 'returns', 'labels'],
    featured: true,
    sortOrder: 82,
  },
  {
    name: 'Kozmetička prodavnica',
    slug: 'cosmetics-store',
    description: 'Kozmetika, inventar, online prodaja, savetovanje, popusti i marketing.',
    icon: 'Sparkles',
    category: 'Trgovina',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'seo', 'loyalty', 'coupons', 'reviews', 'social-media', 'website', 'email-marketing', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 83,
  },
  {
    name: 'Dropshipping',
    slug: 'dropshipping',
    description: 'Online prodaja bez zaliha, dobavljači, marketplace integracija, naručivanje.',
    icon: 'Package',
    category: 'Trgovina',
    modules: ['dashboard', 'contacts', 'ecommerce', 'marketplace', 'shipping', 'orders', 'inventory', 'website', 'seo', 'email-marketing', 'social-media', 'reports', 'settings', 'coupons', 'reviews'],
    featured: false,
    sortOrder: 84,
  },
  {
    name: 'Elektronska prodavnica',
    slug: 'electronic-store',
    description: 'Elektronika, inventar, garancije, servis, e-commerce i recenzije.',
    icon: 'Monitor',
    category: 'Trgovina',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'service-center', 'warranty', 'reviews', 'seo', 'website', 'social-media', 'reports', 'settings', 'offers', 'returns', 'barcode', 'labels'],
    featured: false,
    sortOrder: 85,
  },
  {
    name: 'Cvetićara',
    slug: 'florist',
    description: 'Cveće, porudžbine, dostava, sezonski proizvodi, marketing i online prodaja.',
    icon: 'Flower',
    category: 'Trgovina',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'delivery', 'calendar', 'coupons', 'social-media', 'website', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 86,
  },
  {
    name: 'Supermarket',
    slug: 'grocery-store',
    description: 'Širok asortiman, POS, inventar, dobavljači, akcije, loyalty i isporuka.',
    icon: 'ShoppingCart',
    category: 'Trgovina',
    modules: ['dashboard', 'inventory', 'pos', 'invoices', 'procurement', 'contacts', 'expenses', 'coupons', 'loyalty', 'ecommerce', 'delivery', 'reports', 'settings', 'offers', 'returns', 'labels', 'barcode'],
    featured: false,
    sortOrder: 87,
  },
  {
    name: 'Prodavnica nameštaja',
    slug: 'furniture-store',
    description: 'Nameštaj, inventar, dostava, montagža, online prodaja i katalog.',
    icon: 'Sofa',
    category: 'Trgovina',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'delivery', 'seo', 'reviews', 'website', 'social-media', 'reports', 'settings', 'offers', 'coupons'],
    featured: false,
    sortOrder: 88,
  },
  {
    name: 'Građevinska železnica',
    slug: 'hardware-store',
    description: 'Građevinski materijal, alati, inventar, nabavka, prodaja i isporuka.',
    icon: 'Wrench',
    category: 'Trgovina',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'procurement', 'offers', 'ecommerce', 'website', 'delivery', 'reports', 'settings', 'expenses'],
    featured: false,
    sortOrder: 89,
  },
  {
    name: 'Igračkara',
    slug: 'toy-store',
    description: 'Igračke, inventar, online prodaja, popusti, sezonske akcije i marketing.',
    icon: 'Puzzle',
    category: 'Trgovina',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'seo', 'coupons', 'loyalty', 'reviews', 'social-media', 'website', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 90,
  },
  {
    name: 'Vinoteka',
    slug: 'wine-shop',
    description: 'Vina, degustacije, inventar, online prodaja, događaji i loyalty.',
    icon: 'Wine',
    category: 'Trgovina',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'events', 'loyalty', 'coupons', 'reviews', 'social-media', 'website', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 91,
  },
]

// ============ ZANATI I KUĆNI SERVISI (8) ============
const tradesHomeServices: IndustryTemplateData[] = [
  {
    name: 'Iznajmljivanje bicikala',
    slug: 'bike-leasing',
    description: 'Flota bicikala, iznajmljivanje, rezervacije, održavanje i plaćanje.',
    icon: 'Bike',
    category: 'Zanati i kućni servisi',
    modules: ['dashboard', 'rentals', 'contacts', 'calendar', 'reservations', 'invoices', 'payments', 'maintenance', 'inventory', 'reports', 'settings'],
    featured: false,
    sortOrder: 92,
  },
  {
    name: 'Biciklistička radnja',
    slug: 'bike-shop',
    description: 'Prodaja i servis bicikala, inventar delova, klijenti i zakazivanje.',
    icon: 'Bike',
    category: 'Zanati i kućni servisi',
    modules: ['dashboard', 'contacts', 'inventory', 'service-center', 'appointments', 'invoices', 'pos', 'ecommerce', 'website', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 93,
  },
  {
    name: 'Čišćenje',
    slug: 'cleaning-services',
    description: 'Zakazivanje, klijenti, ekipa, oprema, fakturisanje i kvalitet kontrole.',
    icon: 'SprayCan',
    category: 'Zanati i kućni servisi',
    modules: ['dashboard', 'contacts', 'appointments', 'field-service', 'work-orders', 'employees', 'calendar', 'invoices', 'expenses', 'reports', 'settings', 'contracts', 'quality'],
    featured: false,
    sortOrder: 94,
  },
  {
    name: 'Električar',
    slug: 'electrician',
    description: 'Servisne intervencije, zakazivanje, klijenti, inventar delova i fakturisanje.',
    icon: 'Zap',
    category: 'Zanati i kućni servisi',
    modules: ['dashboard', 'contacts', 'appointments', 'field-service', 'work-orders', 'inventory', 'invoices', 'expenses', 'calendar', 'reports', 'settings', 'contracts'],
    featured: false,
    sortOrder: 95,
  },
  {
    name: 'Vrtlarenje',
    slug: 'gardening',
    description: 'Zakazivanje, klijenti, oprema, biljke, inventar i sezonski radovi.',
    icon: 'Flower2',
    category: 'Zanati i kućni servisi',
    modules: ['dashboard', 'contacts', 'appointments', 'field-service', 'calendar', 'inventory', 'invoices', 'expenses', 'reports', 'settings', 'contracts', 'ecommerce'],
    featured: false,
    sortOrder: 96,
  },
  {
    name: 'Majstor za sve (Handyman)',
    slug: 'handyman-services',
    description: 'Različiti popravki, zakazivanje, klijenti, inventar alata i fakturisanje.',
    icon: 'Screwdriver',
    category: 'Zanati i kućni servisi',
    modules: ['dashboard', 'contacts', 'appointments', 'field-service', 'work-orders', 'inventory', 'invoices', 'expenses', 'calendar', 'reports', 'settings', 'contracts'],
    featured: false,
    sortOrder: 97,
  },
  {
    name: 'Obućarska radnja',
    slug: 'shoemaker-services',
    description: 'Popravka obuće, klijenti, inventar materijala, zakazivanje i cene.',
    icon: 'Footprints',
    category: 'Zanati i kućni servisi',
    modules: ['dashboard', 'contacts', 'appointments', 'service-center', 'inventory', 'invoices', 'pos', 'expenses', 'reports', 'settings'],
    featured: false,
    sortOrder: 98,
  },
  {
    name: 'Geodetske usluge',
    slug: 'surveying-mapping',
    description: 'Geodetski izmera, projekti, oprema, klijenti, izveštaji i dokumentacija.',
    icon: 'Map',
    category: 'Zanati i kućni servisi',
    modules: ['dashboard', 'contacts', 'projects', 'measurements', 'documents', 'calendar', 'invoices', 'offers', 'reports', 'settings', 'blueprints'],
    featured: false,
    sortOrder: 99,
  },
]

// ============ ALL TEMPLATES ============
export const industryTemplatesData: IndustryTemplateData[] = [
  ...businessServices,
  ...cultureArts,
  ...education,
  ...eventsCommunity,
  ...foodBeverage,
  ...healthWellness,
  ...hospitalityTourism,
  ...manufacturingLogistics,
  ...realEstateConstruction,
  ...retail,
  ...tradesHomeServices,
]

// Category metadata
export const industryCategories = [
  { name: 'Biznis servisi', icon: 'Briefcase', count: businessServices.length },
  { name: 'Kultura i umetnost', icon: 'Palette', count: cultureArts.length },
  { name: 'Obrazovanje', icon: 'GraduationCap', count: education.length },
  { name: 'Događaji i zajednica', icon: 'PartyPopper', count: eventsCommunity.length },
  { name: 'Hrana i piće', icon: 'UtensilsCrossed', count: foodBeverage.length },
  { name: 'Zdravlje i wellness', icon: 'Heart', count: healthWellness.length },
  { name: 'Ugostiteljstvo i turizam', icon: 'Hotel', count: hospitalityTourism.length },
  { name: 'Proizvodnja i logistika', icon: 'Factory', count: manufacturingLogistics.length },
  { name: 'Nekretnine i građevina', icon: 'Building2', count: realEstateConstruction.length },
  { name: 'Trgovina', icon: 'ShoppingBag', count: retail.length },
  { name: 'Zanati i kućni servisi', icon: 'Wrench', count: tradesHomeServices.length },
]
