// Industry templates data for Odoo industry templates
// Maps Odoo's industry list to our existing module keys

export interface IndustryTemplateData {
  name: string        // Serbian name, e.g. "Pekara"
  slug: string        // English slug, e.g. "bakery"
  description: string // Short description in Serbian
  icon: string        // Lucide React icon name
  category: string    // Category in Serbian
  modules: string[]   // Array of our module keys that this industry uses
  featured: boolean   // Whether to feature on top
  sortOrder: number   // Display order within category
}

export const industryTemplatesData: IndustryTemplateData[] = [
  // ═══════════════════════════════════════════════════════════════
  // BIZNIS SERVISI
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Knjigovodstvena firma",
    slug: "accounting-firm",
    description: "Kompletno rešenje za knjigovodstvene firme sa fakturisanjem, obračunom troškova i usklađenošću sa zakonskim propisima.",
    icon: "Calculator",
    category: "Biznis servisi",
    modules: ["accounting", "invoices", "documents", "expenses", "contacts", "calendar", "reports", "spreadsheet", "signatures", "projects", "time-billing", "compliance", "laws"],
    featured: true,
    sortOrder: 1,
  },
  {
    name: "Reklamska agencija",
    slug: "marketing-agency",
    description: "Upravljanje marketinškim kampanjama, CRM, email i društvenim mrežama iz jedne platforme.",
    icon: "Megaphone",
    category: "Biznis servisi",
    modules: ["crm", "marketing-automation", "email-marketing", "social-media", "sms-marketing", "website", "blog", "cms", "seo", "contacts", "projects", "invoices", "reports"],
    featured: true,
    sortOrder: 2,
  },
  {
    name: "IT podrška",
    slug: "it-hardware-support",
    description: "Kompletno rešenje za IT kompanije — podrška, upravljanje sredstvima, ugovori i terenski servis.",
    icon: "Monitor",
    category: "Biznis servisi",
    modules: ["support", "assets", "inventory", "contracts", "field-service", "fleet", "calendar", "contacts", "projects", "knowledge-base", "invoices", "reports"],
    featured: false,
    sortOrder: 3,
  },
  {
    name: "Advokatska kancelarija",
    slug: "law-firm",
    description: "Rešenje za advokatske kancelarije sa praćenjem vremena, dokumentima, fakturisanjem i usklađenošću.",
    icon: "Scale",
    category: "Biznis servisi",
    modules: ["documents", "calendar", "contacts", "invoices", "time-billing", "spreadsheet", "signatures", "compliance", "laws"],
    featured: false,
    sortOrder: 4,
  },
  {
    name: "Revizija i sertifikacija",
    slug: "audit-certification",
    description: "Praćenje revizija, dokumentacija, izveštaji i usklađenost sa standardima i propisima.",
    icon: "ShieldCheck",
    category: "Biznis servisi",
    modules: ["compliance", "documents", "reports", "spreadsheet", "calendar", "contacts", "projects"],
    featured: false,
    sortOrder: 5,
  },
  {
    name: "Agencija za zapošljavanje",
    slug: "talent-acquisition",
    description: "Regrutacija, upravljanje kandidatima, CRM i marketing za agencije za zapošljavanje.",
    icon: "UserCheck",
    category: "Biznis servisi",
    modules: ["recruitment", "contacts", "crm", "calendar", "events", "email-marketing", "website", "blog", "reports"],
    featured: false,
    sortOrder: 6,
  },
  {
    name: "Fosilna goriva",
    slug: "fossil-fuel-trading",
    description: "Upravljanje zalihama, flotom, isporukama i prodajom fosilnih goriva.",
    icon: "Fuel",
    category: "Biznis servisi",
    modules: ["inventory", "fleet", "shipping", "contacts", "crm", "invoices", "expenses", "reports"],
    featured: false,
    sortOrder: 7,
  },
  {
    name: "Agencija za zaštitu životne sredine",
    slug: "environmental-agency",
    description: "Upravljanje usklađenošću, projektima i terenskim radom za agencije za zaštitu životne sredine.",
    icon: "Leaf",
    category: "Biznis servisi",
    modules: ["compliance", "calendar", "projects", "reports", "documents", "laws", "contacts", "field-service"],
    featured: false,
    sortOrder: 8,
  },
  {
    name: "Odoo partner",
    slug: "odoo-partner",
    description: "Kompletno rešenje za Odoo partnere — CRM, projekti, podrška i marketing.",
    icon: "Puzzle",
    category: "Biznis servisi",
    modules: ["crm", "projects", "support", "calendar", "contacts", "website", "blog", "marketing-automation", "invoices", "reports"],
    featured: false,
    sortOrder: 9,
  },
  {
    name: "Preprodaja softvera",
    slug: "software-reseller",
    description: "Upravljanje prodajom softvera, pretplatama, CRM, podrškom i e-trgovinom.",
    icon: "Package",
    category: "Biznis servisi",
    modules: ["crm", "contacts", "inventory", "ecommerce", "invoices", "support", "contracts", "subscriptions"],
    featured: false,
    sortOrder: 10,
  },

  // ═══════════════════════════════════════════════════════════════
  // KULTURA I UMETNOST
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Prodavnica umetnosti",
    slug: "arts-crafts-store",
    description: "E-trgovina, upravljanje zalihama i marketing za prodavnice umetnosti i zanata.",
    icon: "Palette",
    category: "Kultura i umetnost",
    modules: ["ecommerce", "inventory", "invoices", "contacts", "website", "blog", "social-media", "seo", "reviews"],
    featured: false,
    sortOrder: 1,
  },
  {
    name: "Koncertne dvorane",
    slug: "concert-halls",
    description: "Organizacija događaja, prodaja karata, marketing i kase za koncertne dvorane.",
    icon: "Music",
    category: "Kultura i umetnost",
    modules: ["events", "calendar", "contacts", "crm", "website", "marketing-automation", "email-marketing", "invoices", "pos"],
    featured: false,
    sortOrder: 2,
  },
  {
    name: "Galerija",
    slug: "gallery",
    description: "Upravljanje izložbama, online prisustvo, CRM i prodaja umetničkih dela.",
    icon: "Frame",
    category: "Kultura i umetnost",
    modules: ["website", "blog", "cms", "events", "contacts", "crm", "ecommerce", "invoices"],
    featured: false,
    sortOrder: 3,
  },
  {
    name: "Biblioteka",
    slug: "library",
    description: "Upravljanje bibliotečkim fondom, članstvom, katalogom i izdavanjem knjiga.",
    icon: "BookOpen",
    category: "Kultura i umetnost",
    modules: ["education", "contacts", "calendar", "library", "reports", "website", "inventory", "pos"],
    featured: false,
    sortOrder: 4,
  },
  {
    name: "Muzej",
    slug: "museum",
    description: "Upravljanje izložbama, posetama, prodajom suvenira i online prisustvom muzeja.",
    icon: "Landmark",
    category: "Kultura i umetnost",
    modules: ["website", "calendar", "events", "contacts", "inventory", "pos", "ecommerce", "invoices"],
    featured: false,
    sortOrder: 5,
  },
  {
    name: "Fotografija",
    slug: "photography",
    description: "Zakazivanje sesija, upravljanje klijentima, ugovori i prodaja fotografija.",
    icon: "Camera",
    category: "Kultura i umetnost",
    modules: ["calendar", "appointments", "contacts", "crm", "website", "blog", "invoices", "contracts"],
    featured: false,
    sortOrder: 6,
  },
  {
    name: "Tetoviranje",
    slug: "tattoo-shop",
    description: "Zakazivanje termina, galerija radova, recenzije i prodaja za studio tetoviranja.",
    icon: "PenTool",
    category: "Kultura i umetnost",
    modules: ["appointments", "calendar", "contacts", "website", "reviews", "pos", "invoices", "social-media"],
    featured: false,
    sortOrder: 7,
  },
  {
    name: "Pozorište",
    slug: "theater",
    description: "Upravljanje predstavama, prodaja karata, marketing i kase za pozorišta.",
    icon: "Theater",
    category: "Kultura i umetnost",
    modules: ["events", "calendar", "contacts", "pos", "website", "marketing-automation", "email-marketing", "invoices"],
    featured: false,
    sortOrder: 8,
  },

  // ═══════════════════════════════════════════════════════════════
  // OBRAZOVANJE
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Radionice",
    slug: "diy-workshops",
    description: "Organizacija edukativnih radionica, upis, e-trgovina i plaćanje.",
    icon: "Hammer",
    category: "Obrazovanje",
    modules: ["education", "calendar", "events", "contacts", "website", "blog", "ecommerce", "invoices", "pos"],
    featured: false,
    sortOrder: 1,
  },
  {
    name: "Auto-škola",
    slug: "driving-school",
    description: "Upravljanje upisima, rasporedom časova, plaćanjima i izdavanjem sertifikata.",
    icon: "Car",
    category: "Obrazovanje",
    modules: ["education", "enrollment", "contacts", "calendar", "scheduler", "payments", "invoices", "classroom"],
    featured: false,
    sortOrder: 2,
  },
  {
    name: "eLearning platforma",
    slug: "elearning-platform",
    description: "Kompletna eLearning platforma sa kursevima, zadacima, učionicama i e-trgovinom.",
    icon: "GraduationCap",
    category: "Obrazovanje",
    modules: ["education", "enrollment", "homework", "classroom", "timetable", "contacts", "website", "blog", "ecommerce"],
    featured: true,
    sortOrder: 3,
  },
  {
    name: "Studentska organizacija",
    slug: "student-organization",
    description: "Organizacija događaja, upravljanje članstvom, forum i komunikacija za studentske organizacije.",
    icon: "Users",
    category: "Obrazovanje",
    modules: ["events", "calendar", "contacts", "website", "blog", "forum", "email-marketing", "crm"],
    featured: false,
    sortOrder: 4,
  },

  // ═══════════════════════════════════════════════════════════════
  // DOGAĐAJI I ZAJEDNICA
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Coworking",
    slug: "coworking",
    description: "Upravljanje coworking prostorom, rezervacije, pretplate i naplate za članove.",
    icon: "Laptop",
    category: "Događaji i zajednica",
    modules: ["contacts", "calendar", "reservations", "subscriptions", "invoices", "payments", "website", "pos"],
    featured: false,
    sortOrder: 1,
  },
  {
    name: "Organizacija događaja",
    slug: "event-management",
    description: "Kompletno rešenje za organizaciju događaja — od planiranja do prodaje ulaznica.",
    icon: "PartyPopper",
    category: "Događaji i zajednica",
    modules: ["events", "calendar", "contacts", "crm", "website", "pos", "invoices", "email-marketing"],
    featured: true,
    sortOrder: 2,
  },
  {
    name: "Klub članova",
    slug: "members-club",
    description: "Upravljanje članstvom, pretplatama, događajima i komunikacijom sa članovima.",
    icon: "Crown",
    category: "Događaji i zajednica",
    modules: ["contacts", "subscriptions", "calendar", "events", "website", "email-marketing", "pos", "invoices"],
    featured: false,
    sortOrder: 3,
  },
  {
    name: "Neprofitna organizacija",
    slug: "nonprofit",
    description: "Upravljanje donacijama, volonterima, događajima i izveštavanje za neprofitne organizacije.",
    icon: "Heart",
    category: "Događaji i zajednica",
    modules: ["contacts", "accounting", "events", "calendar", "website", "blog", "email-marketing", "reports"],
    featured: false,
    sortOrder: 4,
  },
  {
    name: "Sportski događaji",
    slug: "sport-events",
    description: "Organizacija sportskih takmičenja, prodaja ulaznica, marketing i naplate.",
    icon: "Trophy",
    category: "Događaji i zajednica",
    modules: ["events", "calendar", "contacts", "crm", "website", "marketing-automation", "pos", "invoices"],
    featured: false,
    sortOrder: 5,
  },
  {
    name: "Sportski klub",
    slug: "sports-club",
    description: "Upravljanje članstvom, pretplatama, treninzima i događajima za sportski klub.",
    icon: "Medal",
    category: "Događaji i zajednica",
    modules: ["contacts", "calendar", "events", "subscriptions", "website", "pos", "invoices", "email-marketing"],
    featured: false,
    sortOrder: 6,
  },
  {
    name: "Letnji kampovi",
    slug: "summer-camps",
    description: "Upravljanje upisima, rasporedom, aktivnostima i naplatama za letnje kampove.",
    icon: "Sun",
    category: "Događaji i zajednica",
    modules: ["enrollment", "education", "calendar", "contacts", "events", "website", "payments", "pos", "invoices"],
    featured: false,
    sortOrder: 7,
  },
  {
    name: "Timski sportovi",
    slug: "team-sports",
    description: "Organizacija treninga, mečeva, upravljanje opremom i članstvom.",
    icon: "Dumbbell",
    category: "Događaji i zajednica",
    modules: ["calendar", "events", "contacts", "subscriptions", "website", "inventory", "pos", "invoices", "crm"],
    featured: false,
    sortOrder: 8,
  },
  {
    name: "Svadbeni planer",
    slug: "wedding-planner",
    description: "Planiranje venčanja, upravljanje dobavljačima, budžetom i projektima.",
    icon: "HeartHandshake",
    category: "Događaji i zajednica",
    modules: ["contacts", "calendar", "projects", "website", "blog", "invoices", "expenses", "events"],
    featured: false,
    sortOrder: 9,
  },

  // ═══════════════════════════════════════════════════════════════
  // HRANA I PIĆE
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Pekara",
    slug: "bakery",
    description: "Kase, upravljanje zalihama, e-trgovina, nabavka i lojalnost za pekare.",
    icon: "Croissant",
    category: "Hrana i piće",
    modules: ["pos", "inventory", "ecommerce", "invoices", "procurement", "loyalty", "email-marketing", "social-media", "website", "contacts", "calendar", "kitchen"],
    featured: true,
    sortOrder: 1,
  },
  {
    name: "Bar i kafana",
    slug: "bar-pub",
    description: "Kase, rezervacije, meni, narudžbine i lojalnost za barove i kafane.",
    icon: "Wine",
    category: "Hrana i piće",
    modules: ["pos", "reservations", "inventory", "invoices", "calendar", "contacts", "loyalty", "website", "menu", "orders"],
    featured: false,
    sortOrder: 2,
  },
  {
    name: "Distributer pića",
    slug: "beverage-distributor",
    description: "Upravljanje zalihama, flotom, rutama isporuke i prodajom za distributere pića.",
    icon: "Beer",
    category: "Hrana i piće",
    modules: ["inventory", "shipping", "fleet", "contacts", "crm", "invoices", "expenses", "routes", "delivery", "orders"],
    featured: false,
    sortOrder: 3,
  },
  {
    name: "Poslastičarnica",
    slug: "cake-store",
    description: "Kase, e-trgovina, zakazivanje torta i marketing za poslastičarnice.",
    icon: "Cake",
    category: "Hrana i piće",
    modules: ["pos", "ecommerce", "inventory", "calendar", "appointments", "contacts", "website", "blog", "reviews", "invoices"],
    featured: false,
    sortOrder: 4,
  },
  {
    name: "Slastičarnica",
    slug: "candy-shop",
    description: "E-trgovina, kase, upravljanje zalihama i marketing za slastičarnice.",
    icon: "Candy",
    category: "Hrana i piće",
    modules: ["ecommerce", "inventory", "pos", "invoices", "contacts", "website", "social-media", "seo", "reviews"],
    featured: false,
    sortOrder: 5,
  },
  {
    name: "Ketering",
    slug: "catering",
    description: "Upravljanje događajima, kuhinjom, isporukom i flotom za ketering servise.",
    icon: "ChefHat",
    category: "Hrana i piće",
    modules: ["events", "calendar", "contacts", "inventory", "kitchen", "orders", "invoices", "pos", "fleet", "delivery"],
    featured: false,
    sortOrder: 6,
  },
  {
    name: "Brza hrana",
    slug: "fast-food",
    description: "Kase, kuhinja, narudžbine, e-trgovina i dostava za brzu hranu.",
    icon: "UtensilsCrossed",
    category: "Hrana i piće",
    modules: ["pos", "kitchen", "inventory", "orders", "invoices", "ecommerce", "contacts", "website", "delivery"],
    featured: true,
    sortOrder: 7,
  },
  {
    name: "Kamioni za hranu",
    slug: "food-trucks",
    description: "Kase, kuhinja, ruta, flotom i marketing za kamione za hranu.",
    icon: "Truck",
    category: "Hrana i piće",
    modules: ["pos", "kitchen", "inventory", "orders", "invoices", "calendar", "fleet", "routes", "social-media", "website"],
    featured: false,
    sortOrder: 8,
  },
  {
    name: "Restoran",
    slug: "fine-dining",
    description: "Kompletno rešenje za restorane — rezervacije, meni, kuhinja, kase i lojalnost.",
    icon: "Utensils",
    category: "Hrana i piće",
    modules: ["reservations", "menu", "kitchen", "orders", "pos", "inventory", "invoices", "contacts", "calendar", "website", "reviews", "loyalty"],
    featured: true,
    sortOrder: 9,
  },
  {
    name: "Dostava hrane",
    slug: "takeaway-restaurant",
    description: "E-trgovina, narudžbine, dostava, rute i recenzije za restorane sa dostavom.",
    icon: "Bike",
    category: "Hrana i piće",
    modules: ["ecommerce", "orders", "delivery", "routes", "inventory", "kitchen", "pos", "invoices", "contacts", "website", "reviews"],
    featured: false,
    sortOrder: 10,
  },

  // ═══════════════════════════════════════════════════════════════
  // ZDRAVLJE I WELLNESS
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Penjački teretana",
    slug: "climbing-gym",
    description: "Pretplate, zakazivanje, događaji i kase za penjačke teretane.",
    icon: "Mountain",
    category: "Zdravlje i wellness",
    modules: ["contacts", "subscriptions", "calendar", "events", "pos", "website", "inventory", "invoices"],
    featured: false,
    sortOrder: 1,
  },
  {
    name: "Optika",
    slug: "eyewear-store",
    description: "Zakazivanje pregleda, prodaja naftika, e-trgovina i recenzije za optike.",
    icon: "Glasses",
    category: "Zdravlje i wellness",
    modules: ["contacts", "inventory", "ecommerce", "pos", "invoices", "appointments", "website", "seo", "reviews"],
    featured: false,
    sortOrder: 2,
  },
  {
    name: "Fitnes centar",
    slug: "fitness-center",
    description: "Pretplate, zakazivanje treninga, lojalnost i marketing za fitnes centre.",
    icon: "Dumbbell",
    category: "Zdravlje i wellness",
    modules: ["subscriptions", "contacts", "calendar", "events", "appointments", "pos", "website", "loyalty", "email-marketing", "invoices"],
    featured: true,
    sortOrder: 3,
  },
  {
    name: "Frizerski salon",
    slug: "hair-salon",
    description: "Zakazivanje termina, kase, recenzije i društvene mreže za frizere.",
    icon: "Scissors",
    category: "Zdravlje i wellness",
    modules: ["appointments", "calendar", "contacts", "pos", "website", "reviews", "social-media", "invoices"],
    featured: false,
    sortOrder: 4,
  },
  {
    name: "Personalni trener",
    slug: "personal-trainer",
    description: "Zakazivanje treninga, pretplate, klijenti i marketing za personalne trenere.",
    icon: "Activity",
    category: "Zdravlje i wellness",
    modules: ["appointments", "contacts", "calendar", "subscriptions", "website", "social-media", "invoices", "loyalty"],
    featured: false,
    sortOrder: 5,
  },
  {
    name: "Apoteka",
    slug: "pharmacy",
    description: "Zalihe, kase, recepti, izveštaji i usklađenost za apoteke.",
    icon: "Pill",
    category: "Zdravlje i wellness",
    modules: ["inventory", "pos", "contacts", "invoices", "reports", "compliance", "website", "prescriptions"],
    featured: false,
    sortOrder: 6,
  },
  {
    name: "Veterinarska ambulanta",
    slug: "veterinary-clinic",
    description: "Zakazivanje, kartoni pacijenata, recepti, zalihe i fakturisanje za veterinarske ambulante.",
    icon: "Dog",
    category: "Zdravlje i wellness",
    modules: ["appointments", "calendar", "contacts", "inventory", "invoices", "patients", "prescriptions", "medical-records", "website"],
    featured: false,
    sortOrder: 7,
  },
  {
    name: "Wellness praktičar",
    slug: "wellness-practitioner",
    description: "Zakazivanje, pretplate, klijenti i marketing za wellness prakse.",
    icon: "Sparkles",
    category: "Zdravlje i wellness",
    modules: ["appointments", "calendar", "contacts", "subscriptions", "website", "social-media", "invoices", "loyalty"],
    featured: false,
    sortOrder: 8,
  },
  {
    name: "Joga i pilates studio",
    slug: "yoga-pilates",
    description: "Zakazivanje časova, pretplate, događaji i marketing za joga i pilates studije.",
    icon: "Flower2",
    category: "Zdravlje i wellness",
    modules: ["appointments", "calendar", "contacts", "subscriptions", "events", "website", "social-media", "invoices"],
    featured: false,
    sortOrder: 9,
  },

  // ═══════════════════════════════════════════════════════════════
  // UGOSTITELJSTVO I TURIZAM
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Kuglana",
    slug: "bowling-alleys",
    description: "Rezervacije, kase, događaji i upravljanje za kuglane.",
    icon: "CircleDot",
    category: "Ugostiteljstvo i turizam",
    modules: ["reservations", "pos", "calendar", "contacts", "inventory", "website", "events", "invoices"],
    featured: false,
    sortOrder: 1,
  },
  {
    name: "Kamp",
    slug: "campsite",
    description: "Rezervacije, kalendar, zalihe, kase i e-trgovina za kampove.",
    icon: "Tent",
    category: "Ugostiteljstvo i turizam",
    modules: ["reservations", "calendar", "contacts", "inventory", "pos", "website", "ecommerce", "invoices"],
    featured: false,
    sortOrder: 2,
  },
  {
    name: "Escape sobe",
    slug: "escape-rooms",
    description: "Rezervacije, kalendar, događaji i marketing za escape sobe.",
    icon: "KeyRound",
    category: "Ugostiteljstvo i turizam",
    modules: ["reservations", "calendar", "contacts", "pos", "events", "website", "email-marketing", "invoices"],
    featured: false,
    sortOrder: 3,
  },
  {
    name: "Guest house",
    slug: "guest-house",
    description: "Rezervacije, kalendar, smještaj i recenzije za guest house.",
    icon: "Home",
    category: "Ugostiteljstvo i turizam",
    modules: ["reservations", "calendar", "contacts", "inventory", "pos", "website", "reviews", "invoices"],
    featured: false,
    sortOrder: 4,
  },
  {
    name: "Obilasci grada",
    slug: "guided-tours",
    description: "Kalendar, rezervacije, e-trgovina, recenzije i marketing za obilaske grada.",
    icon: "MapPin",
    category: "Ugostiteljstvo i turizam",
    modules: ["calendar", "reservations", "contacts", "website", "ecommerce", "reviews", "social-media", "invoices"],
    featured: false,
    sortOrder: 5,
  },
  {
    name: "Vikendica",
    slug: "holiday-house",
    description: "Rezervacije, kalendar, nekretnine, e-trgovina i recenzije za vikendice.",
    icon: "House",
    category: "Ugostiteljstvo i turizam",
    modules: ["reservations", "calendar", "contacts", "property", "website", "ecommerce", "reviews", "invoices"],
    featured: false,
    sortOrder: 6,
  },
  {
    name: "Hotel",
    slug: "hotel",
    description: "Kompletno rešenje za hotele — rezervacije, restoran, kase, lojalnost i recenzije.",
    icon: "Hotel",
    category: "Ugostiteljstvo i turizam",
    modules: ["reservations", "calendar", "contacts", "inventory", "pos", "kitchen", "orders", "website", "reviews", "loyalty", "invoices"],
    featured: true,
    sortOrder: 7,
  },
  {
    name: "Noćni klub",
    slug: "night-clubs",
    description: "Kalendar, događaji, kase, rezervacije i marketing za noćne klubove.",
    icon: "Disco",
    category: "Ugostiteljstvo i turizam",
    modules: ["calendar", "events", "pos", "reservations", "contacts", "inventory", "website", "social-media", "invoices"],
    featured: false,
    sortOrder: 8,
  },
  {
    name: "Aktivnosti na otvorenom",
    slug: "outdoor-activities",
    description: "Kalendar, rezervacije, događaji, e-trgovina i recenzije za aktivnosti na otvorenom.",
    icon: "Trees",
    category: "Ugostiteljstvo i turizam",
    modules: ["calendar", "reservations", "contacts", "events", "website", "ecommerce", "reviews", "inventory", "invoices"],
    featured: false,
    sortOrder: 9,
  },
  {
    name: "Spa resort",
    slug: "spa-resort",
    description: "Rezervacije, tretmani, kalendar, kase, lojalnost i recenzije za spa centre.",
    icon: "Droplets",
    category: "Ugostiteljstvo i turizam",
    modules: ["reservations", "appointments", "calendar", "contacts", "inventory", "pos", "website", "reviews", "loyalty", "invoices"],
    featured: false,
    sortOrder: 10,
  },

  // ═══════════════════════════════════════════════════════════════
  // PROIZVODNJA I LOGISTIKA
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Logistika trećih strana",
    slug: "third-party-logistics",
    description: "Kompletno rešenje za 3PL — transport, flota, magacin, rute i isporuke.",
    icon: "Container",
    category: "Proizvodnja i logistika",
    modules: ["shipping", "fleet", "inventory", "routes", "delivery", "contacts", "crm", "invoices", "reports"],
    featured: true,
    sortOrder: 1,
  },
  {
    name: "Drvodeljci",
    slug: "carpenter",
    description: "Proizvodnja, zalihe, narudžbine, projekti i CRM za stolare i drvodeljce.",
    icon: "Hammer",
    category: "Proizvodnja i logistika",
    modules: ["manufacturing", "inventory", "orders", "contacts", "crm", "invoices", "projects", "calendar"],
    featured: false,
    sortOrder: 2,
  },
  {
    name: "Korporativni pokloni",
    slug: "corporate-gifts",
    description: "Zalihe, e-trgovina, narudžbine, dostava i CRM za korporativne poklone.",
    icon: "Gift",
    category: "Proizvodnja i logistika",
    modules: ["inventory", "ecommerce", "contacts", "crm", "website", "orders", "delivery", "invoices"],
    featured: false,
    sortOrder: 3,
  },
  {
    name: "Proizvodnja nameštaja",
    slug: "custom-furniture",
    description: "Proizvodnja, zalihe, projekti, narudžbine i CRM za proizvodnju nameštaja.",
    icon: "Armchair",
    category: "Proizvodnja i logistika",
    modules: ["manufacturing", "inventory", "projects", "contacts", "crm", "orders", "invoices", "calendar"],
    featured: false,
    sortOrder: 4,
  },
  {
    name: "Distribucija hrane",
    slug: "food-distribution",
    description: "Zalihe, transport, flota, rute, kvalitet i isporuka za distribuciju hrane.",
    icon: "Truck",
    category: "Proizvodnja i logistika",
    modules: ["inventory", "shipping", "fleet", "routes", "delivery", "contacts", "crm", "invoices", "quality", "expenses"],
    featured: false,
    sortOrder: 5,
  },
  {
    name: "Metaloprerada",
    slug: "metal-fabricator",
    description: "Proizvodnja, kvalitet, održavanje, sredstva i narudžbine za metalopreradu.",
    icon: "Cog",
    category: "Proizvodnja i logistika",
    modules: ["manufacturing", "inventory", "quality", "maintenance", "assets", "orders", "contacts", "crm", "invoices", "projects"],
    featured: false,
    sortOrder: 6,
  },
  {
    name: "Mikro pivara",
    slug: "micro-brewery",
    description: "Proizvodnja piva, zalihe, kvalitet, kase i prodaja za mikro pivare.",
    icon: "Beer",
    category: "Proizvodnja i logistika",
    modules: ["manufacturing", "inventory", "quality", "contacts", "crm", "pos", "website", "invoices"],
    featured: false,
    sortOrder: 7,
  },
  {
    name: "Tekstilna proizvodnja",
    slug: "textile-manufacturing",
    description: "Proizvodnja, zalihe, kvalitet, e-trgovina i prodaja za tekstilnu industriju.",
    icon: "Shirt",
    category: "Proizvodnja i logistika",
    modules: ["manufacturing", "inventory", "quality", "orders", "contacts", "crm", "ecommerce", "invoices", "reports"],
    featured: false,
    sortOrder: 8,
  },
  {
    name: "Vinograd",
    slug: "vineyard",
    description: "Proizvodnja vina, zalihe, kvalitet, e-trgovina, kase i prodaja za vinograde.",
    icon: "Grape",
    category: "Proizvodnja i logistika",
    modules: ["manufacturing", "inventory", "quality", "contacts", "crm", "ecommerce", "website", "pos", "invoices"],
    featured: false,
    sortOrder: 9,
  },

  // ═══════════════════════════════════════════════════════════════
  // NEKRETNINE I GRAĐEVINA
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Arhitektonska firma",
    slug: "architecture-firm",
    description: "Projekti, dokumentacija, planovi, CRM i izveštaji za arhitektonske firme.",
    icon: "Building2",
    category: "Nekretnine i građevina",
    modules: ["projects", "documents", "contacts", "crm", "calendar", "blueprints", "reports", "website", "invoices"],
    featured: false,
    sortOrder: 1,
  },
  {
    name: "Zajednica vlasnika",
    slug: "property-owner-association",
    description: "Nekretnine, komunalije, radni nalozi, održavanje i računovodstvo za zajednice vlasnika.",
    icon: "Building",
    category: "Nekretnine i građevina",
    modules: ["property", "utilities", "work-orders", "maintenance", "accounting", "contacts", "calendar", "invoices", "compliance"],
    featured: false,
    sortOrder: 2,
  },
  {
    name: "Građevinar",
    slug: "construction-builder",
    description: "Projekti, gradilište, sredstva, flota, održavanje i izveštaji za građevinske firme.",
    icon: "HardHat",
    category: "Nekretnine i građevina",
    modules: ["projects", "construction-site", "assets", "fleet", "maintenance", "inventory", "contacts", "crm", "invoices", "calendar", "reports"],
    featured: true,
    sortOrder: 3,
  },
  {
    name: "Investitor",
    slug: "construction-developer",
    description: "Projekti, gradilište, planovi, CRM i izveštaji za investitore u građevinarstvu.",
    icon: "Crane",
    category: "Nekretnine i građevina",
    modules: ["projects", "construction-site", "contacts", "crm", "blueprints", "calendar", "reports", "website"],
    featured: false,
    sortOrder: 4,
  },
  {
    name: "HVAC servisi",
    slug: "hvac-services",
    description: "Održavanje, terenski servis, flota, zakazivanje i radni nalozi za HVAC servise.",
    icon: "Thermometer",
    category: "Nekretnine i građevina",
    modules: ["maintenance", "field-service", "fleet", "calendar", "contacts", "crm", "appointments", "inventory", "invoices", "work-orders"],
    featured: false,
    sortOrder: 5,
  },
  {
    name: "Upravljanje nekretninama",
    slug: "property-management",
    description: "Kompletno rešenje za upravljanje nekretninama — zakup, održavanje, računovodstvo i izveštaji.",
    icon: "Key",
    category: "Nekretnine i građevina",
    modules: ["property", "rentals", "property-viewings", "maintenance", "contracts", "accounting", "contacts", "calendar", "work-orders", "utilities", "invoices", "reports"],
    featured: true,
    sortOrder: 6,
  },
  {
    name: "Izdavanje mašina",
    slug: "machine-tools-rental",
    description: "Zakup, flota, održavanje, zalihe, ugovori i isporuka za izdavanje mašina.",
    icon: "Wrench",
    category: "Nekretnine i građevina",
    modules: ["rentals", "fleet", "maintenance", "inventory", "contacts", "crm", "contracts", "calendar", "invoices", "delivery"],
    featured: false,
    sortOrder: 7,
  },
  {
    name: "Agencija za nekretnine",
    slug: "real-estate-agency",
    description: "Nekretnine, pregledi, CRM, marketing i izveštaji za agencije za nekretnine.",
    icon: "DoorOpen",
    category: "Nekretnine i građevina",
    modules: ["property", "property-viewings", "contacts", "crm", "calendar", "website", "blog", "social-media", "invoices", "reports"],
    featured: false,
    sortOrder: 8,
  },
  {
    name: "Solarne instalacije",
    slug: "solar-energy",
    description: "Projekti, instalacije, održavanje, sredstva i fakturisanje za solarne instalacije.",
    icon: "SunMedium",
    category: "Nekretnine i građevina",
    modules: ["projects", "maintenance", "inventory", "assets", "contacts", "crm", "calendar", "invoices"],
    featured: false,
    sortOrder: 9,
  },

  // ═══════════════════════════════════════════════════════════════
  // TRGOVINA
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Poljoprivredna prodavnica",
    slug: "agricultural-store",
    description: "Zalihe, kase, e-trgovina, nabavka i CRM za poljoprivredne prodavnice.",
    icon: "Wheat",
    category: "Trgovina",
    modules: ["inventory", "pos", "ecommerce", "contacts", "crm", "website", "invoices", "procurement"],
    featured: false,
    sortOrder: 1,
  },
  {
    name: "Auto delovi",
    slug: "automobile-spare-parts",
    description: "Zalihe, kase, e-trgovina, barkod i nabavka za prodavce auto delova.",
    icon: "Cog",
    category: "Trgovina",
    modules: ["inventory", "pos", "ecommerce", "contacts", "crm", "website", "invoices", "procurement", "barcode"],
    featured: false,
    sortOrder: 2,
  },
  {
    name: "Knjižara",
    slug: "bookstore",
    description: "Zalihe, kase, e-trgovina, blog i nabavka za knjižare.",
    icon: "BookOpen",
    category: "Trgovina",
    modules: ["inventory", "pos", "ecommerce", "contacts", "website", "blog", "reviews", "invoices", "procurement"],
    featured: false,
    sortOrder: 3,
  },
  {
    name: "Prodavnica odeće",
    slug: "clothing-store",
    description: "Zalihe, e-trgovina, kase, SEO, društvene mreže i nabavka za prodavnice odeće.",
    icon: "Shirt",
    category: "Trgovina",
    modules: ["inventory", "ecommerce", "pos", "contacts", "crm", "website", "seo", "social-media", "reviews", "invoices", "procurement"],
    featured: false,
    sortOrder: 4,
  },
  {
    name: "Kozmetika",
    slug: "cosmetics-store",
    description: "Zalihe, e-trgovina, kase, lojalnost i marketing za kozmetičke prodavnice.",
    icon: "Sparkles",
    category: "Trgovina",
    modules: ["inventory", "ecommerce", "pos", "contacts", "crm", "website", "seo", "social-media", "reviews", "invoices", "loyalty"],
    featured: false,
    sortOrder: 5,
  },
  {
    name: "Dropshipping",
    slug: "dropshipping",
    description: "E-trgovina, isporuka, transport, SEO i narudžbine za dropshipping posao.",
    icon: "PackageCheck",
    category: "Trgovina",
    modules: ["ecommerce", "inventory", "shipping", "delivery", "contacts", "crm", "website", "seo", "invoices", "orders"],
    featured: false,
    sortOrder: 6,
  },
  {
    name: "Elektro prodavnica",
    slug: "electronic-store",
    description: "Zalihe, kase, e-trgovina, garancije i nabavka za elektro prodavnice.",
    icon: "Zap",
    category: "Trgovina",
    modules: ["inventory", "pos", "ecommerce", "contacts", "crm", "website", "seo", "reviews", "invoices", "procurement", "warranty"],
    featured: false,
    sortOrder: 7,
  },
  {
    name: "Cvećara",
    slug: "florist",
    description: "E-trgovina, kase, zakazivanje, dostava i društvene mreže za cvećare.",
    icon: "Flower2",
    category: "Trgovina",
    modules: ["ecommerce", "pos", "inventory", "calendar", "appointments", "delivery", "contacts", "website", "social-media", "reviews", "invoices"],
    featured: false,
    sortOrder: 8,
  },
  {
    name: "Supermarket",
    slug: "grocery-store",
    description: "Kompletno rešenje za supermarkete — zalihe, kase, barkod, kvalitet i isporuka.",
    icon: "ShoppingCart",
    category: "Trgovina",
    modules: ["inventory", "pos", "ecommerce", "contacts", "procurement", "barcode", "quality", "invoices", "reports", "delivery"],
    featured: true,
    sortOrder: 9,
  },
  {
    name: "Prodavnica nameštaja",
    slug: "furniture-store",
    description: "Zalihe, e-trgovina, kase, SEO, dostava i nabavka za prodavnice nameštaja.",
    icon: "Sofa",
    category: "Trgovina",
    modules: ["inventory", "ecommerce", "pos", "contacts", "crm", "website", "seo", "reviews", "delivery", "invoices", "procurement"],
    featured: false,
    sortOrder: 10,
  },
  {
    name: "Prodavnica alata",
    slug: "hardware-store",
    description: "Zalihe, kase, e-trgovina, CRM i nabavka za prodavnice alata.",
    icon: "Wrench",
    category: "Trgovina",
    modules: ["inventory", "pos", "ecommerce", "contacts", "crm", "website", "reviews", "invoices", "procurement"],
    featured: false,
    sortOrder: 11,
  },
  {
    name: "Prodavnica igračaka",
    slug: "toy-store",
    description: "Zalihe, e-trgovina, kase, SEO, društvene mreže i recenzije za prodavnice igračaka.",
    icon: "Gamepad2",
    category: "Trgovina",
    modules: ["inventory", "ecommerce", "pos", "contacts", "website", "seo", "social-media", "reviews", "invoices"],
    featured: false,
    sortOrder: 12,
  },
  {
    name: "Vinoteka",
    slug: "wine-shop",
    description: "Zalihe, kase, e-trgovina, lojalnost i prodaja za vinoteku.",
    icon: "Wine",
    category: "Trgovina",
    modules: ["inventory", "pos", "ecommerce", "contacts", "crm", "website", "reviews", "invoices", "loyalty"],
    featured: false,
    sortOrder: 13,
  },

  // ═══════════════════════════════════════════════════════════════
  // ZANATI I KUĆNE SERVISI
  // ═══════════════════════════════════════════════════════════════
  {
    name: "Izdavanje bicikala",
    slug: "bike-leasing",
    description: "Zakup, flota, održavanje, zalihe, ugovori i fakturisanje za izdavanje bicikala.",
    icon: "Bike",
    category: "Zanati i kućni servisi",
    modules: ["rentals", "fleet", "maintenance", "inventory", "contacts", "crm", "contracts", "calendar", "invoices"],
    featured: false,
    sortOrder: 1,
  },
  {
    name: "Prodavnica bicikala",
    slug: "bike-shop",
    description: "Zalihe, kase, e-trgovina, servis, recenzije i nabavka za prodavnice bicikala.",
    icon: "Bike",
    category: "Zanati i kućni servisi",
    modules: ["inventory", "pos", "ecommerce", "maintenance", "contacts", "website", "reviews", "invoices", "procurement"],
    featured: false,
    sortOrder: 2,
  },
  {
    name: "Čišćenje",
    slug: "cleaning-services",
    description: "Terenski servis, zakazivanje, flota, radni nalozi za servise čišćenja.",
    icon: "SprayCan",
    category: "Zanati i kućni servisi",
    modules: ["field-service", "calendar", "appointments", "contacts", "crm", "fleet", "work-orders", "invoices"],
    featured: false,
    sortOrder: 3,
  },
  {
    name: "Električar",
    slug: "electrician",
    description: "Terenski servis, zakazivanje, flota, sredstva i radni nalozi za električare.",
    icon: "Zap",
    category: "Zanati i kućni servisi",
    modules: ["field-service", "calendar", "appointments", "contacts", "fleet", "work-orders", "assets", "inventory", "invoices"],
    featured: false,
    sortOrder: 4,
  },
  {
    name: "Vrtnarstvo",
    slug: "gardening",
    description: "Terenski servis, zakazivanje, flota, zalihe i radni nalozi za vrtnarske servise.",
    icon: "TreePine",
    category: "Zanati i kućni servisi",
    modules: ["field-service", "calendar", "appointments", "contacts", "fleet", "inventory", "invoices", "work-orders"],
    featured: false,
    sortOrder: 5,
  },
  {
    name: "Majstor",
    slug: "handyman-services",
    description: "Terenski servis, zakazivanje, flota, zalihe i radni nalozi za majstorske servise.",
    icon: "Hand",
    category: "Zanati i kućni servisi",
    modules: ["field-service", "calendar", "appointments", "contacts", "fleet", "work-orders", "inventory", "invoices"],
    featured: false,
    sortOrder: 6,
  },
  {
    name: "Obućar",
    slug: "shoemaker-services",
    description: "Terenski servis, zakazivanje, klijenti i fakturisanje za obućarske servise.",
    icon: "Footprints",
    category: "Zanati i kućni servisi",
    modules: ["field-service", "appointments", "contacts", "calendar", "invoices", "expenses", "pos", "website"],
    featured: false,
    sortOrder: 7,
  },
  {
    name: "Geodetske usluge",
    slug: "surveying-mapping",
    description: "Projekti, terenski rad, dokumentacija i izveštaji za geodetske usluge.",
    icon: "Compass",
    category: "Zanati i kućni servisi",
    modules: ["projects", "calendar", "field-service", "contacts", "crm", "documents", "reports", "invoices"],
    featured: false,
    sortOrder: 8,
  },
];
