// Industry Templates ("Namene") - Odoo-style pre-configured module sets
// Each template defines which modules are active for a specific industry type.

export interface IndustryTemplateData {
  name: string
  slug: string
  description: string
  icon: string
  category: string
  modules: string[]
  featured: boolean
  sortOrder: number
}

// ============ RAČUNOVODSTVO I FINANSIJE (7) ============
const accountingFinance: IndustryTemplateData[] = [
  {
    name: 'Računovodstvena firma',
    slug: 'accounting-firm',
    description: 'Kompletno računovodstvo, knjiženje, protokol, fiskalizacija i izveštaji za klijente.',
    icon: 'Calculator',
    category: 'Računovodstvo i finansije',
    modules: ['dashboard', 'contacts', 'finance', 'invoices', 'accounting', 'protocol', 'reports', 'calendar', 'documents', 'expenses', 'settings', 'automation', 'bank-sync', 'payments', 'contracts', 'offers', 'subscriptions'],
    featured: true,
    sortOrder: 1,
  },
  {
    name: 'Knjigovodstvena agencija',
    slug: 'bookkeeping-agency',
    description: 'Vođenje knjiga za više klijenata, izdavanje faktura, bankovna usklađenost i izveštaji.',
    icon: 'BookOpen',
    category: 'Računovodstvo i finansije',
    modules: ['dashboard', 'contacts', 'invoices', 'accounting', 'protocol', 'reports', 'calendar', 'documents', 'expenses', 'settings', 'bank-sync', 'payments', 'offers', 'subscriptions'],
    featured: false,
    sortOrder: 100,
  },
  {
    name: 'Revizija i sertifikacija',
    slug: 'audit-certification',
    description: 'Revizija finansijskih izveštaja, sertifikacija standarda, praćenje naloga i nalazi.',
    icon: 'ShieldCheck',
    category: 'Računovodstvo i finansije',
    modules: ['dashboard', 'contacts', 'finance', 'invoices', 'accounting', 'protocol', 'reports', 'documents', 'standards', 'projects', 'calendar', 'settings', 'automation'],
    featured: false,
    sortOrder: 3,
  },
  {
    name: 'Savjetovanje za finansije',
    slug: 'financial-consulting',
    description: 'Finansijsko savjetovanje, investicioni planovi, analiza, izvještaji i upravljanje klijentima.',
    icon: 'TrendingUp',
    category: 'Računovodstvo i finansije',
    modules: ['dashboard', 'contacts', 'crm', 'projects', 'calendar', 'documents', 'invoices', 'offers', 'contracts', 'reports', 'settings', 'finance'],
    featured: true,
    sortOrder: 101,
  },
  {
    name: 'Faktoring i lizing',
    slug: 'factoring-leasing',
    description: 'Upravljanje faktoring ugovorima, lizing najma, dospijeća, kamate i naplate.',
    icon: 'Landmark',
    category: 'Računovodstvo i finansije',
    modules: ['dashboard', 'contacts', 'finance', 'invoices', 'contracts', 'payments', 'accounting', 'reports', 'calendar', 'documents', 'settings', 'bank-sync', 'offers'],
    featured: false,
    sortOrder: 102,
  },
  {
    name: 'Zapošljavanje talenata',
    slug: 'talent-acquisition',
    description: 'Regrutacija, selekcija kandidata, intervjui, praćenje i plasman kadrova.',
    icon: 'UserSearch',
    category: 'Računovodstvo i finansije',
    modules: ['dashboard', 'contacts', 'recruitment', 'employees', 'calendar', 'crm', 'email-marketing', 'documents', 'reports', 'settings', 'referrals', 'skills'],
    featured: false,
    sortOrder: 6,
  },
  {
    name: 'IT konsalting i razvoj',
    slug: 'it-consulting',
    description: 'Projektni menadžment, development timovi, zakazivanje i fakturisanje.',
    icon: 'Code2',
    category: 'Računovodstvo i finansije',
    modules: ['dashboard', 'projects', 'contacts', 'employees', 'time-tracking', 'time-billing', 'calendar', 'documents', 'invoices', 'offers', 'reports', 'settings', 'knowledge-base', 'chat', 'automation'],
    featured: false,
    sortOrder: 10,
  },
]

// ============ UGOSTITELJSTVO I TURIZAM (27) ============
const hospitalityTourism: IndustryTemplateData[] = [
  {
    name: 'Restoran',
    slug: 'restaurant',
    description: 'Kompletni restoranski sistem: rezervacije, meni, porudžbine, kuhinja, POS i klijenti.',
    icon: 'ChefHat',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'restaurant', 'reservations', 'menu', 'orders', 'kitchen', 'pos', 'inventory', 'contacts', 'invoices', 'expenses', 'calendar', 'reports', 'settings', 'coupons', 'reviews', 'loyalty'],
    featured: true,
    sortOrder: 40,
  },
  {
    name: 'Restoran sa finom kuhinjom',
    slug: 'fine-dining-restaurant',
    description: 'Premium restoranski sistem sa naprednim menijem, vinskom kartom i VIP rezervacijama.',
    icon: 'UtensilsCrossed',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'restaurant', 'reservations', 'menu', 'orders', 'kitchen', 'pos', 'inventory', 'contacts', 'invoices', 'expenses', 'calendar', 'reports', 'settings', 'coupons', 'reviews', 'loyalty'],
    featured: false,
    sortOrder: 103,
  },
  {
    name: 'Hotel',
    slug: 'hotel',
    description: 'Kompletni hotelski sistem: sobe, rezervacije, gosti, restoran, POS i finansije.',
    icon: 'Hotel',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'reservations', 'restaurant', 'menu', 'orders', 'kitchen', 'pos', 'property', 'contacts', 'calendar', 'invoices', 'payments', 'expenses', 'reports', 'settings', 'reviews', 'coupons', 'loyalty', 'maintenance', 'employees'],
    featured: true,
    sortOrder: 57,
  },
  {
    name: 'Bar i pub',
    slug: 'bar-pub',
    description: 'Upravljanje restoranskim porudžbinama, piće, rezervacije, POS i zalihe.',
    icon: 'Beer',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'restaurant', 'reservations', 'menu', 'kitchen', 'orders', 'pos', 'inventory', 'invoices', 'expenses', 'calendar', 'reports', 'settings', 'coupons'],
    featured: false,
    sortOrder: 33,
  },
  {
    name: 'Kafić',
    slug: 'coffee-shop',
    description: 'Kafanska ponuda, kolači, rezervacije, POS, loyalnost i marketing.',
    icon: 'Coffee',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'restaurant', 'reservations', 'menu', 'orders', 'kitchen', 'pos', 'inventory', 'contacts', 'invoices', 'expenses', 'calendar', 'reports', 'settings', 'coupons', 'loyalty'],
    featured: true,
    sortOrder: 104,
  },
  {
    name: 'Brza hrana',
    slug: 'fast-food',
    description: 'POS, meni, naručivanje, porudžbine, kuhinja, isporuka i zalihe.',
    icon: 'Burger',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'restaurant', 'menu', 'orders', 'kitchen', 'pos', 'inventory', 'delivery', 'invoices', 'expenses', 'reports', 'settings', 'coupons', 'loyalty'],
    featured: true,
    sortOrder: 38,
  },
  {
    name: 'Ketering',
    slug: 'catering',
    description: 'Porudžbine hrane za evente, meni, sirovine, isporuke, kalendar i klijenti.',
    icon: 'UtensilsCrossed',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'contacts', 'crm', 'calendar', 'events', 'invoices', 'offers', 'kitchen', 'inventory', 'procurement', 'delivery', 'reports', 'settings', 'expenses'],
    featured: false,
    sortOrder: 37,
  },
  {
    name: 'Dostava hrane',
    slug: 'food-delivery',
    description: 'Logistika dostave hrane, narudžbe, kuriri, praćenje isporuka i plaćanje.',
    icon: 'Truck',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'contacts', 'orders', 'delivery', 'routes', 'fleet', 'inventory', 'invoices', 'expenses', 'calendar', 'reports', 'settings', 'ecommerce', 'coupons'],
    featured: false,
    sortOrder: 105,
  },
  {
    name: 'Pizzeria',
    slug: 'pizzeria',
    description: 'Pizza narudžbine, meni, sirovine, pećnica, dostava, POS i online naručivanje.',
    icon: 'Pizza',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'restaurant', 'menu', 'orders', 'kitchen', 'pos', 'inventory', 'delivery', 'invoices', 'expenses', 'calendar', 'reports', 'settings', 'coupons', 'ecommerce'],
    featured: false,
    sortOrder: 106,
  },
  {
    name: 'Poslastičarnica',
    slug: 'cake-store',
    description: 'Porudžbine torta i kolača, recepti, sirovine, zakazivanje preuzimanja i marketing.',
    icon: 'Cake',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'kitchen', 'calendar', 'appointments', 'social-media', 'website', 'reports', 'settings', 'offers', 'ecommerce'],
    featured: false,
    sortOrder: 35,
  },
  {
    name: 'Noćni klub',
    slug: 'night-club',
    description: 'Događaji, DJ raspored, ulaznice, POS, rezervacije VIP i marketing.',
    icon: 'Disc',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'events', 'calendar', 'reservations', 'pos', 'inventory', 'invoices', 'coupons', 'social-media', 'website', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 58,
  },
  {
    name: 'Hostel',
    slug: 'hostel',
    description: 'Kreveti, sobe, rezervacije, gosti, zajednički prostori, plaćanje i recenzije.',
    icon: 'BedDouble',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'reservations', 'property', 'contacts', 'calendar', 'invoices', 'payments', 'expenses', 'reports', 'settings', 'reviews', 'maintenance'],
    featured: false,
    sortOrder: 107,
  },
  {
    name: 'Apartmani za iznajmljivanje',
    slug: 'apartment-rental',
    description: 'Apartmani, rezervacije, cijene po sezoni, gosti, plaćanje i recenzije.',
    icon: 'Building2',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'reservations', 'property', 'rentals', 'contacts', 'calendar', 'invoices', 'payments', 'coupons', 'reviews', 'website', 'social-media', 'reports', 'settings'],
    featured: true,
    sortOrder: 108,
  },
  {
    name: 'Kamp',
    slug: 'campsite',
    description: 'Rezervacije parcela, smene, klijenti, plaćanje, oprema i aktivnosti.',
    icon: 'Tent',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'reservations', 'contacts', 'calendar', 'invoices', 'payments', 'inventory', 'maintenance', 'website', 'reports', 'settings'],
    featured: false,
    sortOrder: 52,
  },
  {
    name: 'Turistička agencija',
    slug: 'travel-agency',
    description: 'Paketi tura, rezervacije, klijenti, partneri, plaćanje i marketing.',
    icon: 'Plane',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'contacts', 'crm', 'calendar', 'reservations', 'invoices', 'payments', 'ecommerce', 'website', 'email-marketing', 'social-media', 'reports', 'settings', 'offers'],
    featured: true,
    sortOrder: 109,
  },
  {
    name: 'Vođenje tura',
    slug: 'guided-tours',
    description: 'Ture, vodiči, rezervacije, kalendar, plaćanje i marketing.',
    icon: 'MapPin',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'contacts', 'calendar', 'events', 'reservations', 'invoices', 'payments', 'crm', 'website', 'email-marketing', 'social-media', 'reports', 'settings', 'ecommerce'],
    featured: false,
    sortOrder: 55,
  },
  {
    name: 'Gostinski dom',
    slug: 'guest-house',
    description: 'Sobe, rezervacije, gosti, plaćanje, čišćenje i osnovna hrana.',
    icon: 'Home',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'reservations', 'property', 'contacts', 'calendar', 'invoices', 'payments', 'expenses', 'reports', 'settings', 'reviews'],
    featured: false,
    sortOrder: 54,
  },
  {
    name: 'Planinski vikendica',
    slug: 'holiday-house',
    description: 'Rezervacije, gosti, cene po sezoni, plaćanje, recenzije i marketing.',
    icon: 'Cabin',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'reservations', 'property', 'calendar', 'contacts', 'invoices', 'payments', 'coupons', 'reviews', 'website', 'social-media', 'reports', 'settings'],
    featured: false,
    sortOrder: 56,
  },
  {
    name: 'Spa resort',
    slug: 'spa-resort',
    description: 'Tretmani, rezervacije, članstvo, restoran, sobe i kompletna ponuda.',
    icon: 'Waves',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'reservations', 'appointments', 'scheduler', 'calendar', 'contacts', 'invoices', 'payments', 'subscriptions', 'restaurant', 'menu', 'pos', 'property', 'reviews', 'loyalty', 'coupons', 'website', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 60,
  },
  {
    name: 'Food truck',
    slug: 'food-trucks',
    description: 'Mobilna prodaja, lokacije, meni, inventar, dnevni izveštaji i isporuka.',
    icon: 'Truck',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'restaurant', 'menu', 'orders', 'kitchen', 'pos', 'inventory', 'fleet', 'expenses', 'reports', 'settings', 'social-media'],
    featured: false,
    sortOrder: 39,
  },
  {
    name: 'Takeaway restoran',
    slug: 'takeaway-restaurant',
    description: 'Naručivanje hrane, meni, isporuka, online prodaja i plaćanje.',
    icon: 'ShoppingBag',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'restaurant', 'menu', 'orders', 'kitchen', 'pos', 'ecommerce', 'delivery', 'inventory', 'expenses', 'coupons', 'reports', 'settings', 'social-media'],
    featured: false,
    sortOrder: 41,
  },
  {
    name: 'Pekara',
    slug: 'bakery',
    description: 'Proizvodnja i prodaja pekarskih proizvoda, sirovine, recepti, isporuke i POS.',
    icon: 'Croissant',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'inventory', 'invoices', 'pos', 'manufacturing', 'kitchen', 'procurement', 'contacts', 'expenses', 'reports', 'settings', 'coupons', 'offers', 'ecommerce'],
    featured: true,
    sortOrder: 32,
  },
  {
    name: 'Distributer pića',
    slug: 'beverages-distributor',
    description: 'Nabavka, skladište, isporuke, flota, fakturisanje i praćenje naloga.',
    icon: 'Wine',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'contacts', 'inventory', 'procurement', 'invoices', 'delivery', 'fleet', 'routes', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 34,
  },
  {
    name: 'Sladara / Prodavnica slatkiša',
    slug: 'candy-shop',
    description: 'Prodaja slatkiša, inventar, online prodaja, kupon sistem i lojalnost.',
    icon: 'Candy',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'seo', 'loyalty', 'coupons', 'social-media', 'website', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 36,
  },
  {
    name: 'Kuglana',
    slug: 'bowling-alleys',
    description: 'Rezervacije staza, kafić, POS, članstvo, događaji i zalihe.',
    icon: 'Circle',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'reservations', 'pos', 'calendar', 'contacts', 'invoices', 'inventory', 'coupons', 'events', 'reports', 'settings'],
    featured: false,
    sortOrder: 51,
  },
  {
    name: 'Escape room',
    slug: 'escape-rooms',
    description: 'Rezervacije soba, timovi, rang lista, plaćanje i marketing.',
    icon: 'Lock',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'reservations', 'calendar', 'contacts', 'invoices', 'pos', 'coupons', 'gamification', 'website', 'social-media', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 53,
  },
  {
    name: 'Outdoor aktivnosti',
    slug: 'outdoor-activities',
    description: 'Avanturističke aktivnosti, rezervacije, oprema, instruktori i bezbednost.',
    icon: 'Trees',
    category: 'Ugostiteljstvo i turizam',
    modules: ['dashboard', 'contacts', 'calendar', 'reservations', 'inventory', 'invoices', 'payments', 'safety', 'website', 'email-marketing', 'social-media', 'reports', 'settings'],
    featured: false,
    sortOrder: 59,
  },
]

// ============ TRGOVINA I MALOPRODAJA (17) ============
const retailCommerce: IndustryTemplateData[] = [
  {
    name: 'Supermarket',
    slug: 'grocery-store',
    description: 'Širok asortiman, POS, inventar, dobavljači, akcije, loyalty i isporuka.',
    icon: 'ShoppingCart',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'inventory', 'pos', 'invoices', 'procurement', 'contacts', 'expenses', 'coupons', 'loyalty', 'ecommerce', 'delivery', 'reports', 'settings', 'offers', 'returns', 'labels', 'barcode'],
    featured: false,
    sortOrder: 87,
  },
  {
    name: 'Prodavnica odeće',
    slug: 'clothing-store',
    description: 'Inventar, veličine, boje, e-commerce, POS, popusti i lojalnost.',
    icon: 'Shirt',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'seo', 'loyalty', 'coupons', 'reviews', 'social-media', 'website', 'reports', 'settings', 'offers', 'returns', 'labels'],
    featured: true,
    sortOrder: 82,
  },
  {
    name: 'Online trgovina (e-commerce)',
    slug: 'ecommerce-store',
    description: 'Online prodaja bez zaliha, dobavljači, marketplace integracija, naručivanje.',
    icon: 'Package',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'ecommerce', 'marketplace', 'shipping', 'orders', 'inventory', 'website', 'seo', 'email-marketing', 'social-media', 'reports', 'settings', 'coupons', 'reviews'],
    featured: true,
    sortOrder: 84,
  },
  {
    name: 'Elektronska prodavnica',
    slug: 'electronic-store',
    description: 'Elektronika, inventar, garancije, servis, e-commerce i recenzije.',
    icon: 'Monitor',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'service-center', 'warranty', 'reviews', 'seo', 'website', 'social-media', 'reports', 'settings', 'offers', 'returns', 'barcode', 'labels'],
    featured: false,
    sortOrder: 85,
  },
  {
    name: 'Auto delovi',
    slug: 'automobile-spare-parts',
    description: 'Inventar delova, katalog, nabavka, prodaja, e-commerce i servis.',
    icon: 'Car',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'procurement', 'service-center', 'ecommerce', 'website', 'seo', 'reports', 'settings', 'offers', 'barcode', 'labels'],
    featured: false,
    sortOrder: 80,
  },
  {
    name: 'Kozmetička prodavnica',
    slug: 'cosmetics-store',
    description: 'Kozmetika, inventar, online prodaja, savetovanje, popusti i marketing.',
    icon: 'Sparkles',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'seo', 'loyalty', 'coupons', 'reviews', 'social-media', 'website', 'email-marketing', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 83,
  },
  {
    name: 'Cvjećara',
    slug: 'florist',
    description: 'Cveće, porudžbine, dostava, sezonski proizvodi, marketing i online prodaja.',
    icon: 'Flower',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'delivery', 'calendar', 'coupons', 'social-media', 'website', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 86,
  },
  {
    name: 'Pekara / poslastičarnica',
    slug: 'bakery-sweets',
    description: 'Proizvodnja i prodaja pekarskih proizvoda, sirovine, recepti, isporuke i POS.',
    icon: 'Croissant',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'inventory', 'invoices', 'pos', 'manufacturing', 'kitchen', 'procurement', 'contacts', 'expenses', 'reports', 'settings', 'coupons', 'offers', 'ecommerce'],
    featured: false,
    sortOrder: 110,
  },
  {
    name: 'Prodaja namještaja',
    slug: 'furniture-store',
    description: 'Nameštaj, inventar, dostava, montaža, online prodaja i katalog.',
    icon: 'Sofa',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'delivery', 'seo', 'reviews', 'website', 'social-media', 'reports', 'settings', 'offers', 'coupons'],
    featured: false,
    sortOrder: 88,
  },
  {
    name: 'Prodaja elektronike',
    slug: 'electronics-retail',
    description: 'Elektronika, inventar, garancije, servis, e-commerce i recenzije.',
    icon: 'Laptop',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'service-center', 'warranty', 'reviews', 'seo', 'website', 'social-media', 'reports', 'settings', 'offers', 'returns', 'barcode', 'labels'],
    featured: false,
    sortOrder: 111,
  },
  {
    name: 'Prodaja alata i strojeva',
    slug: 'hardware-store',
    description: 'Građevinski materijal, alati, inventar, nabavka, prodaja i isporuka.',
    icon: 'Wrench',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'procurement', 'offers', 'ecommerce', 'website', 'delivery', 'reports', 'settings', 'expenses'],
    featured: false,
    sortOrder: 89,
  },
  {
    name: 'Bencinska postaja',
    slug: 'gas-station',
    description: 'Nabavka, prodaja i praćenje zaliha fosilnih goriva, flota vozila i isporuke.',
    icon: 'Fuel',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'invoices', 'inventory', 'fleet', 'delivery', 'routes', 'finance', 'expenses', 'reports', 'settings', 'procurement', 'offers'],
    featured: false,
    sortOrder: 4,
  },
  {
    name: 'Knjižara',
    slug: 'bookstore',
    description: 'Knjige, inventar, ISBN, online prodaja, izdavanje, loyalty i događaji.',
    icon: 'BookOpen',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'library', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'website', 'loyalty', 'coupons', 'events', 'social-media', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 81,
  },
  {
    name: 'Poljoprivredna apoteka',
    slug: 'agricultural-store',
    description: 'Prodaja poljoprivredne opreme, inventar, dobavljači, nabavka i online prodaja.',
    icon: 'Sprout',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'procurement', 'offers', 'ecommerce', 'website', 'reports', 'settings', 'expenses'],
    featured: false,
    sortOrder: 79,
  },
  {
    name: 'Igračkara',
    slug: 'toy-store',
    description: 'Igračke, inventar, online prodaja, popusti, sezonske akcije i marketing.',
    icon: 'Puzzle',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'seo', 'coupons', 'loyalty', 'reviews', 'social-media', 'website', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 90,
  },
  {
    name: 'Vinoteka',
    slug: 'wine-shop',
    description: 'Vina, degustacije, inventar, online prodaja, događaji i loyalty.',
    icon: 'Wine',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'events', 'loyalty', 'coupons', 'reviews', 'social-media', 'website', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 91,
  },
  {
    name: 'Radnja za umetnost i zanat',
    slug: 'arts-crafts-store',
    description: 'Prodaja umetničkih i zanatskih proizvoda, inventar, online prodaja i kupon sistem.',
    icon: 'Palette',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'seo', 'website', 'reviews', 'coupons', 'social-media', 'finance', 'reports', 'settings', 'offers', 'expenses'],
    featured: false,
    sortOrder: 11,
  },
  {
    name: 'Auto kuća',
    slug: 'car-dealership',
    description: 'Prodaja novih i polovnih automobila, probne vožnje, finansiranje, servis i garancije.',
    icon: 'CarFront',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'crm', 'inventory', 'invoices', 'offers', 'contracts', 'payments', 'website', 'social-media', 'email-marketing', 'reports', 'settings', 'service-center', 'warranty'],
    featured: true,
    sortOrder: 112,
  },
  {
    name: 'Drogerija / parfumerija',
    slug: 'drugstore-perfumery',
    description: 'Ljekovita kozmetika, parfemi, inventar, online prodaja, promocije i loyalty program.',
    icon: 'Droplet',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'seo', 'loyalty', 'coupons', 'reviews', 'social-media', 'website', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 113,
  },
  {
    name: 'Mesnica',
    slug: 'butcher-shop',
    description: 'Prodaja mesa i mesnih prerađevina, nabavka, inventar, cijene i higijenski standardi.',
    icon: 'Beef',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'procurement', 'expenses', 'quality', 'standards', 'reports', 'settings'],
    featured: false,
    sortOrder: 114,
  },
  {
    name: 'Ribarnica',
    slug: 'fish-market',
    description: 'Prodaja svježeg i smrznutog ribljeg asortimana, nabavka, inventar i kvalitet.',
    icon: 'Fish',
    category: 'Trgovina i maloprodaja',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'procurement', 'expenses', 'quality', 'standards', 'reports', 'settings'],
    featured: false,
    sortOrder: 115,
  },
]

// ============ ZDRAVSTVO I FARMACIJA (11) ============
const healthcare: IndustryTemplateData[] = [
  {
    name: 'Apoteka',
    slug: 'pharmacy',
    description: 'Lekovi, inventar, rokovi trajanja, recepti, klijenti i prodaja.',
    icon: 'Pill',
    category: 'Zdravstvo i farmacija',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'procurement', 'reports', 'settings', 'patients', 'prescriptions', 'offers'],
    featured: true,
    sortOrder: 47,
  },
  {
    name: 'Optika',
    slug: 'eyewear-store',
    description: 'Proizvodi, klijenti, pregledi, narudžbenice, inventar i online prodaja.',
    icon: 'Glasses',
    category: 'Zdravstvo i farmacija',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'pos', 'ecommerce', 'appointments', 'offers', 'reviews', 'seo', 'social-media', 'reports', 'settings'],
    featured: false,
    sortOrder: 43,
  },
  {
    name: 'Veterinarska stanica',
    slug: 'veterinary-clinic',
    description: 'Pacijenti (ljubimci), vlasnici, zakazivanje, tretmani, inventar i fakturisanje.',
    icon: 'Syringe',
    category: 'Zdravstvo i farmacija',
    modules: ['dashboard', 'contacts', 'appointments', 'calendar', 'inventory', 'invoices', 'pos', 'prescriptions', 'documents', 'website', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 48,
  },
  {
    name: 'Ordinacija opće medicine',
    slug: 'general-practice',
    description: 'Pacijenti, kartoni, zakazivanje, pregledi, recepti, nalazi i naplata.',
    icon: 'Stethoscope',
    category: 'Zdravstvo i farmacija',
    modules: ['dashboard', 'contacts', 'patients', 'appointments', 'scheduler', 'calendar', 'medical-records', 'prescriptions', 'invoices', 'payments', 'documents', 'reports', 'settings'],
    featured: true,
    sortOrder: 116,
  },
  {
    name: 'Stomatološka ordinacija',
    slug: 'dental-clinic',
    description: 'Pacijenti, zakazivanje, tretmani, nalazi, rendgen, inventar i fakturisanje.',
    icon: 'Smile',
    category: 'Zdravstvo i farmacija',
    modules: ['dashboard', 'contacts', 'patients', 'appointments', 'scheduler', 'calendar', 'medical-records', 'inventory', 'invoices', 'payments', 'documents', 'reports', 'settings', 'prescriptions'],
    featured: false,
    sortOrder: 117,
  },
  {
    name: 'Fizioterapija i rehabilitacija',
    slug: 'physiotherapy',
    description: 'Pacijenti, zakazivanje, terapije, napredovanje, dokumentacija i naplata.',
    icon: 'Activity',
    category: 'Zdravstvo i farmacija',
    modules: ['dashboard', 'contacts', 'patients', 'appointments', 'scheduler', 'calendar', 'invoices', 'payments', 'documents', 'reports', 'settings', 'subscriptions'],
    featured: false,
    sortOrder: 118,
  },
  {
    name: 'Laboratorij',
    slug: 'laboratory',
    description: 'Uzorci, analize, rezultati, pacijenti, inventar opreme i izveštaji.',
    icon: 'Microscope',
    category: 'Zdravstvo i farmacija',
    modules: ['dashboard', 'contacts', 'patients', 'lab', 'appointments', 'calendar', 'inventory', 'invoices', 'payments', 'documents', 'reports', 'settings', 'quality', 'standards'],
    featured: false,
    sortOrder: 119,
  },
  {
    name: 'Poliklinika',
    slug: 'polyclinic',
    description: 'Više specijalističkih ordinacija, pacijenti, zakazivanje, nalazi i billing.',
    icon: 'Hospital',
    category: 'Zdravstvo i farmacija',
    modules: ['dashboard', 'contacts', 'patients', 'appointments', 'scheduler', 'calendar', 'medical-records', 'prescriptions', 'lab', 'inventory', 'invoices', 'payments', 'employees', 'documents', 'reports', 'settings'],
    featured: false,
    sortOrder: 120,
  },
  {
    name: 'Dom zdravlja',
    slug: 'health-center',
    description: 'Primarna zdravstvena zaštita, pacijenti, ekipa, kartoni, preventivni pregledi.',
    icon: 'HeartPulse',
    category: 'Zdravstvo i farmacija',
    modules: ['dashboard', 'contacts', 'patients', 'appointments', 'scheduler', 'calendar', 'medical-records', 'prescriptions', 'employees', 'inventory', 'invoices', 'reports', 'settings', 'documents'],
    featured: false,
    sortOrder: 121,
  },
  {
    name: 'Bolnica',
    slug: 'hospital',
    description: 'Odjeli, kreveti, pacijenti, osoblje, raspored, inventar i kompletna dokumentacija.',
    icon: 'Building',
    category: 'Zdravstvo i farmacija',
    modules: ['dashboard', 'contacts', 'patients', 'appointments', 'scheduler', 'calendar', 'medical-records', 'prescriptions', 'lab', 'inventory', 'employees', 'invoices', 'reports', 'settings', 'documents', 'maintenance', 'assets'],
    featured: false,
    sortOrder: 122,
  },
  {
    name: 'Ortopedska pomagala',
    slug: 'orthopedic-supplies',
    description: 'Ortopedska pomagala, proteze, inventar, klijenti, narudžbenice i naplata.',
    icon: 'Accessibility',
    category: 'Zdravstvo i farmacija',
    modules: ['dashboard', 'contacts', 'patients', 'inventory', 'invoices', 'pos', 'appointments', 'offers', 'ecommerce', 'reports', 'settings', 'prescriptions'],
    featured: false,
    sortOrder: 123,
  },
]

// ============ OBRAZOVANJE (12) ============
const education: IndustryTemplateData[] = [
  {
    name: 'Tečajevi (programiranje, dizajn...)',
    slug: 'diy-workshops',
    description: 'Organizacija radionica, upis polaznika, raspored, plaćanje i sertifikati.',
    icon: 'Hammer',
    category: 'Obrazovanje',
    modules: ['dashboard', 'education', 'calendar', 'contacts', 'invoices', 'payments', 'enrollment', 'tuition', 'homework', 'website', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 19,
  },
  {
    name: 'Online tečajevi (e-learning)',
    slug: 'elearning-platform',
    description: 'Online kursevi, lekcije, testovi, polaznici, certifikati i naplata.',
    icon: 'GraduationCap',
    category: 'Obrazovanje',
    modules: ['dashboard', 'education', 'homework', 'enrollment', 'tuition', 'calendar', 'contacts', 'website', 'blog', 'ecommerce', 'payments', 'subscriptions', 'email-marketing', 'surveys', 'reports', 'settings'],
    featured: true,
    sortOrder: 21,
  },
  {
    name: 'Autoskola',
    slug: 'driving-school',
    description: 'Učenici, instruktori, vožnje, raspored, plaćanje i polaganje ispita.',
    icon: 'Car',
    category: 'Obrazovanje',
    modules: ['dashboard', 'education', 'calendar', 'contacts', 'fleet', 'scheduler', 'enrollment', 'tuition', 'invoices', 'payments', 'reports', 'settings'],
    featured: false,
    sortOrder: 20,
  },
  {
    name: 'Studentska organizacija',
    slug: 'student-organization',
    description: 'Članstvo, događaji, projekti, komunikacija, dokumenti i finansije.',
    icon: 'Users',
    category: 'Obrazovanje',
    modules: ['dashboard', 'contacts', 'events', 'projects', 'calendar', 'chat', 'forum', 'documents', 'surveys', 'website', 'blog', 'finance', 'reports', 'settings'],
    featured: false,
    sortOrder: 22,
  },
  {
    name: 'Osnovna škola',
    slug: 'primary-school',
    description: 'Učenici, nastavnici, raspored, ocjene, prisustvo, roditelji i izvještaji.',
    icon: 'School',
    category: 'Obrazovanje',
    modules: ['dashboard', 'education', 'contacts', 'calendar', 'timetable', 'classroom', 'enrollment', 'homework', 'employees', 'documents', 'reports', 'settings', 'website'],
    featured: true,
    sortOrder: 124,
  },
  {
    name: 'Srednja škola',
    slug: 'high-school',
    description: 'Učenici, nastavnici, raspored, ocjene, prisustvo, ispiti i izvještaji.',
    icon: 'School',
    category: 'Obrazovanje',
    modules: ['dashboard', 'education', 'contacts', 'calendar', 'timetable', 'classroom', 'enrollment', 'homework', 'employees', 'documents', 'reports', 'settings', 'website'],
    featured: false,
    sortOrder: 125,
  },
  {
    name: 'Fakultet / sveučilište',
    slug: 'university',
    description: 'Studenti, profesori, predmeti, ispiti, enrolled, ocjene i akademski izvještaji.',
    icon: 'GraduationCap',
    category: 'Obrazovanje',
    modules: ['dashboard', 'education', 'contacts', 'calendar', 'timetable', 'classroom', 'enrollment', 'homework', 'employees', 'library', 'documents', 'reports', 'settings', 'website', 'tuition', 'payments'],
    featured: false,
    sortOrder: 126,
  },
  {
    name: 'Jezična škola',
    slug: 'language-school',
    description: 'Kursevi stranih jezika, polaznici, nastavnici, raspored, testovi i certifikati.',
    icon: 'Languages',
    category: 'Obrazovanje',
    modules: ['dashboard', 'education', 'calendar', 'contacts', 'enrollment', 'tuition', 'homework', 'invoices', 'payments', 'website', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 127,
  },
  {
    name: 'Glazbena škola',
    slug: 'music-school',
    description: 'Učenici, profesori, instrumenti, raspored časova, prijemi i nastupi.',
    icon: 'Music',
    category: 'Obrazovanje',
    modules: ['dashboard', 'education', 'calendar', 'contacts', 'enrollment', 'tuition', 'invoices', 'payments', 'inventory', 'reports', 'settings', 'website', 'events'],
    featured: false,
    sortOrder: 128,
  },
  {
    name: 'Škola stranih jezika',
    slug: 'foreign-language-school',
    description: 'Intenzivni kursevi, individualni i grupni časovi, testiranje razine i certifikacija.',
    icon: 'BookOpen',
    category: 'Obrazovanje',
    modules: ['dashboard', 'education', 'calendar', 'contacts', 'enrollment', 'tuition', 'homework', 'invoices', 'payments', 'website', 'email-marketing', 'surveys', 'reports', 'settings'],
    featured: false,
    sortOrder: 129,
  },
  {
    name: 'Dječji vrtić',
    slug: 'kindergarten',
    description: 'Djeca, roditelji, odgojitelji, raspored, aktivnosti, prehrana i plaćanje.',
    icon: 'Baby',
    category: 'Obrazovanje',
    modules: ['dashboard', 'education', 'contacts', 'calendar', 'enrollment', 'invoices', 'payments', 'documents', 'employees', 'reports', 'settings', 'website', 'events'],
    featured: false,
    sortOrder: 130,
  },
  {
    name: 'Studentski dom',
    slug: 'student-dormitory',
    description: 'Sobe, studenti, prijave, kalendar, plaćanje, oprema i komunikacija.',
    icon: 'Home',
    category: 'Obrazovanje',
    modules: ['dashboard', 'property', 'reservations', 'contacts', 'calendar', 'invoices', 'payments', 'maintenance', 'reports', 'settings', 'contracts'],
    featured: false,
    sortOrder: 131,
  },
]

// ============ GRAĐEVINA I NEKRETNINE (14) ============
const constructionRealEstate: IndustryTemplateData[] = [
  {
    name: 'Građevinska firma',
    slug: 'construction-builder',
    description: 'Gradilišta, radnici, podizvođači, alati, bezbednost i naplata.',
    icon: 'HardHat',
    category: 'Građevina i nekretnine',
    modules: ['dashboard', 'construction-site', 'employees', 'blueprints', 'subcontractors', 'safety', 'fleet', 'inventory', 'maintenance', 'invoices', 'expenses', 'projects', 'calendar', 'reports', 'settings', 'documents'],
    featured: true,
    sortOrder: 72,
  },
  {
    name: 'Arhitektonski biro',
    slug: 'architecture-firm',
    description: 'Projekti, nacrti, klijenti, stages, dokumentacija i fakturisanje.',
    icon: 'Compass',
    category: 'Građevina i nekretnine',
    modules: ['dashboard', 'projects', 'contacts', 'blueprints', 'documents', 'calendar', 'invoices', 'offers', 'time-billing', 'reports', 'settings'],
    featured: false,
    sortOrder: 70,
  },
  {
    name: 'Geodetska firma',
    slug: 'surveying-mapping',
    description: 'Geodetski izmera, projekti, oprema, klijenti, izveštaji i dokumentacija.',
    icon: 'Map',
    category: 'Građevina i nekretnine',
    modules: ['dashboard', 'contacts', 'projects', 'measurements', 'documents', 'calendar', 'invoices', 'offers', 'reports', 'settings', 'blueprints'],
    featured: false,
    sortOrder: 99,
  },
  {
    name: 'Agencija za nekretnine',
    slug: 'real-estate-agency',
    description: 'Nekretnine, pregledi, klijenti, kupoprodaja, zakup i marketing.',
    icon: 'Home',
    category: 'Građevina i nekretnine',
    modules: ['dashboard', 'property', 'property-viewings', 'contacts', 'crm', 'calendar', 'website', 'blog', 'social-media', 'email-marketing', 'reports', 'settings'],
    featured: true,
    sortOrder: 77,
  },
  {
    name: 'Upravljanje nekretninama',
    slug: 'property-management',
    description: 'Nekretnine, zakupci, ugovori, održavanje, računi i izveštaji.',
    icon: 'Building2',
    category: 'Građevina i nekretnine',
    modules: ['dashboard', 'property', 'rentals', 'property-viewings', 'contacts', 'contracts', 'maintenance', 'work-orders', 'utilities', 'invoices', 'payments', 'calendar', 'documents', 'reports', 'settings'],
    featured: true,
    sortOrder: 75,
  },
  {
    name: 'Investitor / developer',
    slug: 'construction-developer',
    description: 'Projekti, gradilišta, investitori, prodaja, finansije i praćenje napretka.',
    icon: 'Crane',
    category: 'Građevina i nekretnine',
    modules: ['dashboard', 'construction-site', 'projects', 'property', 'contacts', 'crm', 'blueprints', 'invoices', 'offers', 'finance', 'reports', 'calendar', 'documents', 'settings'],
    featured: false,
    sortOrder: 73,
  },
  {
    name: 'HVAC servisi',
    slug: 'hvac-services',
    description: 'Servis klima i grejanja, zakazivanje, inventar delova, klijenti i fakturisanje.',
    icon: 'Thermometer',
    category: 'Građevina i nekretnine',
    modules: ['dashboard', 'contacts', 'appointments', 'field-service', 'work-orders', 'inventory', 'invoices', 'expenses', 'calendar', 'reports', 'settings', 'contracts'],
    featured: false,
    sortOrder: 74,
  },
  {
    name: 'Solarni sistemi',
    slug: 'solar-energy-systems',
    description: 'Projektovanje, instalacija, održavanje, klijenti i subvencije.',
    icon: 'Sun',
    category: 'Građevina i nekretnine',
    modules: ['dashboard', 'contacts', 'projects', 'appointments', 'field-service', 'work-orders', 'inventory', 'invoices', 'offers', 'contracts', 'maintenance', 'reports', 'calendar', 'settings', 'documents'],
    featured: false,
    sortOrder: 78,
  },
  {
    name: 'Zajednica vlasnika stanova',
    slug: 'property-owner-association',
    description: 'Stanari, računi, održavanje, zadaće, dokumenti i godišnji plan.',
    icon: 'Building',
    category: 'Građevina i nekretnine',
    modules: ['dashboard', 'contacts', 'property', 'work-orders', 'maintenance', 'utilities', 'invoices', 'payments', 'documents', 'calendar', 'reports', 'settings', 'contracts', 'complaints'],
    featured: false,
    sortOrder: 71,
  },
  {
    name: 'Izdavanje mašina i alata',
    slug: 'machine-tools-rental',
    description: 'Inventar opreme, iznajmljivanje, klijenti, rezervacije, održavanje.',
    icon: 'Wrench',
    category: 'Građevina i nekretnine',
    modules: ['dashboard', 'inventory', 'contacts', 'rentals', 'calendar', 'invoices', 'contracts', 'maintenance', 'assets', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 76,
  },
  {
    name: 'Nadzor gradilišta',
    slug: 'construction-supervision',
    description: 'Kontrola kvaliteta, napredak gradnje, dokumentacija, bezbednost i izveštaji.',
    icon: 'ClipboardCheck',
    category: 'Građevina i nekretnine',
    modules: ['dashboard', 'construction-site', 'blueprints', 'safety', 'subcontractors', 'documents', 'calendar', 'reports', 'settings', 'quality', 'standards', 'projects'],
    featured: false,
    sortOrder: 132,
  },
  {
    name: 'Instalaterska firma',
    slug: 'plumbing-electrical-firm',
    description: 'Instalacije vodovoda, struje, plina, zakazivanje, inventar, klijenti i naplata.',
    icon: 'Wrench',
    category: 'Građevina i nekretnine',
    modules: ['dashboard', 'contacts', 'appointments', 'field-service', 'work-orders', 'inventory', 'invoices', 'expenses', 'calendar', 'reports', 'settings', 'contracts', 'maintenance'],
    featured: false,
    sortOrder: 133,
  },
  {
    name: 'Keramičarska / parketarska firma',
    slug: 'tiling-flooring',
    description: 'Postavljanje keramike, parketa, laminata, zakazivanje, klijenti, materijal.',
    icon: 'Square',
    category: 'Građevina i nekretnine',
    modules: ['dashboard', 'contacts', 'projects', 'calendar', 'inventory', 'invoices', 'offers', 'expenses', 'documents', 'reports', 'settings', 'contracts'],
    featured: false,
    sortOrder: 134,
  },
  {
    name: 'Procjena nekretnina',
    slug: 'property-valuation',
    description: 'Procjena vrijednosti nekretnina, izvještaji, klijenti, dokumentacija i naplata.',
    icon: 'Target',
    category: 'Građevina i nekretnine',
    modules: ['dashboard', 'contacts', 'property', 'valuation', 'documents', 'calendar', 'invoices', 'reports', 'settings', 'offers', 'blueprints'],
    featured: false,
    sortOrder: 135,
  },
]

// ============ LOGISTIKA I TRANSPORT (10) ============
const logisticsTransport: IndustryTemplateData[] = [
  {
    name: 'Skladište / logistički centar',
    slug: 'third-party-logistics',
    description: 'Skladište, prijem, otprema, isporuke, flota i praćenje pošiljki.',
    icon: 'Warehouse',
    category: 'Logistika i transport',
    modules: ['dashboard', 'inventory', 'shipping', 'delivery', 'fleet', 'loading-dock', 'contacts', 'invoices', 'reports', 'settings', 'routes', 'packaging', 'barcode'],
    featured: true,
    sortOrder: 61,
  },
  {
    name: 'Distribucija hrane',
    slug: 'food-distribution',
    description: 'Nabavka, skladištenje, distribucija, flota, ekipe i praćenje naloga.',
    icon: 'Truck',
    category: 'Logistika i transport',
    modules: ['dashboard', 'inventory', 'procurement', 'shipping', 'delivery', 'fleet', 'routes', 'contacts', 'invoices', 'expenses', 'reports', 'settings'],
    featured: false,
    sortOrder: 65,
  },
  {
    name: 'Prijevoznička firma',
    slug: 'trucking-company',
    description: 'Kamionski prijevoz robe, flota, rute, teretni listovi, troškovi i fakturisanje.',
    icon: 'TruckIcon',
    category: 'Logistika i transport',
    modules: ['dashboard', 'contacts', 'fleet', 'trucks', 'routes', 'shipping', 'delivery', 'loading-dock', 'invoices', 'expenses', 'fuel', 'reports', 'settings', 'documents'],
    featured: true,
    sortOrder: 136,
  },
  {
    name: 'Kurirska služba',
    slug: 'courier-service',
    description: 'Brza dostava paketa, praćenje pošiljki, kuriri, zone i fakturisanje.',
    icon: 'Package',
    category: 'Logistika i transport',
    modules: ['dashboard', 'contacts', 'shipping', 'delivery', 'fleet', 'routes', 'inventory', 'invoices', 'expenses', 'reports', 'settings', 'barcode', 'packaging'],
    featured: false,
    sortOrder: 137,
  },
  {
    name: 'Špedicija (rastresiti teret)',
    slug: 'freight-forwarding',
    description: 'Organizacija teretnog transporta, carina, dokumentacija, partneri i praćenje.',
    icon: 'Container',
    category: 'Logistika i transport',
    modules: ['dashboard', 'contacts', 'shipping', 'customs-docs', 'inventory', 'invoices', 'documents', 'calendar', 'reports', 'settings', 'fleet', 'routes'],
    featured: false,
    sortOrder: 138,
  },
  {
    name: 'Carinsko posredovanje',
    slug: 'customs-brokerage',
    description: 'Carinska dokumentacija, uvoz/izvoz, deklaracije, klijenti i takse.',
    icon: 'Stamp',
    category: 'Logistika i transport',
    modules: ['dashboard', 'contacts', 'customs-docs', 'documents', 'invoices', 'calendar', 'reports', 'settings', 'contracts'],
    featured: false,
    sortOrder: 139,
  },
  {
    name: 'Parkirališna kuća',
    slug: 'parking-garage',
    description: 'Parkirna mjesta, zone, cijene, pretplate, ulazi/izlazi i izvještaji.',
    icon: 'ParkingCircle',
    category: 'Logistika i transport',
    modules: ['dashboard', 'contacts', 'subscriptions', 'invoices', 'payments', 'reports', 'settings', 'inventory'],
    featured: false,
    sortOrder: 140,
  },
  {
    name: 'Autobuski prijevoz',
    slug: 'bus-transport',
    description: 'Linije, raspored, vozila, putne karte, putnici i održavanje.',
    icon: 'Bus',
    category: 'Logistika i transport',
    modules: ['dashboard', 'contacts', 'fleet', 'routes', 'reservations', 'invoices', 'payments', 'maintenance', 'employees', 'calendar', 'reports', 'settings'],
    featured: false,
    sortOrder: 141,
  },
  {
    name: 'Taksi služba',
    slug: 'taxi-service',
    description: 'Vozači, narudžbe, pozivi, praćenje, naplate, flota i izvještaji.',
    icon: 'CarFront',
    category: 'Logistika i transport',
    modules: ['dashboard', 'contacts', 'fleet', 'routes', 'invoices', 'payments', 'expenses', 'reports', 'settings', 'geolocation'],
    featured: false,
    sortOrder: 142,
  },
  {
    name: 'Iznajmljivanje vozila (rent-a-car)',
    slug: 'rent-a-car',
    description: 'Flota vozila, rezervacije, ugovori, osiguranje, naplate i održavanje.',
    icon: 'CarFront',
    category: 'Logistika i transport',
    modules: ['dashboard', 'contacts', 'fleet', 'rent-a-car', 'rentals', 'reservations', 'calendar', 'invoices', 'payments', 'contracts', 'maintenance', 'reports', 'settings'],
    featured: true,
    sortOrder: 143,
  },
]

// ============ PROIZVODNJA I INDUSTRIJA (14) ============
const manufacturingIndustry: IndustryTemplateData[] = [
  {
    name: 'Proizvodnja namještaja',
    slug: 'custom-furniture-production',
    description: 'Narudžbenice, proizvodnja, sirovine, projekti, isporuka i fakturisanje.',
    icon: 'Armchair',
    category: 'Proizvodnja i industrija',
    modules: ['dashboard', 'manufacturing', 'projects', 'inventory', 'contacts', 'invoices', 'offers', 'blueprints', 'delivery', 'reports', 'settings', 'procurement', 'quality'],
    featured: false,
    sortOrder: 64,
  },
  {
    name: 'Stolar',
    slug: 'carpenter',
    description: 'Proizvodnja nameštaja, sirovine, narudžbenice, inventar i isporuke.',
    icon: 'Hammer',
    category: 'Proizvodnja i industrija',
    modules: ['dashboard', 'manufacturing', 'inventory', 'contacts', 'invoices', 'offers', 'projects', 'delivery', 'reports', 'settings', 'procurement'],
    featured: false,
    sortOrder: 62,
  },
  {
    name: 'Proizvodnja tekstila',
    slug: 'textile-manufacturing',
    description: 'Proizvodnja, sirovine, kvalitet, inventar, narudžbenice i isporuke.',
    icon: 'Scissors',
    category: 'Proizvodnja i industrija',
    modules: ['dashboard', 'manufacturing', 'quality', 'inventory', 'contacts', 'invoices', 'offers', 'projects', 'delivery', 'labels', 'standards', 'reports', 'settings', 'procurement'],
    featured: false,
    sortOrder: 68,
  },
  {
    name: 'Metaloprerađivačka industrija',
    slug: 'metal-fabricator',
    description: 'Proizvodnja, kvalitet, nacrta, inventar sirovina, narudžbenice i isporuke.',
    icon: 'Cog',
    category: 'Proizvodnja i industrija',
    modules: ['dashboard', 'manufacturing', 'quality', 'blueprints', 'inventory', 'contacts', 'invoices', 'offers', 'projects', 'delivery', 'maintenance', 'standards', 'reports', 'settings', 'procurement'],
    featured: false,
    sortOrder: 66,
  },
  {
    name: 'Mikro pivara',
    slug: 'microbrewery',
    description: 'Proizvodnja piva, sirovine, recepti, distribucija, prodaja i marketing.',
    icon: 'Beer',
    category: 'Proizvodnja i industrija',
    modules: ['dashboard', 'manufacturing', 'inventory', 'procurement', 'contacts', 'invoices', 'pos', 'delivery', 'routes', 'website', 'social-media', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 67,
  },
  {
    name: 'Vinograd',
    slug: 'vineyard',
    description: 'Vinogradarstvo, berba, proizvodnja vina, čuvanje, distribucija i degustacije.',
    icon: 'Grape',
    category: 'Proizvodnja i industrija',
    modules: ['dashboard', 'manufacturing', 'inventory', 'contacts', 'invoices', 'pos', 'ecommerce', 'delivery', 'website', 'social-media', 'email-marketing', 'reports', 'settings', 'coupons', 'offers'],
    featured: false,
    sortOrder: 69,
  },
  {
    name: 'Korporativni pokloni',
    slug: 'corporate-gifts',
    description: 'B2B prodaja poklona, katalog, narudžbine, graviranje i isporuka.',
    icon: 'Gift',
    category: 'Proizvodnja i industrija',
    modules: ['dashboard', 'contacts', 'crm', 'inventory', 'invoices', 'offers', 'ecommerce', 'delivery', 'website', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 63,
  },
  {
    name: 'Proizvodnja hrane i pića',
    slug: 'food-beverage-production',
    description: 'Proizvodnja, sirovine, recepti, kontrola kvaliteta, inventar i distribucija.',
    icon: 'Factory',
    category: 'Proizvodnja i industrija',
    modules: ['dashboard', 'manufacturing', 'inventory', 'procurement', 'quality', 'standards', 'contacts', 'invoices', 'delivery', 'reports', 'settings', 'labels', 'packaging'],
    featured: true,
    sortOrder: 144,
  },
  {
    name: 'Proizvodnja plastike',
    slug: 'plastic-manufacturing',
    description: 'Proizvodnja plastike, kalupi, sirovine, kvalitet, inventar i isporuke.',
    icon: 'Box',
    category: 'Proizvodnja i industrija',
    modules: ['dashboard', 'manufacturing', 'quality', 'inventory', 'contacts', 'invoices', 'offers', 'projects', 'delivery', 'maintenance', 'standards', 'reports', 'settings', 'procurement'],
    featured: false,
    sortOrder: 145,
  },
  {
    name: 'Strojarska radionica',
    slug: 'machine-workshop',
    description: 'Obrada metala, CNC mašine, nacrta, inventar, narudžbenice i isporuke.',
    icon: 'Cog',
    category: 'Proizvodnja i industrija',
    modules: ['dashboard', 'manufacturing', 'quality', 'blueprints', 'inventory', 'contacts', 'invoices', 'offers', 'projects', 'delivery', 'maintenance', 'reports', 'settings', 'procurement'],
    featured: false,
    sortOrder: 146,
  },
  {
    name: 'Brodogradilište',
    slug: 'shipyard',
    description: 'Gradnja i popravka brodova, projekti, nacrti, inventar, radnici i sertifikati.',
    icon: 'Ship',
    category: 'Proizvodnja i industrija',
    modules: ['dashboard', 'manufacturing', 'projects', 'blueprints', 'inventory', 'contacts', 'employees', 'subcontractors', 'safety', 'invoices', 'expenses', 'reports', 'settings', 'documents', 'maintenance', 'quality'],
    featured: false,
    sortOrder: 147,
  },
  {
    name: 'Tiskara / grafička priprema',
    slug: 'printing-press',
    description: 'Tiskarske narudžbine, grafička priprema, inventar papira, isporuka i naplata.',
    icon: 'Printer',
    category: 'Proizvodnja i industrija',
    modules: ['dashboard', 'manufacturing', 'inventory', 'contacts', 'invoices', 'offers', 'projects', 'delivery', 'reports', 'settings', 'procurement', 'quality', 'labels'],
    featured: false,
    sortOrder: 148,
  },
  {
    name: 'IT proizvodnja (hardver)',
    slug: 'it-hardware-manufacturing',
    description: 'Proizvodnja IT opreme, komponente, kontrola kvaliteta, inventar i distribucija.',
    icon: 'CircuitBoard',
    category: 'Proizvodnja i industrija',
    modules: ['dashboard', 'manufacturing', 'quality', 'inventory', 'contacts', 'invoices', 'offers', 'delivery', 'reports', 'settings', 'procurement', 'standards', 'assets'],
    featured: false,
    sortOrder: 149,
  },
  {
    name: 'Farma (poljoprivreda)',
    slug: 'farm-agriculture',
    description: 'Poljoprivredna proizvodnja, biljke/životinje, inventar, sezonski radovi i prodaja.',
    icon: 'Sprout',
    category: 'Proizvodnja i industrija',
    modules: ['dashboard', 'inventory', 'contacts', 'invoices', 'procurement', 'expenses', 'manufacturing', 'calendar', 'reports', 'settings', 'quality', 'ecommerce'],
    featured: false,
    sortOrder: 150,
  },
]

// ============ USLUŽNE DJELATNOSTI (33) ============
const serviceIndustry: IndustryTemplateData[] = [
  {
    name: 'Fitness centar / teretana',
    slug: 'fitness-center',
    description: 'Članstvo, treneri, raspored, plaćanje, oprema i komunikacija sa članovima.',
    icon: 'Dumbbell',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'subscriptions', 'calendar', 'employees', 'appointments', 'invoices', 'payments', 'inventory', 'maintenance', 'website', 'email-marketing', 'loyalty', 'reports', 'settings'],
    featured: true,
    sortOrder: 44,
  },
  {
    name: 'Salon ljepote',
    slug: 'hair-salon',
    description: 'Zakazivanje termina, klijenti, kozmetika, inventar, plaćanje i marketing.',
    icon: 'Scissors',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'appointments', 'scheduler', 'calendar', 'invoices', 'pos', 'inventory', 'expenses', 'loyalty', 'social-media', 'website', 'reports', 'settings'],
    featured: false,
    sortOrder: 45,
  },
  {
    name: 'Studio za tetovaže',
    slug: 'tattoo-shop',
    description: 'Zakazivanje termina, klijenti, portfolio, galerija, prodaja opreme i nalazi.',
    icon: 'PenTool',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'appointments', 'scheduler', 'calendar', 'invoices', 'inventory', 'pos', 'social-media', 'website', 'reports', 'settings'],
    featured: false,
    sortOrder: 17,
  },
  {
    name: 'Firma za čišćenje',
    slug: 'cleaning-services',
    description: 'Zakazivanje, klijenti, ekipa, oprema, fakturisanje i kvalitet kontrole.',
    icon: 'SprayCan',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'appointments', 'field-service', 'work-orders', 'employees', 'calendar', 'invoices', 'expenses', 'reports', 'settings', 'contracts', 'quality'],
    featured: false,
    sortOrder: 94,
  },
  {
    name: 'Održavanje zelenih površina',
    slug: 'gardening',
    description: 'Zakazivanje, klijenti, oprema, biljke, inventar i sezonski radovi.',
    icon: 'Flower2',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'appointments', 'field-service', 'calendar', 'inventory', 'invoices', 'expenses', 'reports', 'settings', 'contracts', 'ecommerce'],
    featured: false,
    sortOrder: 96,
  },
  {
    name: 'Studio za fotografiju / video',
    slug: 'photography',
    description: 'Zakazivanje sesija, upravljanje klijentima, galerije, fakturisanje i isporuka.',
    icon: 'Camera',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'crm', 'calendar', 'appointments', 'invoices', 'offers', 'documents', 'website', 'social-media', 'reports', 'settings'],
    featured: false,
    sortOrder: 16,
  },
  {
    name: 'Pravna firma / odvjetnik',
    slug: 'law-firm',
    description: 'Upravljanje predmetima, klijentima, rokovima, dokumentima i fakturisanje usluga.',
    icon: 'Scale',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'projects', 'calendar', 'documents', 'invoices', 'offers', 'contracts', 'time-billing', 'finance', 'reports', 'settings', 'automation', 'signatures'],
    featured: true,
    sortOrder: 7,
  },
  {
    name: 'Nevladina organizacija (NVO)',
    slug: 'nonprofit-organisation',
    description: 'Projekti, donatori, volonteri, izveštaji, događaji i transparentnost.',
    icon: 'Heart',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'projects', 'documents', 'calendar', 'events', 'invoices', 'reports', 'website', 'blog', 'email-marketing', 'surveys', 'settings'],
    featured: false,
    sortOrder: 26,
  },
  {
    name: 'Ekološka agencija',
    slug: 'environmental-agency',
    description: 'Praćenje ekoloških standarda, izveštavanje, dozvole i usklađenost.',
    icon: 'Leaf',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'projects', 'documents', 'standards', 'reports', 'calendar', 'invoices', 'settings', 'compliance', 'quality'],
    featured: false,
    sortOrder: 5,
  },
  {
    name: 'Marketing agencija',
    slug: 'marketing-agency',
    description: 'Kampanje, CRM, društvene mreže, email marketing, projekti i analitika.',
    icon: 'Megaphone',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'crm', 'contacts', 'projects', 'calendar', 'social-media', 'email-marketing', 'marketing-automation', 'surveys', 'events', 'website', 'blog', 'seo', 'invoices', 'reports', 'finance', 'settings', 'automation', 'sms-marketing'],
    featured: true,
    sortOrder: 9,
  },
  {
    name: 'IT hardver i podrška',
    slug: 'it-hardware-support',
    description: 'Upravljanje IT opremom, tiketi za podršku, evidencija licence i održavanje.',
    icon: 'Monitor',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'assets', 'maintenance', 'support', 'projects', 'inventory', 'invoices', 'reports', 'settings', 'service-center', 'knowledge-base', 'contracts'],
    featured: false,
    sortOrder: 8,
  },
  {
    name: 'Penjački teretana',
    slug: 'climbing-gym',
    description: 'Članstvo, rezervacija termina, oprema, instruktori i fakturisanje.',
    icon: 'Mountain',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'subscriptions', 'calendar', 'reservations', 'invoices', 'payments', 'inventory', 'maintenance', 'website', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 42,
  },
  {
    name: 'Personalni trener',
    slug: 'personal-trainer',
    description: 'Klijenti, programi treninga, zakazivanje, napredovanje i plaćanje.',
    icon: 'Activity',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'appointments', 'calendar', 'invoices', 'payments', 'subscriptions', 'documents', 'website', 'email-marketing', 'social-media', 'reports', 'settings'],
    featured: false,
    sortOrder: 46,
  },
  {
    name: 'Wellness praksa',
    slug: 'wellness-practitioner',
    description: 'Klijenti, zakazivanje, terapije, naplata, dokumentacija i marketing.',
    icon: 'Sparkles',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'appointments', 'scheduler', 'calendar', 'invoices', 'payments', 'subscriptions', 'documents', 'website', 'email-marketing', 'social-media', 'reports', 'settings'],
    featured: false,
    sortOrder: 49,
  },
  {
    name: 'Yoga i Pilates studio',
    slug: 'yoga-pilates-studio',
    description: 'Članstvo, raspored časova, rezervacije, plaćanje i komunikacija.',
    icon: 'Flower2',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'subscriptions', 'calendar', 'reservations', 'appointments', 'invoices', 'payments', 'website', 'email-marketing', 'social-media', 'reports', 'settings'],
    featured: false,
    sortOrder: 50,
  },
  {
    name: 'Majstor za sve (Handyman)',
    slug: 'handyman-services',
    description: 'Različiti popravki, zakazivanje, klijenti, inventar alata i fakturisanje.',
    icon: 'Screwdriver',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'appointments', 'field-service', 'work-orders', 'inventory', 'invoices', 'expenses', 'calendar', 'reports', 'settings', 'contracts'],
    featured: false,
    sortOrder: 97,
  },
  {
    name: 'Električar',
    slug: 'electrician',
    description: 'Servisne intervencije, zakazivanje, klijenti, inventar delova i fakturisanje.',
    icon: 'Zap',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'appointments', 'field-service', 'work-orders', 'inventory', 'invoices', 'expenses', 'calendar', 'reports', 'settings', 'contracts'],
    featured: false,
    sortOrder: 95,
  },
  {
    name: 'Biciklistička radnja',
    slug: 'bike-shop',
    description: 'Prodaja i servis bicikala, inventar delova, klijenti i zakazivanje.',
    icon: 'Bike',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'inventory', 'service-center', 'appointments', 'invoices', 'pos', 'ecommerce', 'website', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 93,
  },
  {
    name: 'Iznajmljivanje bicikala',
    slug: 'bike-leasing',
    description: 'Flota bicikala, iznajmljivanje, rezervacije, održavanje i plaćanje.',
    icon: 'Bike',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'rentals', 'contacts', 'calendar', 'reservations', 'invoices', 'payments', 'maintenance', 'inventory', 'reports', 'settings'],
    featured: false,
    sortOrder: 92,
  },
  {
    name: 'Obućarska radnja',
    slug: 'shoemaker-services',
    description: 'Popravka obuće, klijenti, inventar materijala, zakazivanje i cene.',
    icon: 'Footprints',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'appointments', 'service-center', 'inventory', 'invoices', 'pos', 'expenses', 'reports', 'settings'],
    featured: false,
    sortOrder: 98,
  },
  {
    name: 'Izrada bilborda',
    slug: 'billboard-rental',
    description: 'Upravljanje bilbordima, zakazivanje kampanja, fakturisanje i praćenje lokacija.',
    icon: 'LayoutDashboard',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'invoices', 'offers', 'calendar', 'projects', 'documents', 'finance', 'settings', 'reports', 'crm', 'contracts'],
    featured: false,
    sortOrder: 2,
  },
  {
    name: 'Salon za nokte / pirsing',
    slug: 'nail-piercing-studio',
    description: 'Zakazivanje termina, klijenti, inventar, plaćanje, galerija i marketing.',
    icon: 'Sparkles',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'appointments', 'scheduler', 'calendar', 'invoices', 'pos', 'inventory', 'expenses', 'loyalty', 'social-media', 'website', 'reports', 'settings'],
    featured: false,
    sortOrder: 151,
  },
  {
    name: 'Autopraonica / servis',
    slug: 'car-wash-service',
    description: 'Zakazivanje, klijenti, usluge, paketi, plaćanje i lojalnost program.',
    icon: 'Droplets',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'appointments', 'scheduler', 'calendar', 'invoices', 'pos', 'expenses', 'loyalty', 'coupons', 'social-media', 'website', 'reports', 'settings'],
    featured: false,
    sortOrder: 152,
  },
  {
    name: 'Agencija za zaštitu / obezbjeđenje',
    slug: 'security-agency',
    description: 'Osoblje, objekti, raspored smjena, patrola, izveštaji i ugovori.',
    icon: 'Shield',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'employees', 'calendar', 'scheduler', 'invoices', 'contracts', 'documents', 'reports', 'settings', 'cameras', 'geolocation'],
    featured: false,
    sortOrder: 153,
  },
  {
    name: 'Web dizajn / digitalna agencija',
    slug: 'web-design-agency',
    description: 'Web projekti, dizajn, development, klijenti, hosting, domeni i naplata.',
    icon: 'Globe',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'projects', 'calendar', 'website', 'cms', 'blog', 'seo', 'ecommerce', 'invoices', 'offers', 'contracts', 'time-billing', 'reports', 'settings', 'support', 'knowledge-base'],
    featured: true,
    sortOrder: 154,
  },
  {
    name: 'Notar / javni bilježnik',
    slug: 'notary-public',
    description: 'Overavanje dokumenata, klijenti, rokovi, arhiva, knjige i naplata.',
    icon: 'Stamp',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'projects', 'calendar', 'documents', 'invoices', 'payments', 'signatures', 'reports', 'settings', 'contracts'],
    featured: false,
    sortOrder: 155,
  },
  {
    name: 'Terenski servis',
    slug: 'field-service-appliances',
    description: 'Servis kućanskih aparata i elektronike, zakazivanje, inventar dijelova, naplata.',
    icon: 'Wrench',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'appointments', 'field-service', 'work-orders', 'inventory', 'invoices', 'expenses', 'calendar', 'reports', 'settings', 'contracts', 'service-center'],
    featured: false,
    sortOrder: 156,
  },
  {
    name: 'Centar za obuku pasa',
    slug: 'dog-training-center',
    description: 'Zakazivanje treninga, vlasnici, psi, programi, plaćanje i komunikacija.',
    icon: 'Dog',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'appointments', 'scheduler', 'calendar', 'invoices', 'payments', 'inventory', 'website', 'email-marketing', 'social-media', 'reports', 'settings'],
    featured: false,
    sortOrder: 157,
  },
  {
    name: 'Bračna / porodična savjetovališta',
    slug: 'family-counseling',
    description: 'Klijenti, zakazivanje, terapije, dokumentacija, naplata i povjerljivost.',
    icon: 'Heart',
    category: 'Uslužne djelatnosti',
    modules: ['dashboard', 'contacts', 'appointments', 'scheduler', 'calendar', 'invoices', 'payments', 'subscriptions', 'documents', 'reports', 'settings', 'website'],
    featured: false,
    sortOrder: 158,
  },
]

// ============ OSTALO (21) ============
const miscOther: IndustryTemplateData[] = [
  {
    name: 'Sportski klub',
    slug: 'sports-club',
    description: 'Članstvo, treningi, takmičenja, plaćanje, oprema i komunikacija.',
    icon: 'Dumbbell',
    category: 'Ostalo',
    modules: ['dashboard', 'contacts', 'calendar', 'subscriptions', 'invoices', 'payments', 'inventory', 'events', 'email-marketing', 'website', 'reports', 'settings'],
    featured: false,
    sortOrder: 28,
  },
  {
    name: 'Udruženje vlasnika stanova',
    slug: 'homeowner-association',
    description: 'Stanari, računi, održavanje, zadaće, dokumenti i godišnji plan.',
    icon: 'Building',
    category: 'Ostalo',
    modules: ['dashboard', 'contacts', 'property', 'work-orders', 'maintenance', 'utilities', 'invoices', 'payments', 'documents', 'calendar', 'reports', 'settings', 'contracts', 'complaints'],
    featured: false,
    sortOrder: 159,
  },
  {
    name: 'Koncertne dvorane',
    slug: 'concert-halls',
    description: 'Upravljanje događajima, rezervacije, karte, prodaja ulaznica i marketinške kampanje.',
    icon: 'Music',
    category: 'Ostalo',
    modules: ['dashboard', 'events', 'calendar', 'reservations', 'contacts', 'invoices', 'pos', 'coupons', 'email-marketing', 'website', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 12,
  },
  {
    name: 'Galerija',
    slug: 'gallery',
    description: 'Izložbe, umetnici, prodaja dela, katalogizacija i praćenje posetilaca.',
    icon: 'Frame',
    category: 'Ostalo',
    modules: ['dashboard', 'contacts', 'inventory', 'invoices', 'calendar', 'events', 'crm', 'website', 'blog', 'social-media', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 13,
  },
  {
    name: 'Biblioteka',
    slug: 'library',
    description: 'Upravljanje knjigama, članstvo, izdavanje, rezervacije i katalog.',
    icon: 'BookOpen',
    category: 'Ostalo',
    modules: ['dashboard', 'library', 'contacts', 'calendar', 'reports', 'settings', 'education', 'documents', 'website'],
    featured: false,
    sortOrder: 14,
  },
  {
    name: 'Muzej',
    slug: 'museum',
    description: 'Eksponati, izložbe, karte, posetioci, edukativni programi i donacije.',
    icon: 'Landmark',
    category: 'Ostalo',
    modules: ['dashboard', 'contacts', 'inventory', 'events', 'calendar', 'invoices', 'education', 'website', 'reports', 'settings', 'reservations'],
    featured: false,
    sortOrder: 15,
  },
  {
    name: 'Pozorište',
    slug: 'theater',
    description: 'Predstave, repertoar, karte, glumci, rezervacije i marketing kampanje.',
    icon: 'Drama',
    category: 'Ostalo',
    modules: ['dashboard', 'events', 'calendar', 'contacts', 'reservations', 'invoices', 'email-marketing', 'website', 'blog', 'social-media', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 18,
  },
  {
    name: 'Coworking prostor',
    slug: 'coworking',
    description: 'Članstvo, rezervacija radnih mesta, kalendar događaja, fakturisanje i komunikacija.',
    icon: 'Laptop',
    category: 'Ostalo',
    modules: ['dashboard', 'contacts', 'calendar', 'reservations', 'invoices', 'subscriptions', 'events', 'chat', 'website', 'reports', 'settings', 'offers'],
    featured: false,
    sortOrder: 23,
  },
  {
    name: 'Event menadžment',
    slug: 'event-management',
    description: 'Planiranje i organizacija događaja, klijenti, dobavljači, budžet i logistika.',
    icon: 'PartyPopper',
    category: 'Ostalo',
    modules: ['dashboard', 'events', 'calendar', 'projects', 'contacts', 'crm', 'invoices', 'offers', 'expenses', 'email-marketing', 'social-media', 'website', 'reports', 'settings', 'marketing-automation'],
    featured: true,
    sortOrder: 24,
  },
  {
    name: 'Klub članova',
    slug: 'members-club',
    description: 'Članstvo, mesečne/godišnje članarine, događaji, rezervacije i komunikacija.',
    icon: 'UserCheck',
    category: 'Ostalo',
    modules: ['dashboard', 'contacts', 'subscriptions', 'calendar', 'events', 'reservations', 'invoices', 'payments', 'email-marketing', 'website', 'reports', 'settings'],
    featured: false,
    sortOrder: 25,
  },
  {
    name: 'Sportski događaji',
    slug: 'sport-events',
    description: 'Organizacija takmičenja, ekipe, registar učesnika, karte i sponzori.',
    icon: 'Trophy',
    category: 'Ostalo',
    modules: ['dashboard', 'events', 'calendar', 'contacts', 'crm', 'invoices', 'offers', 'email-marketing', 'website', 'reports', 'settings'],
    featured: false,
    sortOrder: 27,
  },
  {
    name: 'Letnji kampovi',
    slug: 'summer-camps',
    description: 'Učesnici, roditelji, smene, aktivnosti, zdravstveni kartoni i plaćanje.',
    icon: 'Tent',
    category: 'Ostalo',
    modules: ['dashboard', 'contacts', 'education', 'calendar', 'enrollment', 'invoices', 'payments', 'documents', 'website', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 29,
  },
  {
    name: 'Timski sportovi',
    slug: 'team-sports-club',
    description: 'Ekipni sportovi, treneri, utakmice, statistika, članstvo i finansije.',
    icon: 'Medal',
    category: 'Ostalo',
    modules: ['dashboard', 'contacts', 'calendar', 'events', 'subscriptions', 'invoices', 'inventory', 'website', 'email-marketing', 'reports', 'settings', 'gamification'],
    featured: false,
    sortOrder: 30,
  },
  {
    name: 'Vjenčanja i proslave',
    slug: 'wedding-planner',
    description: 'Planiranje vjenčanja, klijenti, dobavljači, budžet, raspored i dokumentacija.',
    icon: 'Ring',
    category: 'Ostalo',
    modules: ['dashboard', 'contacts', 'crm', 'projects', 'calendar', 'invoices', 'offers', 'expenses', 'documents', 'website', 'social-media', 'email-marketing', 'reports', 'settings'],
    featured: false,
    sortOrder: 31,
  },
  {
    name: 'Policijska / vatrogasna postaja',
    slug: 'police-fire-station',
    description: 'Osoblje, smjene, akcije, dokumentacija, inventar opreme i izveštaji.',
    icon: 'ShieldAlert',
    category: 'Ostalo',
    modules: ['dashboard', 'employees', 'calendar', 'scheduler', 'inventory', 'assets', 'maintenance', 'documents', 'reports', 'settings', 'vehicles', 'incidents'],
    featured: false,
    sortOrder: 160,
  },
  {
    name: 'Crveni križ',
    slug: 'red-cross',
    description: 'Volonteri, akcije, donacije, hitne intervencije, izvještaji i javna komunikacija.',
    icon: 'Heart',
    category: 'Ostalo',
    modules: ['dashboard', 'contacts', 'events', 'projects', 'calendar', 'documents', 'volunteers', 'invoices', 'reports', 'website', 'email-marketing', 'surveys', 'settings'],
    featured: false,
    sortOrder: 161,
  },
]

// ============ ALL TEMPLATES ============
export const industryTemplatesData: IndustryTemplateData[] = [
  ...accountingFinance,
  ...hospitalityTourism,
  ...retailCommerce,
  ...healthcare,
  ...education,
  ...constructionRealEstate,
  ...logisticsTransport,
  ...manufacturingIndustry,
  ...serviceIndustry,
  ...miscOther,
]

// Category metadata
export const industryCategories = [
  { name: 'Računovodstvo i finansije', icon: 'Calculator', count: accountingFinance.length },
  { name: 'Ugostiteljstvo i turizam', icon: 'Hotel', count: hospitalityTourism.length },
  { name: 'Trgovina i maloprodaja', icon: 'ShoppingBag', count: retailCommerce.length },
  { name: 'Zdravstvo i farmacija', icon: 'Pill', count: healthcare.length },
  { name: 'Obrazovanje', icon: 'GraduationCap', count: education.length },
  { name: 'Građevina i nekretnine', icon: 'Building2', count: constructionRealEstate.length },
  { name: 'Logistika i transport', icon: 'Truck', count: logisticsTransport.length },
  { name: 'Proizvodnja i industrija', icon: 'Factory', count: manufacturingIndustry.length },
  { name: 'Uslužne djelatnosti', icon: 'Briefcase', count: serviceIndustry.length },
  { name: 'Ostalo', icon: 'Star', count: miscOther.length },
]
