import type { ThemeSettings } from './theme'

// ============ THEME PRESETS ============

export interface ThemePreset {
  name: string
  nameEn: string
  settings: ThemeSettings
}

export const themePresets: ThemePreset[] = [
  {
    name: 'Zelena (podrazumevana)',
    nameEn: 'Green (Default)',
    settings: {
      primaryColor: '#16a34a',
      primaryForeground: '#f0fdf4',
      accentColor: '#f0fdf4',
      sidebarColor: '#1a2e1e',
      sidebarForeground: '#e8f5e9',
      borderRadius: '0.625rem',
      logo: null,
      companyName: '',
    },
  },
  {
    name: 'Plava',
    nameEn: 'Blue',
    settings: {
      primaryColor: '#2563eb',
      primaryForeground: '#eff6ff',
      accentColor: '#eff6ff',
      sidebarColor: '#1e293b',
      sidebarForeground: '#e2e8f0',
      borderRadius: '0.625rem',
      logo: null,
      companyName: '',
    },
  },
  {
    name: 'Ljubičasta',
    nameEn: 'Purple',
    settings: {
      primaryColor: '#7c3aed',
      primaryForeground: '#faf5ff',
      accentColor: '#faf5ff',
      sidebarColor: '#2e1a47',
      sidebarForeground: '#ede9fe',
      borderRadius: '0.625rem',
      logo: null,
      companyName: '',
    },
  },
  {
    name: 'Crvena',
    nameEn: 'Red',
    settings: {
      primaryColor: '#dc2626',
      primaryForeground: '#fef2f2',
      accentColor: '#fef2f2',
      sidebarColor: '#2d1b1b',
      sidebarForeground: '#fecaca',
      borderRadius: '0.625rem',
      logo: null,
      companyName: '',
    },
  },
  {
    name: 'Narandžasta',
    nameEn: 'Orange',
    settings: {
      primaryColor: '#ea580c',
      primaryForeground: '#fff7ed',
      accentColor: '#fff7ed',
      sidebarColor: '#2d1f10',
      sidebarForeground: '#fed7aa',
      borderRadius: '0.625rem',
      logo: null,
      companyName: '',
    },
  },
  {
    name: 'Roza',
    nameEn: 'Pink',
    settings: {
      primaryColor: '#db2777',
      primaryForeground: '#fdf2f8',
      accentColor: '#fdf2f8',
      sidebarColor: '#2d1525',
      sidebarForeground: '#fbcfe8',
      borderRadius: '0.625rem',
      logo: null,
      companyName: '',
    },
  },
  {
    name: 'Teal',
    nameEn: 'Teal',
    settings: {
      primaryColor: '#0d9488',
      primaryForeground: '#f0fdfa',
      accentColor: '#f0fdfa',
      sidebarColor: '#152e2c',
      sidebarForeground: '#ccfbf1',
      borderRadius: '0.625rem',
      logo: null,
      companyName: '',
    },
  },
  {
    name: 'Tamna',
    nameEn: 'Dark',
    settings: {
      primaryColor: '#6b7280',
      primaryForeground: '#f9fafb',
      accentColor: '#f3f4f6',
      sidebarColor: '#111827',
      sidebarForeground: '#e5e7eb',
      borderRadius: '0.625rem',
      logo: null,
      companyName: '',
    },
  },
  {
    name: 'Indigo',
    nameEn: 'Indigo',
    settings: {
      primaryColor: '#4f46e5',
      primaryForeground: '#eef2ff',
      accentColor: '#eef2ff',
      sidebarColor: '#1e1b4b',
      sidebarForeground: '#c7d2fe',
      borderRadius: '0.75rem',
      logo: null,
      companyName: '',
    },
  },
  {
    name: 'Cyan',
    nameEn: 'Cyan',
    settings: {
      primaryColor: '#0891b2',
      primaryForeground: '#ecfeff',
      accentColor: '#ecfeff',
      sidebarColor: '#0c2d3a',
      sidebarForeground: '#a5f3fc',
      borderRadius: '0.5rem',
      logo: null,
      companyName: '',
    },
  },
  {
    name: 'Lime',
    nameEn: 'Lime',
    settings: {
      primaryColor: '#65a30d',
      primaryForeground: '#f7fee7',
      accentColor: '#f7fee7',
      sidebarColor: '#1a2e05',
      sidebarForeground: '#d9f99d',
      borderRadius: '0.625rem',
      logo: null,
      companyName: '',
    },
  },
  {
    name: 'Fuchsia',
    nameEn: 'Fuchsia',
    settings: {
      primaryColor: '#c026d3',
      primaryForeground: '#fdf4ff',
      accentColor: '#fdf4ff',
      sidebarColor: '#2d0a31',
      sidebarForeground: '#f0abfc',
      borderRadius: '0.75rem',
      logo: null,
      companyName: '',
    },
  },
  {
    name: 'Smeđa (Premium)',
    nameEn: 'Brown (Premium)',
    settings: {
      primaryColor: '#92400e',
      primaryForeground: '#fef3c7',
      accentColor: '#fef3c7',
      sidebarColor: '#1c1207',
      sidebarForeground: '#fcd34d',
      borderRadius: '0.375rem',
      logo: null,
      companyName: '',
    },
  },
  {
    name: 'Siva (Minimal)',
    nameEn: 'Gray (Minimal)',
    settings: {
      primaryColor: '#475569',
      primaryForeground: '#f8fafc',
      accentColor: '#f1f5f9',
      sidebarColor: '#0f172a',
      sidebarForeground: '#cbd5e1',
      borderRadius: '0rem',
      logo: null,
      companyName: '',
    },
  },
]
