import { useState, useEffect, useCallback, useMemo } from 'react'

export function useProcurementManager() {


  return {
    activeTab,
    approvalMetrics,
    c,
    d,
    deleteConfirmOpen,
    editingPR,
    filterDept,
    filterPRPriority,
    filterPRStatus,
    filterSuppCat,
    filterSuppStatus,
    filteredPRs,
    filteredSuppliers,
    handleDeletePR,
    handleSavePR,
    loadData,
    monthlySpending,
    openNewPR,
    prDetailOpen,
    prDialogOpen,
    prs,
    searchQuery,
    selectedPR,
    selectedSupplier,
    setActiveTab,
    setDeleteConfirmOpen,
    setFilterDept,
    setFilterPRPriority,
    setFilterPRStatus,
    setFilterSuppCat,
    setFilterSuppStatus,
    setPrDetailOpen,
    setPrDialogOpen,
    setSupplierDetailOpen,
    spendingByCategory,
    sub,
    supplierDetailOpen,
    suppliers,
  }
}
