'use client'
import { useState, useEffect, useCallback } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Badge } from '@/components/ui/badge'; import { Skeleton } from '@/components/ui/skeleton'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'; import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'; import { Label } from '@/components/ui/label'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Plus, Search, Trash2, Pencil, Eye, List, ArrowLeft } from 'lucide-react'; import { toast } from 'sonner'; import { formatDate } from '@/lib/helpers'

type PriceListItem = { id: string; listNo: string; name: string; category: string; type: string; validFrom: string; validUntil: string; items: number; status: string; createdBy: string; notes: string }
const STATUSES: Record<string, { color: string; label: string }> = { active: { color: 'bg-emerald-100 text-emerald-800', label: 'Aktivan' }, draft: { color: 'bg-amber-100 text-amber-800', label: 'Nacrt' }, archived: { color: 'bg-gray-100 text-gray-800', label: 'Arhiviran' } }
function getStatusBadge(s: string) { const r = STATUSES[s]; return r ? <Badge className={`${r.color} text-xs`}>{r.label}</Badge> : <Badge className="text-xs">{s}</Badge> }

export function PriceLists() {
  const [data, setData] = useState<PriceListItem[]>([]); const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState(''); const [dialogOpen, setDialogOpen] = useState(false); const [editItem, setEditItem] = useState<PriceListItem | null>(null)
  const [detailId, setDetailId] = useState<string | null>(null); const [form, setForm] = useState<Partial<PriceListItem>>({}); const [activeTab, setActiveTab] = useState('pregled')

  const fetchData = useCallback(async () => {
    try {
      setLoading(true)
      const params = new URLSearchParams()
      if (search) params.set('search', search)
      const res = await fetch(`/api/price-lists-v2?${params}`)
      if (!res.ok) throw new Error()
      const json = await res.json()
      setData(json)
    } catch { toast.error('Greška pri učitavanju') } finally { setLoading(false) }
  }, [search])

  useEffect(() => { fetchData() }, [fetchData])

  const filtered = data
  const handleDelete = async (id: string) => { if (!confirm('Obrisati?')) return; try { const res = await fetch(`/api/price-lists-v2/${id}`, { method: 'DELETE' }); if (!res.ok) throw new Error(); toast.success('Obrisano'); fetchData() } catch { toast.error('Greška pri brisanju') } }
  const openCreate = () => { setEditItem(null); setForm({ name: '', category: 'Opšti', type: 'retail', validFrom: new Date().toISOString().split('T')[0], validUntil: '', status: 'draft', createdBy: '', notes: '' }); setDialogOpen(true) }
  const openEdit = (item: PriceListItem) => { setEditItem(item); setForm({ ...item }); setDialogOpen(true) }
  const handleSave = async () => { if (!form.name) { toast.error('Unesite naziv'); return }; try { const url = editItem ? `/api/price-lists-v2/${editItem.id}` : '/api/price-lists-v2'; const res = await fetch(url, { method: editItem ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!res.ok) throw new Error(); toast.success(editItem ? 'Ažurirano' : 'Kreiran'); setDialogOpen(false); fetchData() } catch { toast.error('Greška pri čuvanju') } }
  if (loading) return <div className="space-y-4"><Skeleton className="h-8 w-64" /><Skeleton className="h-64" /></div>
  const detailItem = detailId ? data.find(i => i.id === detailId) : null

  return (<div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight">Cenovnici</h1><p className="text-sm text-muted-foreground">Upravljanje cenovnicima i cenovnim listama</p></div><Button size="sm" className="gap-2" onClick={openCreate}><Plus className="h-4 w-4" />Novi cenovnik</Button></div>
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3"><Card className="p-4"><div className="text-xs text-muted-foreground mb-1 flex items-center gap-1"><List className="h-3 w-3" />Ukupno</div><p className="text-2xl font-bold">{data.length}</p></Card><Card className="p-4"><div className="text-xs text-emerald-600 mb-1">Aktivnih</div><p className="text-2xl font-bold text-emerald-700">{data.filter(i => i.status === 'active').length}</p></Card><Card className="p-4"><div className="text-xs text-amber-600 mb-1">Nacrti</div><p className="text-2xl font-bold text-amber-700">{data.filter(i => i.status === 'draft').length}</p></Card><Card className="p-4"><div className="text-xs text-muted-foreground mb-1">Ukupno stavki</div><p className="text-2xl font-bold">{data.reduce((s, i) => s + i.items, 0)}</p></Card></div>
    <Tabs value={activeTab} onValueChange={setActiveTab}><TabsList><TabsTrigger value="pregled">Pregled</TabsTrigger><TabsTrigger value="dodaj">Dodaj</TabsTrigger><TabsTrigger value="uredi">Uredi</TabsTrigger></TabsList>
      <TabsContent value="pregled" className="mt-4"><Card><CardHeader className="pb-3"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><CardTitle className="text-base">Lista cenovnika</CardTitle><div className="relative"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground" /><Input placeholder="Pretraga..." className="pl-8 h-8 w-44 text-xs" value={search} onChange={e => setSearch(e.target.value)} /></div></div></CardHeader><CardContent><div className="max-h-[480px] overflow-y-auto"><Table><TableHeader><TableRow><TableHead className="text-xs">Naziv</TableHead><TableHead className="text-xs hidden sm:table-cell">Kategorija</TableHead><TableHead className="text-xs hidden md:table-cell">Tip</TableHead><TableHead className="text-xs hidden md:table-cell">Stavki</TableHead><TableHead className="text-xs hidden lg:table-cell">Period</TableHead><TableHead className="text-xs">Status</TableHead><TableHead className="text-xs text-right">Akcije</TableHead></TableRow></TableHeader><TableBody>{filtered.length === 0 ? <TableRow><TableCell colSpan={7} className="text-center py-8 text-muted-foreground text-sm">Nema</TableCell></TableRow> : filtered.map(item => (<TableRow key={item.id}><TableCell className="text-xs font-medium">{item.name}</TableCell><TableCell className="text-xs text-muted-foreground hidden sm:table-cell">{item.category}</TableCell><TableCell className="text-xs hidden md:table-cell">{item.type === 'retail' ? 'Malo' : item.type === 'wholesale' ? 'Vele' : 'Specijalan'}</TableCell><TableCell className="text-xs hidden md:table-cell">{item.items}</TableCell><TableCell className="text-xs text-muted-foreground hidden lg:table-cell">{formatDate(item.validFrom)} — {formatDate(item.validUntil)}</TableCell><TableCell>{getStatusBadge(item.status)}</TableCell><TableCell className="text-right"><div className="flex items-center justify-end gap-1"><Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setDetailId(item.id)}><Eye className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => openEdit(item)}><Pencil className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7 text-red-500" onClick={() => handleDelete(item.id)}><Trash2 className="h-3.5 w-3.5" /></Button></div></TableCell></TableRow>))}</TableBody></Table></div></CardContent></Card></TabsContent>
      <TabsContent value="dodaj" className="mt-4"><Card><CardHeader><CardTitle className="text-base">Novi cenovnik</CardTitle></CardHeader><CardContent><div className="grid gap-4"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="grid gap-2"><Label className="text-xs">Naziv *</Label><Input className="text-xs" value={form.name || ''} onChange={e => setForm({ ...form, name: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Kategorija</Label><Input className="text-xs" value={form.category || ''} onChange={e => setForm({ ...form, category: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Tip</Label><Select value={form.type || 'retail'} onValueChange={v => setForm({ ...form, type: v })}><SelectTrigger className="text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="retail">Maloprodaja</SelectItem><SelectItem value="wholesale">Veleprodaja</SelectItem><SelectItem value="special">Specijalan</SelectItem></SelectContent></Select></div><div className="grid gap-2"><Label className="text-xs">Kreirao</Label><Input className="text-xs" value={form.createdBy || ''} onChange={e => setForm({ ...form, createdBy: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Važi od</Label><Input className="text-xs" type="date" value={form.validFrom || ''} onChange={e => setForm({ ...form, validFrom: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Važi do</Label><Input className="text-xs" type="date" value={form.validUntil || ''} onChange={e => setForm({ ...form, validUntil: e.target.value })} /></div></div><Button size="sm" className="w-fit gap-2" onClick={handleSave}><Plus className="h-4 w-4" />Kreiraj</Button></div></CardContent></Card></TabsContent>
      <TabsContent value="uredi" className="mt-4"><Card><CardHeader><CardTitle className="text-base">Uredi</CardTitle></CardHeader><CardContent><div className="max-h-[500px] overflow-y-auto space-y-3">{data.map(item => (<div key={item.id} className="flex items-center gap-3 p-3 border rounded-lg"><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><span className="text-xs font-medium">{item.name}</span>{getStatusBadge(item.status)}</div><p className="text-xs text-muted-foreground truncate">{item.category} — {item.items} stavki — {formatDate(item.validFrom)} do {formatDate(item.validUntil)}</p></div><Button variant="ghost" size="icon" className="h-7 w-7 shrink-0" onClick={() => openEdit(item)}><Pencil className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7 text-red-500 shrink-0" onClick={() => handleDelete(item.id)}><Trash2 className="h-3.5 w-3.5" /></Button></div>))}</div></CardContent></Card></TabsContent>
    </Tabs>
    {detailId && detailItem && (<Card><CardHeader className="pb-3"><div className="flex items-center gap-2"><Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setDetailId(null)}><ArrowLeft className="h-4 w-4" /></Button><CardTitle className="text-base">{detailItem.name}</CardTitle></div></CardHeader><CardContent><div className="space-y-3"><div className="flex items-center gap-2">{getStatusBadge(detailItem.status)}</div><div className="grid grid-cols-2 gap-3">{[['Kategorija', detailItem.category],['Tip', detailItem.type],['Stavki', String(detailItem.items)],['Kreirao', detailItem.createdBy],['Važi od', formatDate(detailItem.validFrom)],['Važi do', formatDate(detailItem.validUntil)]].map(([l, v]) => (<div key={l} className="p-2 rounded-lg bg-muted/50"><div className="text-xs text-muted-foreground">{l}</div><div className="text-xs font-medium">{v}</div></div>))}</div></div></CardContent></Card>)}
    {dialogOpen && (<Card><CardHeader className="pb-3"><div className="flex items-center gap-2"><Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setDialogOpen(false)}><ArrowLeft className="h-4 w-4" /></Button><CardTitle className="text-base">{editItem ? 'Uredi' : 'Novi'}</CardTitle></div></CardHeader><CardContent><div className="grid gap-4"><div className="grid grid-cols-2 gap-3"><div className="grid gap-2"><Label className="text-xs">Naziv *</Label><Input className="text-xs" value={form.name || ''} onChange={e => setForm({ ...form, name: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Status</Label><Select value={form.status || 'draft'} onValueChange={v => setForm({ ...form, status: v })}><SelectTrigger className="text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="active">Aktivan</SelectItem><SelectItem value="draft">Nacrt</SelectItem><SelectItem value="archived">Arhiviran</SelectItem></SelectContent></Select></div></div></div><div className="flex justify-end gap-2 pt-4"><Button variant="outline" size="sm" onClick={() => setDialogOpen(false)}>Otkaži</Button><Button size="sm" onClick={handleSave}>Sačuvaj</Button></div></CardContent></Card>)}
  </div>)
}
