export interface MarketplaceContentProps {
  activeTab: any
  setActiveTab: React.Dispatch<React.SetStateAction<any>>
  loading: any
  setLoading: React.Dispatch<React.SetStateAction<any>>
  dashData: any
  setDashData: React.Dispatch<React.SetStateAction<any>>
  vendors: any[]
  setVendors: React.Dispatch<React.SetStateAction<any[]>>
  vendorSearch: any
  setVendorSearch: React.Dispatch<React.SetStateAction<any>>
  vendorFilter: any
  setVendorFilter: React.Dispatch<React.SetStateAction<any>>
  orders: any[]
  setOrders: React.Dispatch<React.SetStateAction<any[]>>
  orderSearch: any
  setOrderSearch: React.Dispatch<React.SetStateAction<any>>
  orderFilter: any
  setOrderFilter: React.Dispatch<React.SetStateAction<any>>
  reviews: any[]
  setReviews: React.Dispatch<React.SetStateAction<any[]>>
  disputes: any[]
  setDisputes: React.Dispatch<React.SetStateAction<any[]>>
  products: any[]
  setProducts: React.Dispatch<React.SetStateAction<any[]>>
  categories: string[]
  setCategories: React.Dispatch<React.SetStateAction<string[]>>
  prodSearch: any
  setProdSearch: React.Dispatch<React.SetStateAction<any>>
  prodCategory: any
  setProdCategory: React.Dispatch<React.SetStateAction<any>>
  prodVendor: any
  setProdVendor: React.Dispatch<React.SetStateAction<any>>
  prodFeatured: any
  setProdFeatured: React.Dispatch<React.SetStateAction<any>>
  coupons: any[]
  setCoupons: React.Dispatch<React.SetStateAction<any[]>>
  vendorDialogOpen: any
  setVendorDialogOpen: React.Dispatch<React.SetStateAction<any>>
  orderDialogOpen: any
  setOrderDialogOpen: React.Dispatch<React.SetStateAction<any>>
  reviewDialogOpen: any
  setReviewDialogOpen: React.Dispatch<React.SetStateAction<any>>
  disputeDialogOpen: any
  setDisputeDialogOpen: React.Dispatch<React.SetStateAction<any>>
  vendorDetailOpen: any
  setVendorDetailOpen: React.Dispatch<React.SetStateAction<any>>
  orderDetailOpen: any
  setOrderDetailOpen: React.Dispatch<React.SetStateAction<any>>
  productDialogOpen: any
  setProductDialogOpen: React.Dispatch<React.SetStateAction<any>>
  couponDialogOpen: any
  setCouponDialogOpen: React.Dispatch<React.SetStateAction<any>>
  selectedItem: any
  setSelectedItem: React.Dispatch<React.SetStateAction<any>>
  vendorForm: any
  setVendorForm: React.Dispatch<React.SetStateAction<any>>
  orderForm: any
  setOrderForm: React.Dispatch<React.SetStateAction<any>>
  orderItems: any[]
  setOrderItems: React.Dispatch<React.SetStateAction<any[]>>
  reviewForm: any
  setReviewForm: React.Dispatch<React.SetStateAction<any>>
  disputeForm: any
  setDisputeForm: React.Dispatch<React.SetStateAction<any>>
  productForm: any
  setProductForm: React.Dispatch<React.SetStateAction<any>>
  couponForm: any
  setCouponForm: React.Dispatch<React.SetStateAction<any>>
  toast: any
  setToast: React.Dispatch<React.SetStateAction<any>>
  emptyVendor: any
  emptyOrder: any
  emptyReview: any
  emptyDispute: any
  emptyProduct: any
  emptyCoupon: any
}
