import type { Reservation } from "./types";

export const INITIAL: Reservation[] = [
  {
    id: "1",
    reservationNo: "REZ-2024-001",
    guestName: "Luka Petrović",
    phone: "+381 63 123 4567",
    email: "luka.p@email.com",
    date: "2024-06-16",
    time: "19:00",
    partySize: 4,
    tableNo: "T-5",
    area: "indoor",
    status: "confirmed",
    occasion: "Rođendan",
    specialRequests: "Torta za 4 osobe, svetlića na sto",
    source: "phone",
    duration: 120,
    deposit: 2000,
    notes: "",
  },
  {
    id: "2",
    reservationNo: "REZ-2024-002",
    guestName: "Ana Stanković",
    phone: "+381 64 987 6543",
    email: "ana.s@email.com",
    date: "2024-06-15",
    time: "20:00",
    partySize: 2,
    tableNo: "T-12",
    area: "terrace",
    status: "checked_in",
    occasion: "",
    specialRequests: "Mesto pored prozora ako moguće",
    source: "website",
    duration: 90,
    deposit: 0,
    notes: "Stigla na vreme",
  },
  {
    id: "3",
    reservationNo: "REZ-2024-003",
    guestName: "Dragan Milić",
    phone: "+381 65 555 1234",
    email: "",
    date: "2024-06-15",
    time: "12:30",
    partySize: 8,
    tableNo: "T-1",
    area: "vip",
    status: "pending",
    occasion: "Poslovni ručak",
    specialRequests: "Privatna prostorija, projektor, meni za 8 osoba",
    source: "phone",
    duration: 180,
    deposit: 5000,
    notes: "Čeka potvrdu — admin treba da odobri VIP",
  },
  {
    id: "4",
    reservationNo: "REZ-2024-004",
    guestName: "Jelena Nikolić",
    phone: "+381 62 444 8899",
    email: "jelena.n@email.com",
    date: "2024-06-14",
    time: "19:30",
    partySize: 6,
    tableNo: "T-3",
    area: "indoor",
    status: "completed",
    occasion: "",
    specialRequests: "",
    source: "app",
    duration: 120,
    deposit: 0,
    notes: "Sve prošlo u redu",
  },
  {
    id: "5",
    reservationNo: "REZ-2024-005",
    guestName: "Nikola Jovanović",
    phone: "+381 61 777 3344",
    email: "",
    date: "2024-06-14",
    time: "20:00",
    partySize: 3,
    tableNo: "",
    area: "outdoor",
    status: "cancelled",
    occasion: "",
    specialRequests: "",
    source: "phone",
    duration: 90,
    deposit: 0,
    notes: "Otkazano zbog kiše",
  },
  {
    id: "6",
    reservationNo: "REZ-2024-006",
    guestName: "Sara Đorđević",
    phone: "+381 60 222 7766",
    email: "sara.dj@email.com",
    date: "2024-06-16",
    time: "18:00",
    partySize: 2,
    tableNo: "T-8",
    area: "bar",
    status: "confirmed",
    occasion: "",
    specialRequests: "Veganski meni",
    source: "website",
    duration: 60,
    deposit: 0,
    notes: "",
  },
  {
    id: "7",
    reservationNo: "REZ-2024-007",
    guestName: "Ivan Savić",
    phone: "+381 66 888 1122",
    email: "",
    date: "2024-06-13",
    time: "19:00",
    partySize: 5,
    tableNo: "T-7",
    area: "indoor",
    status: "no_show",
    occasion: "",
    specialRequests: "",
    source: "phone",
    duration: 90,
    deposit: 0,
    notes: "Nije se pojavio — 2x poziv, nema odgovora",
  },
  {
    id: "8",
    reservationNo: "REZ-2024-008",
    guestName: "Milica Marković",
    phone: "+381 63 333 6688",
    email: "milica.m@email.com",
    date: "2024-06-17",
    time: "13:00",
    partySize: 10,
    tableNo: "T-1+T-2",
    area: "indoor",
    status: "confirmed",
    occasion: "Slava",
    specialRequests: "Slavski kolač, žito, sveće. Sto za 10 sa prostorom oko",
    source: "email",
    duration: 180,
    deposit: 8000,
    notes: "Depozit plaćen — preostalo na licu mesta",
  },
  {
    id: "9",
    reservationNo: "REZ-2024-009",
    guestName: "Goran Petrović",
    phone: "+381 62 555 7799",
    email: "",
    date: "2024-06-16",
    time: "21:00",
    partySize: 2,
    tableNo: "",
    area: "terrace",
    status: "pending",
    occasion: "",
    specialRequests: "",
    source: "walk_in",
    duration: 60,
    deposit: 0,
    notes: "Dospel bez rezervacije — upisan na terasu",
  },
  {
    id: "10",
    reservationNo: "REZ-2024-010",
    guestName: "Maja Stojanović",
    phone: "+381 64 111 4455",
    email: "maja.s@email.com",
    date: "2024-06-18",
    time: "20:00",
    partySize: 4,
    tableNo: "T-4",
    area: "indoor",
    status: "confirmed",
    occasion: "Anniversary",
    specialRequests: "Romantično uređenje stola, sveće",
    source: "app",
    duration: 120,
    deposit: 1500,
    notes: "",
  },
];

export const STATUSES: Record<string, { color: string; label: string }> = {
  confirmed: { color: "bg-emerald-100 text-emerald-800", label: "Potvrđena" },
  pending: { color: "bg-amber-100 text-amber-800", label: "Na čekanju" },
  checked_in: { color: "bg-blue-100 text-blue-800", label: "Prijavljena" },
  completed: { color: "bg-gray-100 text-gray-800", label: "Završena" },
  cancelled: { color: "bg-red-100 text-red-800", label: "Otkazana" },
  no_show: { color: "bg-orange-100 text-orange-800", label: "Nije došao" },
};

export const AREAS: Record<string, { label: string }> = {
  indoor: { label: "Sala" },
  outdoor: { label: "Bašta" },
  terrace: { label: "Terasa" },
  vip: { label: "VIP" },
  bar: { label: "Bar" },
};
