import type { Review } from "./types";

export const INITIAL_DATA: Review[] = [
  {
    id: "1",
    customerName: "Jelena Marković",
    customerEmail: "jelena@email.com",
    productName: "Bluetooth zvučnik JBL",
    productSku: "BTS-JBL01",
    category: "Audio",
    rating: 5,
    title: "Odličan zvučnik za tu cenu!",
    content:
      "Kvalitet zvuka je izvanredan, baterija traje 8+ sati. Bluetooth konekcija stabilna. Preporučujem svima!",
    status: "approved",
    source: "website",
    verified: true,
    helpful: 24,
    notHelpful: 2,
    createdAt: "2024-06-14",
    responseText:
      "Hvala Vam na prelepoj recenziji! Radujemo se što ste zadovoljni.",
    respondedAt: "2024-06-14",
    respondedBy: "Support tim",
  },
  {
    id: "2",
    customerName: "Stefan Ilić",
    customerEmail: "stefan@email.com",
    productName: "Tenisice Nike Air Max",
    productSku: "SHO-NAM90",
    category: "Obuća",
    rating: 4,
    title: "Udobne ali veličina malo veća",
    content:
      "Vrlo udobne patike za svakodnevno nošenje. Jedina primedba je da traju pola broja veće nego što piše na labeli.",
    status: "approved",
    source: "google",
    verified: true,
    helpful: 18,
    notHelpful: 3,
    createdAt: "2024-06-13",
    responseText: null,
    respondedAt: null,
    respondedBy: null,
  },
  {
    id: "3",
    customerName: "Ana Đorđević",
    customerEmail: "ana@email.com",
    productName: "Majica - crna (XL)",
    productSku: "TSH-BLK-XL",
    category: "Odeća",
    rating: 2,
    title: "Kvalitet nije ono što sam očekivala",
    content:
      "Majica je stigla ali je vrlo tanka i nakon jednog pranja se izvukla. Za ovu cenu sam očekivala bolji kvalitet.",
    status: "responded",
    source: "website",
    verified: true,
    helpful: 12,
    notHelpful: 8,
    createdAt: "2024-06-12",
    responseText:
      "Žao nam je zbog Vašeg iskustva. Kontaktirajte nas na support za mogućnost povrata ili zamene.",
    respondedAt: "2024-06-12",
    respondedBy: "Support tim",
  },
  {
    id: "4",
    customerName: "Petar Stanković",
    customerEmail: "petar@email.com",
    productName: "Drvena stolica Classic",
    productSku: "CHR-CLS01",
    category: "Nameštaj",
    rating: 1,
    title: "TOTALNO LOŠE - NE KUPUJTE",
    content:
      "Stolica je stigla POLOMLJENA! Nikakva zaštita u transportu. Pokušao sam da pozovem ali niko ne odgovara. JEDI GOVNA FIRMA!!!",
    status: "flagged",
    source: "website",
    verified: true,
    helpful: 5,
    notHelpful: 15,
    createdAt: "2024-06-15",
    responseText: null,
    respondedAt: null,
    respondedBy: null,
  },
  {
    id: "5",
    customerName: "Miroslav Jovanović",
    customerEmail: "miroslav@email.com",
    productName: "Bosch bušilica GSB 550",
    productSku: "DRL-BOS550",
    category: "Alati",
    rating: 5,
    title: "Profesionalna bušilica",
    content:
      "Koristim za građevinske radove svaki dan. Odlična snaga, ergonomski držak. Zaista profesionalan alat.",
    status: "pending",
    source: "email",
    verified: true,
    helpful: 8,
    notHelpful: 0,
    createdAt: "2024-06-15",
    responseText: null,
    respondedAt: null,
    respondedBy: null,
  },
  {
    id: "6",
    customerName: "Ljubica Perić",
    customerEmail: "ljubica@email.com",
    productName: "Keramičke šolje set",
    productSku: "CUP-SET6",
    category: "Kuhinjski",
    rating: 3,
    title: "Lep set ali slaba zaštita",
    content:
      "Šolje su prelepe i kvalitetne ali su 2 od 6 stigle polomljene. Zaštita u pakovanju bi trebalo da je bolja.",
    status: "approved",
    source: "social",
    verified: false,
    helpful: 6,
    notHelpful: 1,
    createdAt: "2024-06-11",
    responseText: null,
    respondedAt: null,
    respondedBy: null,
  },
  {
    id: "7",
    customerName: "Goran Đorđević",
    customerEmail: "goran@email.com",
    productName: 'LED monitor 27" 4K',
    productSku: "MON-4K27",
    category: "Monitori",
    rating: 4,
    title: "Sjajan monitor, samo malo IPS bleeding",
    content:
      "Slika je kristalno čista, boje tačne. Jedina mana je blago IPS bleeding u donjim uglovima koji se primećuje samo na potpuno crnoj pozadini.",
    status: "pending",
    source: "website",
    verified: true,
    helpful: 31,
    notHelpful: 4,
    createdAt: "2024-06-15",
    responseText: null,
    respondedAt: null,
    respondedBy: null,
  },
  {
    id: "8",
    customerName: "Nenad Milić",
    customerEmail: "nenad@email.com",
    productName: "Navlaka za auto sedišta",
    productSku: "AUT-COV01",
    category: "Auto",
    rating: 1,
    title: "Ne odgovara modelu",
    content:
      "Kupio sam za Golf 7 ali ne sedi dobro. Navlaka klizi i ne izgleda kao na slikama. Vraćam.",
    status: "rejected",
    source: "website",
    verified: false,
    helpful: 2,
    notHelpful: 3,
    createdAt: "2024-06-10",
    responseText: null,
    respondedAt: null,
    respondedBy: null,
  },
];

export const STATUSES: Record<string, { color: string; label: string }> = {
  pending: {
    color: "bg-slate-100 text-slate-800 dark:bg-slate-800 dark:text-slate-300",
    label: "Čeka odobrenje",
  },
  approved: {
    color:
      "bg-emerald-100 text-emerald-800 dark:bg-emerald-900 dark:text-emerald-300",
    label: "Odobrena",
  },
  rejected: {
    color: "bg-red-100 text-red-800 dark:bg-red-900 dark:text-red-300",
    label: "Odbijena",
  },
  flagged: {
    color: "bg-amber-100 text-amber-800 dark:bg-amber-900 dark:text-amber-300",
    label: "Označena",
  },
  responded: {
    color: "bg-blue-100 text-blue-800 dark:bg-blue-900 dark:text-blue-300",
    label: "Odgovorena",
  },
};

export const SOURCES: Record<string, { label: string }> = {
  website: { label: "Web sajt" },
  email: { label: "Email" },
  google: { label: "Google" },
  social: { label: "Društvene mreže" },
};
