'use client'

import { useCallback, useEffect, useState } from 'react'

import { Badge } from '@/components/ui/badge'
import { Button } from '@/components/ui/button'
import { Card, CardContent } from '@/components/ui/card'
import { Input } from '@/components/ui/input'
import { Label } from '@/components/ui/label'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'
import { Skeleton } from '@/components/ui/skeleton'
import { Switch } from '@/components/ui/switch'
import { AlertTriangle, Calendar, CheckCircle2, Clock, FileText, Pencil, Play, Plus, Repeat, Trash2, Zap } from 'lucide-react'
'use client'

import { useCallback, useEffect, useState } from 'react'

import type { Partner, Product, RecurringInvoice, LineItem } from './types'

function RecurringInvoicesContent() {
  const { t } = useTranslation()
  const [recurringInvoices, setRecurringInvoices] = useState<RecurringInvoice[]>([])
  const [partners, setPartners] = useState<Partner[]>([])
  const [products, setProducts] = useState<Product[]>([])
  const [loading, setLoading] = useState(true)
  const [dialogOpen, setDialogOpen] = useState(false)
  const [editing, setEditing] = useState<RecurringInvoice | null>(null)
  const [submitting, setSubmitting] = useState(false)
  const [generatingId, setGeneratingId] = useState<string | null>(null)

  // Form state
  const [formName, setFormName] = useState('')
  const [formPartnerId, setFormPartnerId] = useState('')
  const [formFrequency, setFormFrequency] = useState('monthly')
  const [formNextDate, setFormNextDate] = useState('')
  const [formStartDate, setFormStartDate] = useState('')
  const [formEndDate, setFormEndDate] = useState('')
  const [formNotes, setFormNotes] = useState('')
  const [formItems, setFormItems] = useState<LineItem[]>([
    { productId: '', productName: '', quantity: 1, unitPrice: 0, discountPct: 0, taxRate: 20 },
  ])

  const fetchData = useCallback(async () => {
    setLoading(true)
    try {
      const [recurringRes, partnersRes, productsRes] = await Promise.all([
        fetch('/api/recurring-invoices'),
        fetch('/api/partners'),
        fetch('/api/products'),
      ])
      const [recurringData, partnersData, productsData] = await Promise.all([
        recurringRes.json(),
        partnersRes.json(),
        productsRes.json(),
      ])
      setRecurringInvoices(recurringData || [])
      setPartners(partnersData || [])
      setProducts(productsData || [])
    } catch {
      // ignore
    } finally {
      setLoading(false)
    }
  }, [])

  useEffect(() => {
    fetchData()
  }, [fetchData])

  // Stats
  const stats = {
    totalActive: recurringInvoices.filter(r => r.isActive).length,
    dueThisMonth: recurringInvoices.filter(r => {
      if (!r.isActive) return false
      const d = new Date(r.nextDate)
      const now = new Date()
      return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear()
    }).length,
    totalAutoGenerated: recurringInvoices.reduce((sum, r) => sum + r._count.invoices, 0),
    overdueCount: recurringInvoices.filter(r => getStatus(r.nextDate, r.isActive) === 'overdue').length,
  }

  const resetForm = () => {
    setFormName('')
    setFormPartnerId('')
    setFormFrequency('monthly')
    setFormNextDate('')
    setFormStartDate('')
    setFormEndDate('')
    setFormNotes('')
    setFormItems([{ productId: '', productName: '', quantity: 1, unitPrice: 0, discountPct: 0, taxRate: 20 }])
    setEditing(null)
  }

  const handleOpenNew = () => {
    resetForm()
    // Set default dates
    const today = new Date()
    const nextMonth = new Date(today)
    nextMonth.setMonth(nextMonth.getMonth() + 1)
    setFormStartDate(today.toISOString().split('T')[0])
    setFormNextDate(nextMonth.toISOString().split('T')[0])
    setDialogOpen(true)
  }

  const handleOpenEdit = (item: RecurringInvoice) => {
    setEditing(item)
    setFormName(item.name)
    setFormPartnerId(item.partnerId)
    setFormFrequency(item.frequency)
    setFormNextDate(new Date(item.nextDate).toISOString().split('T')[0])
    setFormStartDate(new Date(item.startDate).toISOString().split('T')[0])
    setFormEndDate(item.endDate ? new Date(item.endDate).toISOString().split('T')[0] : '')
    setFormNotes(item.notes || '')
    try {
      const parsed = JSON.parse(item.items)
      if (Array.isArray(parsed)) setFormItems(parsed)
    } catch {
      setFormItems([{ productId: '', productName: '', quantity: 1, unitPrice: 0, discountPct: 0, taxRate: 20 }])
    }
    setDialogOpen(true)
  }

  const handleSubmit = async () => {
    if (!formName || !formPartnerId || !formNextDate || !formStartDate) {
      toast.error(t('common.required'))
      return
    }

    setSubmitting(true)
    try {
      const body = {
        name: formName,
        partnerId: formPartnerId,
        frequency: formFrequency,
        nextDate: formNextDate,
        startDate: formStartDate,
        endDate: formEndDate || null,
        items: formItems.filter(i => i.productName),
        notes: formNotes || null,
      }

      const url = editing ? `/api/recurring-invoices/${editing.id}` : '/api/recurring-invoices'
      const method = editing ? 'PUT' : 'POST'

      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      })

      if (!res.ok) {
        const err = await res.json()
        toast.error(err.error || t('common.error'))
        return
      }

      toast.success(editing ? t('recurring.updatedSuccess') : t('recurring.createdSuccess'))
      setDialogOpen(false)
      resetForm()
      fetchData()
    } catch {
      toast.error(t('common.error'))
    } finally {
      setSubmitting(false)
    }
  }

  const handleToggleActive = async (item: RecurringInvoice) => {
    try {
      const res = await fetch(`/api/recurring-invoices/${item.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ isActive: !item.isActive }),
      })
      if (!res.ok) throw new Error()
      toast.success(item.isActive ? t('recurring.pausedSuccess') : t('recurring.activatedSuccess'))
      fetchData()
    } catch {
      toast.error(t('common.error'))
    }
  }

  const handleDelete = async (item: RecurringInvoice) => {
    if (!confirm(t('common.deleteConfirm'))) return
    try {
      const res = await fetch(`/api/recurring-invoices/${item.id}`, { method: 'DELETE' })
      if (!res.ok) throw new Error()
      toast.success(t('common.deleteSuccess'))
      fetchData()
    } catch {
      toast.error(t('common.error'))
    }
  }

  const handleGenerateNow = async (id: string) => {
    setGeneratingId(id)
    try {
      const res = await fetch(`/api/recurring-invoices/${id}/generate`, { method: 'POST' })
      if (!res.ok) {
        const err = await res.json()
        toast.error(err.error || t('common.error'))
        return
      }
      const data = await res.json()
      toast.success(t('recurring.generateSuccess'))
      if (data.deactivated) {
        toast.info(t('recurring.deactivatedInfo'))
      }
      fetchData()
    } catch {
      toast.error(t('common.error'))
    } finally {
      setGeneratingId(null)
    }
  }

  const addFormItem = () => {
    setFormItems([...formItems, { productId: '', productName: '', quantity: 1, unitPrice: 0, discountPct: 0, taxRate: 20 }])
  }

  const removeFormItem = (index: number) => {
    if (formItems.length > 1) {
      setFormItems(formItems.filter((_, i) => i !== index))
    }
  }

  const updateFormItem = (index: number, field: keyof LineItem, value: string | number) => {
    const updated = [...formItems]
    updated[index] = { ...updated[index], [field]: value }
    if (field === 'productId') {
      const product = products.find(p => p.id === value)
      if (product) {
        updated[index].productName = product.name
        updated[index].unitPrice = product.sellingPrice
      }
    }
    setFormItems(updated)
  }

  const grandTotal = formItems.reduce((sum, item) => sum + calcItemTotal(item), 0)

  // ==================== RENDER ====================

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between">
        <div>
          <h2 className="text-lg font-semibold flex items-center gap-2">
            <Repeat className="h-5 w-5 text-primary" />
            {t('recurring.title')}
          </h2>
          <p className="text-sm text-muted-foreground mt-0.5">{t('recurring.subtitle')}</p>
        </div>
        <Button size="sm" className="gap-2" onClick={handleOpenNew}>
          <Plus className="h-4 w-4" /> {t('recurring.new')}
        </Button>
      </div>

      {/* Stats Cards */}
      <div className="grid grid-cols-2 gap-3 sm:grid-cols-4">
        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0 }}>
          <Card className="p-4">
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-lg bg-emerald-50 flex items-center justify-center">
                <CheckCircle2 className="h-5 w-5 text-emerald-600" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats.totalActive}</p>
                <p className="text-xs text-muted-foreground">{t('recurring.statActive')}</p>
              </div>
            </div>
          </Card>
        </motion.div>

        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.05 }}>
          <Card className="p-4">
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-lg bg-amber-50 flex items-center justify-center">
                <Clock className="h-5 w-5 text-amber-600" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats.dueThisMonth}</p>
                <p className="text-xs text-muted-foreground">{t('recurring.statDueMonth')}</p>
              </div>
            </div>
          </Card>
        </motion.div>

        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.1 }}>
          <Card className="p-4">
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-lg bg-violet-50 flex items-center justify-center">
                <FileText className="h-5 w-5 text-violet-600" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats.totalAutoGenerated}</p>
                <p className="text-xs text-muted-foreground">{t('recurring.statTotalGenerated')}</p>
              </div>
            </div>
          </Card>
        </motion.div>

        <motion.div initial={{ opacity: 0, y: 10 }} animate={{ opacity: 1, y: 0 }} transition={{ delay: 0.15 }}>
          <Card className="p-4">
            <div className="flex items-center gap-3">
              <div className="h-10 w-10 rounded-lg bg-red-50 flex items-center justify-center">
                <AlertTriangle className="h-5 w-5 text-red-600" />
              </div>
              <div>
                <p className="text-2xl font-bold">{stats.overdueCount}</p>
                <p className="text-xs text-muted-foreground">{t('recurring.statOverdue')}</p>
              </div>
            </div>
          </Card>
        </motion.div>
      </div>

      {/* List */}
      {loading ? (
        <div className="space-y-3">
          {Array.from({ length: 3 }).map((_, i) => (
            <Skeleton key={i} className="h-28 w-full" />
          ))}
        </div>
      ) : recurringInvoices.length === 0 ? (
        <Card className="p-8 text-center">
          <Repeat className="h-12 w-12 mx-auto text-muted-foreground/30 mb-3" />
          <p className="text-muted-foreground">{t('recurring.noRecurring')}</p>
          <Button variant="outline" size="sm" className="mt-3 gap-2" onClick={handleOpenNew}>
            <Plus className="h-4 w-4" /> {t('recurring.new')}
          </Button>
        </Card>
      ) : (
        <div className="grid gap-3 sm:grid-cols-2">
          <AnimatePresence mode="popLayout">
            {recurringInvoices.map((item) => {
              const status = getStatus(item.nextDate, item.isActive)
              const statusConfig = getStatusConfig(status, t)
              const StatusIcon = statusConfig.icon
              const days = item.isActive ? daysUntil(item.nextDate) : null

              return (
                <motion.div
                  key={item.id}
                  initial={{ opacity: 0, scale: 0.95 }}
                  animate={{ opacity: 1, scale: 1 }}
                  exit={{ opacity: 0, scale: 0.95 }}
                  transition={{ duration: 0.2 }}
                  layout
                >
                  <Card className="overflow-hidden border-l-4 transition-shadow hover:shadow-md"
                    style={{ borderLeftColor: status === 'overdue' ? '#ef4444' : status === 'dueToday' ? '#f59e0b' : status === 'active' ? '#10b981' : '#94a3b8' }}
                  >
                    <CardContent className="p-4">
                      {/* Top row: Name + Status */}
                      <div className="flex items-start justify-between gap-2 mb-3">
                        <div className="flex-1 min-w-0">
                          <h3 className="font-semibold text-sm truncate">{item.name}</h3>
                          <p className="text-xs text-muted-foreground mt-0.5 truncate">
                            {item.partner?.name}
                          </p>
                        </div>
                        <Badge variant="outline" className={`text-xs px-2 py-0 shrink-0 ${statusConfig.color}`}>
                          <StatusIcon className="h-3 w-3 mr-1" />
                          {statusConfig.label}
                        </Badge>
                      </div>

                      {/* Middle row: Info */}
                      <div className="flex flex-wrap items-center gap-2 mb-3">
                        <Badge variant="outline" className={`text-xs px-2 py-0 ${getFrequencyBadgeClass(item.frequency)}`}>
                          {getFrequencyIcon(item.frequency)} {getFrequencyLabel(item.frequency, t)}
                        </Badge>
                        <div className="flex items-center gap-1 text-xs text-muted-foreground">
                          <Calendar className="h-3 w-3" />
                          <span>{formatDate(item.nextDate)}</span>
                        </div>
                        {days !== null && days >= 0 && days <= 30 && (
                          <span className="text-xs text-muted-foreground">
                            ({days === 0 ? t('recurring.today') : `${days}d`})
                          </span>
                        )}
                      </div>

                      {/* Bottom info */}
                      <div className="flex items-center justify-between text-xs text-muted-foreground mb-3">
                        <span>
                          {t('recurring.lastGenerated')}: {item.lastGenerated ? formatDate(item.lastGenerated) : '—'}
                        </span>
                        <span>
                          {t('recurring.invoicesCount')}: {item._count.invoices}
                        </span>
                      </div>

                      {/* Actions */}
                      <div className="flex items-center gap-2 pt-2 border-t">
                        <div className="flex items-center gap-2 mr-auto">
                          <Label htmlFor={`toggle-${item.id}`} className="sr-only">
                            {item.isActive ? t('recurring.pause') : t('recurring.resume')}
                          </Label>
                          <Switch
                            id={`toggle-${item.id}`}
                            checked={item.isActive}
                            onCheckedChange={() => handleToggleActive(item)}
                          />
                        </div>
                        {item.isActive && (
                          <Button
                            size="sm"
                            variant="outline"
                            className="h-7 gap-1 text-xs"
                            onClick={() => handleGenerateNow(item.id)}
                            disabled={generatingId === item.id}
                          >
                            {generatingId === item.id ? (
                              <motion.div
                                animate={{ rotate: 360 }}
                                transition={{ repeat: Infinity, duration: 1, ease: 'linear' }}
                              >
                                <Zap className="h-3 w-3" />
                              </motion.div>
                            ) : (
                              <Play className="h-3 w-3" />
                            )}
                            {t('recurring.generateNow')}
                          </Button>
                        )}
                        <Button size="sm" variant="ghost" className="h-7 w-7 p-0" onClick={() => handleOpenEdit(item)}>
                          <Pencil className="h-3.5 w-3.5" />
                        </Button>
                        <Button size="sm" variant="ghost" className="h-7 w-7 p-0 text-destructive hover:text-destructive" onClick={() => handleDelete(item)}>
                          <Trash2 className="h-3.5 w-3.5" />
                        </Button>
                      </div>
                    </CardContent>
                  </Card>
                </motion.div>
              )
            })}
          </AnimatePresence>
        </div>
      )}

    </div>
  )
}
