export const now = new Date();

export const next = new Date(nextDate);

export const today = new Date(now.getFullYear(), now.getMonth(), now.getDate());

export const nextDay = new Date(next.getFullYear(), next.getMonth(), next.getDate());

export const configs: Record<string, { label: string; color: string; icon: typeof CheckCircle2; dotClass: string }> = {
    active: {
      label: t('recurring.active'),
      color: 'bg-emerald-50 text-emerald-700 border-emerald-200',
      icon: CheckCircle2,
      dotClass: 'bg-emerald-500',
    },
    dueToday: {
      label: t('recurring.dueToday'),
      color: 'bg-amber-50 text-amber-700 border-amber-200',
      icon: AlertTriangle,
      dotClass: 'bg-amber-500',
    },
    overdue: {
      label: t('recurring.overdue'),
      color: 'bg-red-50 text-red-700 border-red-200',
      icon: AlertTriangle,
      dotClass: 'bg-red-500',
    },
    paused: {
      label: t('recurring.paused'),
      color: 'bg-slate-50 text-slate-500 border-slate-200',
      icon: Pause,
      dotClass: 'bg-slate-400',
    },
  }

export const labels: Record<string, string> = {
    weekly: t('recurring.weekly'),
    monthly: t('recurring.monthly'),
    quarterly: t('recurring.quarterly'),
    yearly: t('recurring.yearly'),
  }

export const subtotal = item.quantity * item.unitPrice;

export const discount = subtotal * (item.discountPct / 100);

export const base = subtotal - discount;

export const tax = base * (item.taxRate / 100);

export const now = new Date();

export const target = new Date(dateStr);

export const diff = target.getTime() - now.getTime();

export const { t } = useTranslation();

export const { t } = useTranslation();

export const [recurringRes, partnersRes, productsRes] = await Promise.all([
        fetch('/api/recurring-invoices'),
        fetch('/api/partners'),
        fetch('/api/products'),
      ]);

export const [recurringData, partnersData, productsData] = await Promise.all([
        recurringRes.json(),
        partnersRes.json(),
        productsRes.json(),
      ]);

export const stats = {
    totalActive: recurringInvoices.filter(r => r.isActive).length,
    dueThisMonth: recurringInvoices.filter(r => {
      if (!r.isActive) return false
      const d = new Date(r.nextDate)
      const now = new Date()
      return d.getMonth() === now.getMonth() && d.getFullYear() === now.getFullYear()
    }).length,
    totalAutoGenerated: recurringInvoices.reduce((sum, r) => sum + r._count.invoices, 0),
    overdueCount: recurringInvoices.filter(r => getStatus(r.nextDate, r.isActive) === 'overdue').length,
  }

export const resetForm = () => {
    setFormName('')
    setFormPartnerId('')
    setFormFrequency('monthly')
    setFormNextDate('')
    setFormStartDate('')
    setFormEndDate('')
    setFormNotes('')
    setFormItems([{ productId: '', productName: '', quantity: 1, unitPrice: 0, discountPct: 0, taxRate: 20 }])
    setEditing(null)
  }

export const handleOpenNew = () => {
    resetForm()
    // Set default dates
    const today = new Date()
    const nextMonth = new Date(today)
    nextMonth.setMonth(nextMonth.getMonth() + 1)
    setFormStartDate(today.toISOString().split('T')[0])
    setFormNextDate(nextMonth.toISOString().split('T')[0])
    setDialogOpen(true)
  }

export const handleOpenEdit = (item: RecurringInvoice) => {
    setEditing(item)
    setFormName(item.name)
    setFormPartnerId(item.partnerId)
    setFormFrequency(item.frequency)
    setFormNextDate(new Date(item.nextDate).toISOString().split('T')[0])
    setFormStartDate(new Date(item.startDate).toISOString().split('T')[0])
    setFormEndDate(item.endDate ? new Date(item.endDate).toISOString().split('T')[0] : '')
    setFormNotes(item.notes || '')
    try {
      const parsed = JSON.parse(item.items)
      if (Array.isArray(parsed)) setFormItems(parsed)
    } catch {
      setFormItems([{ productId: '', productName: '', quantity: 1, unitPrice: 0, discountPct: 0, taxRate: 20 }])
    }
    setDialogOpen(true)
  }

export const handleSubmit = async () => {
    if (!formName || !formPartnerId || !formNextDate || !formStartDate) {
      toast.error(t('common.required'))
      return
    }

    setSubmitting(true)
    try {
      const body = {
        name: formName,
        partnerId: formPartnerId,
        frequency: formFrequency,
        nextDate: formNextDate,
        startDate: formStartDate,
        endDate: formEndDate || null,
        items: formItems.filter(i => i.productName),
        notes: formNotes || null,
      }

      const url = editing ? `/api/recurring-invoices/${editing.id}` : '/api/recurring-invoices'
      const method = editing ? 'PUT' : 'POST'

      const res = await fetch(url, {
        method,
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify(body),
      })

      if (!res.ok) {
        const err = await res.json()
        toast.error(err.error || t('common.error'))
        return
      }

      toast.success(editing ? t('recurring.updatedSuccess') : t('recurring.createdSuccess'))
      setDialogOpen(false)
      resetForm()
      fetchData()
    } catch {
      toast.error(t('common.error'))
    } finally {
      setSubmitting(false)
    }
  }

export const handleToggleActive = async (item: RecurringInvoice) => {
    try {
      const res = await fetch(`/api/recurring-invoices/${item.id}`, {
        method: 'PUT',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({ isActive: !item.isActive }),
      })
      if (!res.ok) throw new Error()
      toast.success(item.isActive ? t('recurring.pausedSuccess') : t('recurring.activatedSuccess'))
      fetchData()
    } catch {
      toast.error(t('common.error'))
    }
  }

export const handleDelete = async (item: RecurringInvoice) => {
    if (!confirm(t('common.deleteConfirm'))) return
    try {
      const res = await fetch(`/api/recurring-invoices/${item.id}`, { method: 'DELETE' })
      if (!res.ok) throw new Error()
      toast.success(t('common.deleteSuccess'))
      fetchData()
    } catch {
      toast.error(t('common.error'))
    }
  }

export const handleGenerateNow = async (id: string) => {
    setGeneratingId(id)
    try {
      const res = await fetch(`/api/recurring-invoices/${id}/generate`, { method: 'POST' })
      if (!res.ok) {
        const err = await res.json()
        toast.error(err.error || t('common.error'))
        return
      }
      const data = await res.json()
      toast.success(t('recurring.generateSuccess'))
      if (data.deactivated) {
        toast.info(t('recurring.deactivatedInfo'))
      }
      fetchData()
    } catch {
      toast.error(t('common.error'))
    } finally {
      setGeneratingId(null)
    }
  }

export const addFormItem = () => {
    setFormItems([...formItems, { productId: '', productName: '', quantity: 1, unitPrice: 0, discountPct: 0, taxRate: 20 }])
  }

export const removeFormItem = (index: number) => {
    if (formItems.length > 1) {
      setFormItems(formItems.filter((_, i) => i !== index))
    }
  }

export const updateFormItem = (index: number, field: keyof LineItem, value: string | number) => {
    const updated = [...formItems]
    updated[index] = { ...updated[index], [field]: value }
    if (field === 'productId') {
      const product = products.find(p => p.id === value)
      if (product) {
        updated[index].productName = product.name
        updated[index].unitPrice = product.sellingPrice
      }
    }
    setFormItems(updated)
  }

export const grandTotal = formItems.reduce((sum, item) => sum + calcItemTotal(item), 0);

export const status = getStatus(item.nextDate, item.isActive);

export const statusConfig = getStatusConfig(status, t);

export const StatusIcon = statusConfig.icon;

export const days = item.isActive ? daysUntil(item.nextDate) : null;

export const start = new Date(formStartDate);

export const next = new Date(start);

export function getStatus(nextDate: string, isActive: boolean) {
  if (!isActive) return 'paused'
  const now = new Date()
  const next = new Date(nextDate)
  const today = new Date(now.getFullYear(), now.getMonth(), now.getDate())
  const nextDay = new Date(next.getFullYear(), next.getMonth(), next.getDate())

  if (nextDay < today) return 'overdue'
  if (nextDay.getTime() === today.getTime()) return 'dueToday'
  return 'active'
}

export function getStatusConfig(status: string, t: (key: string) => string) {
  const configs: Record<string, { label: string; color: string; icon: typeof CheckCircle2; dotClass: string }> = {
    active: {
      label: t('recurring.active'),
      color: 'bg-emerald-50 text-emerald-700 border-emerald-200',
      icon: CheckCircle2,
      dotClass: 'bg-emerald-500',
    },
    dueToday: {
      label: t('recurring.dueToday'),
      color: 'bg-amber-50 text-amber-700 border-amber-200',
      icon: AlertTriangle,
      dotClass: 'bg-amber-500',
    },
    overdue: {
      label: t('recurring.overdue'),
      color: 'bg-red-50 text-red-700 border-red-200',
      icon: AlertTriangle,
      dotClass: 'bg-red-500',
    },
    paused: {
      label: t('recurring.paused'),
      color: 'bg-slate-50 text-slate-500 border-slate-200',
      icon: Pause,
      dotClass: 'bg-slate-400',
    },
  }
  return configs[status] || configs.active
}

export function getFrequencyLabel(freq: string, t: (key: string) => string) {
  const labels: Record<string, string> = {
    weekly: t('recurring.weekly'),
    monthly: t('recurring.monthly'),
    quarterly: t('recurring.quarterly'),
    yearly: t('recurring.yearly'),
  }
  return labels[freq] || freq
}

export function getFrequencyIcon(freq: string) {
  switch (freq) {
    case 'weekly': return '📅'
    case 'monthly': return '🗓️'
    case 'quarterly': return '📆'
    case 'yearly': return '📋'
    default: return '🔄'
  }
}

export function getFrequencyBadgeClass(freq: string) {
  switch (freq) {
    case 'weekly': return 'bg-blue-50 text-blue-700 border-blue-200'
    case 'monthly': return 'bg-violet-50 text-violet-700 border-violet-200'
    case 'quarterly': return 'bg-orange-50 text-orange-700 border-orange-200'
    case 'yearly': return 'bg-teal-50 text-teal-700 border-teal-200'
    default: return 'bg-slate-50 text-slate-600 border-slate-200'
  }
}

export function calcItemTotal(item: LineItem) {
  const subtotal = item.quantity * item.unitPrice
  const discount = subtotal * (item.discountPct / 100)
  const base = subtotal - discount
  const tax = base * (item.taxRate / 100)
  return base + tax
}

export function daysUntil(dateStr: string): number {
  const now = new Date()
  const target = new Date(dateStr)
  const diff = target.getTime() - now.getTime()
  return Math.ceil(diff / (1000 * 60 * 60 * 24))
}
