'use client'
import { useState, useEffect, useCallback } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Badge } from '@/components/ui/badge'; import { Skeleton } from '@/components/ui/skeleton'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'; import { Label } from '@/components/ui/label'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Plus, Search, Trash2, Pencil, Eye, Tag, Printer, ArrowLeft, X } from 'lucide-react'; import { toast } from 'sonner'; import { formatDate } from '@/lib/helpers'

type LabelItem = { id: string; labelNo: string; name: string; sku: string; category: string; status: string; size: string; material: string; color: string; quantity: number; costPerUnit: number; printDate: string; notes: string }
const CATEGORIES: Record<string, string> = { product: 'Proizvod', shipping: 'Transport', promotion: 'Promocija', barcode: 'Barkod', qr: 'QR kod', price: 'Cena', warning: 'Upozorenje', ingredient: 'Sastojci' }
const STATUSES: Record<string, { color: string; label: string }> = { active: { color: 'bg-emerald-100 text-emerald-800', label: 'Aktivna' }, inactive: { color: 'bg-gray-100 text-gray-800', label: 'Neaktivna' } }
function getStatusBadge(s: string) { const r = STATUSES[s]; return r ? <Badge className={`${r.color} text-xs`}>{r.label}</Badge> : <Badge className="text-xs">{s}</Badge> }

export function Labels() {
  const [data, setData] = useState<LabelItem[]>([]); const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState(''); const [catFilter, setCatFilter] = useState('')
  const [editItem, setEditItem] = useState<LabelItem | null>(null)
  const [detailId, setDetailId] = useState<string | null>(null); const [form, setForm] = useState<Partial<LabelItem>>({}); const [activeTab, setActiveTab] = useState('pregled')

  const fetchData = useCallback(async () => {
    try {
      setLoading(true)
      const params = new URLSearchParams()
      if (search) params.set('search', search)
      if (catFilter) params.set('category', catFilter)
      const res = await fetch(`/api/labels?${params}`)
      if (!res.ok) throw new Error()
      const json = await res.json()
      setData(json)
    } catch { toast.error('Greška pri učitavanju') } finally { setLoading(false) }
  }, [search, catFilter])

  useEffect(() => { fetchData() }, [fetchData])

  const filtered = data
  const handleDelete = async (id: string) => { if (!confirm('Obrisati?')) return; try { const res = await fetch(`/api/labels/${id}`, { method: 'DELETE' }); if (!res.ok) throw new Error(); toast.success('Obrisano'); fetchData() } catch { toast.error('Greška pri brisanju') } }
  const handleNew = () => { setEditItem(null); setForm({ name: '', sku: '', category: 'product', status: 'active', size: '', material: 'Samolepljiva', color: 'Bela', quantity: 1000, costPerUnit: 1, printDate: new Date().toISOString().split('T')[0], notes: '' }); setActiveTab('dodaj') }
  const handleEdit = (item: LabelItem) => { setEditItem(item); setForm({ ...item }); setActiveTab('uredi') }
  const handleSave = async () => { if (!form.name) { toast.error('Unesite naziv'); return }; try { const url = editItem ? `/api/labels/${editItem.id}` : '/api/labels'; const res = await fetch(url, { method: editItem ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!res.ok) throw new Error(); toast.success(editItem ? 'Ažurirano' : 'Kreirano'); if (!editItem) { setForm({ name: '', sku: '', category: 'product', status: 'active', size: '', material: 'Samolepljiva', color: 'Bela', quantity: 1000, costPerUnit: 1, printDate: new Date().toISOString().split('T')[0], notes: '' }) } else { setEditItem(null) }; fetchData() } catch { toast.error('Greška pri čuvanju') } }
  const handleCancelEdit = () => { setEditItem(null); setActiveTab('pregled') }
  if (loading) return <div className="space-y-4"><Skeleton className="h-8 w-64" /><Skeleton className="h-64" /></div>
  const detailItem = detailId ? data.find(i => i.id === detailId) : null

  return (<div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight">Etikete</h1><p className="text-sm text-muted-foreground">Upravljanje etiketama, barkodovima i oznakama</p></div><Button size="sm" className="gap-2" onClick={handleNew}><Plus className="h-4 w-4" />Nova etiketa</Button></div>
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3"><Card className="p-4"><div className="text-xs text-muted-foreground mb-1 flex items-center gap-1"><Tag className="h-3 w-3" />Ukupno</div><p className="text-2xl font-bold">{data.length}</p></Card><Card className="p-4"><div className="text-xs text-emerald-600 mb-1">Aktivnih</div><p className="text-2xl font-bold text-emerald-700">{data.filter(i => i.status === 'active').length}</p></Card><Card className="p-4"><div className="text-xs text-muted-foreground mb-1">Ukupno komada</div><p className="text-2xl font-bold">{data.reduce((s, i) => s + i.quantity, 0).toLocaleString()}</p></Card><Card className="p-4"><div className="text-xs text-muted-foreground mb-1">Ukupna cena</div><p className="text-lg font-bold">{new Intl.NumberFormat('sr-RS', { style: 'currency', currency: 'RSD', maximumFractionDigits: 0 }).format(data.reduce((s, i) => s + i.quantity * i.costPerUnit, 0))}</p></Card></div>
    <Tabs value={activeTab} onValueChange={v => { setActiveTab(v); if (v !== 'uredi') setEditItem(null) }}><TabsList><TabsTrigger value="pregled">Pregled</TabsTrigger><TabsTrigger value="dodaj">Dodaj</TabsTrigger><TabsTrigger value="uredi">Uredi</TabsTrigger></TabsList>
      <TabsContent value="pregled" className="mt-4"><Card><CardHeader className="pb-3"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><CardTitle className="text-base">Lista etiketa</CardTitle><div className="flex gap-2 items-center"><div className="relative"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground" /><Input placeholder="Pretraga..." className="pl-8 h-8 w-44 text-xs" value={search} onChange={e => setSearch(e.target.value)} /></div><Select value={catFilter || 'all'} onValueChange={v => setCatFilter(v === 'all' ? '' : v)}><SelectTrigger className="w-28 h-8 text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Sve</SelectItem><SelectItem value="product">Proizvod</SelectItem><SelectItem value="shipping">Transport</SelectItem><SelectItem value="promotion">Promocija</SelectItem><SelectItem value="barcode">Barkod</SelectItem><SelectItem value="qr">QR kod</SelectItem></SelectContent></Select></div></div></CardHeader><CardContent><div className="max-h-[480px] overflow-y-auto"><Table><TableHeader><TableRow><TableHead className="text-xs">Naziv</TableHead><TableHead className="text-xs hidden sm:table-cell">SKU</TableHead><TableHead className="text-xs hidden md:table-cell">Kategorija</TableHead><TableHead className="text-xs hidden md:table-cell">Količina</TableHead><TableHead className="text-xs hidden lg:table-cell">Dimenzije</TableHead><TableHead className="text-xs">Status</TableHead><TableHead className="text-xs text-right">Akcije</TableHead></TableRow></TableHeader><TableBody>{filtered.length === 0 ? <TableRow><TableCell colSpan={7} className="text-center py-8 text-muted-foreground text-sm">Nema</TableCell></TableRow> : filtered.map(item => (<TableRow key={item.id}><TableCell className="text-xs font-medium">{item.name}</TableCell><TableCell className="text-xs font-mono text-muted-foreground hidden sm:table-cell">{item.sku}</TableCell><TableCell className="text-xs hidden md:table-cell">{CATEGORIES[item.category]}</TableCell><TableCell className="text-xs hidden md:table-cell">{item.quantity.toLocaleString()}</TableCell><TableCell className="text-xs text-muted-foreground hidden lg:table-cell">{item.size} — {item.material}</TableCell><TableCell>{getStatusBadge(item.status)}</TableCell><TableCell className="text-right"><div className="flex items-center justify-end gap-1"><Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setDetailId(item.id)}><Eye className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => handleEdit(item)}><Pencil className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7 text-red-500" onClick={() => handleDelete(item.id)}><Trash2 className="h-3.5 w-3.5" /></Button></div></TableCell></TableRow>))}</TableBody></Table></div></CardContent></Card></TabsContent>
      <TabsContent value="dodaj" className="mt-4"><Card><CardHeader><CardTitle className="text-base">Nova etiketa</CardTitle></CardHeader><CardContent><div className="grid gap-4"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="grid gap-2"><Label className="text-xs">Naziv *</Label><Input className="text-xs" value={form.name || ''} onChange={e => setForm({ ...form, name: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Kategorija</Label><Select value={form.category || 'product'} onValueChange={v => setForm({ ...form, category: v })}><SelectTrigger className="text-xs"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(CATEGORIES).map(([k, v]) => <SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label className="text-xs">Dimenzije</Label><Input className="text-xs" value={form.size || ''} onChange={e => setForm({ ...form, size: e.target.value })} placeholder="80x50mm" /></div><div className="grid gap-2"><Label className="text-xs">Količina</Label><Input className="text-xs" type="number" value={form.quantity || ''} onChange={e => setForm({ ...form, quantity: Number(e.target.value) })} /></div><div className="grid gap-2"><Label className="text-xs">Cena/kom (RSD)</Label><Input className="text-xs" type="number" step="0.01" value={form.costPerUnit || ''} onChange={e => setForm({ ...form, costPerUnit: Number(e.target.value) })} /></div><div className="grid gap-2"><Label className="text-xs">Materijal</Label><Input className="text-xs" value={form.material || ''} onChange={e => setForm({ ...form, material: e.target.value })} /></div></div><div className="flex gap-2"><Button size="sm" className="gap-2" onClick={handleSave}><Plus className="h-4 w-4" />Dodaj</Button><Button size="sm" variant="outline" onClick={() => { setForm({ name: '', sku: '', category: 'product', status: 'active', size: '', material: 'Samolepljiva', color: 'Bela', quantity: 1000, costPerUnit: 1, printDate: new Date().toISOString().split('T')[0], notes: '' }) }}>Poništi</Button></div></div></CardContent></Card></TabsContent>
      <TabsContent value="uredi" className="mt-4">
        {editItem ? (
          <Card><CardHeader><CardTitle className="text-base flex items-center gap-2"><Button variant="ghost" size="icon" className="h-7 w-7" onClick={handleCancelEdit}><ArrowLeft className="h-4 w-4" /></Button>Uredi: {editItem.name}</CardTitle></CardHeader><CardContent><div className="grid gap-4"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="grid gap-2"><Label className="text-xs">Naziv *</Label><Input className="text-xs" value={form.name || ''} onChange={e => setForm({ ...form, name: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Kategorija</Label><Select value={form.category || 'product'} onValueChange={v => setForm({ ...form, category: v })}><SelectTrigger className="text-xs"><SelectValue /></SelectTrigger><SelectContent>{Object.entries(CATEGORIES).map(([k, v]) => <SelectItem key={k} value={k}>{v}</SelectItem>)}</SelectContent></Select></div><div className="grid gap-2"><Label className="text-xs">Status</Label><Select value={form.status || 'active'} onValueChange={v => setForm({ ...form, status: v })}><SelectTrigger className="text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="active">Aktivna</SelectItem><SelectItem value="inactive">Neaktivna</SelectItem></SelectContent></Select></div><div className="grid gap-2"><Label className="text-xs">Dimenzije</Label><Input className="text-xs" value={form.size || ''} onChange={e => setForm({ ...form, size: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Količina</Label><Input className="text-xs" type="number" value={form.quantity || ''} onChange={e => setForm({ ...form, quantity: Number(e.target.value) })} /></div><div className="grid gap-2"><Label className="text-xs">Cena/kom (RSD)</Label><Input className="text-xs" type="number" step="0.01" value={form.costPerUnit || ''} onChange={e => setForm({ ...form, costPerUnit: Number(e.target.value) })} /></div><div className="grid gap-2"><Label className="text-xs">Materijal</Label><Input className="text-xs" value={form.material || ''} onChange={e => setForm({ ...form, material: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Boja</Label><Input className="text-xs" value={form.color || ''} onChange={e => setForm({ ...form, color: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Napomene</Label><Input className="text-xs" value={form.notes || ''} onChange={e => setForm({ ...form, notes: e.target.value })} /></div></div><div className="flex gap-2"><Button size="sm" onClick={handleSave}>Sačuvaj</Button><Button size="sm" variant="outline" onClick={handleCancelEdit}>Otkaži</Button></div></div></CardContent></Card>
        ) : (
          <Card><CardHeader><CardTitle className="text-base">Lista za uređivanje</CardTitle></CardHeader><CardContent><div className="max-h-[500px] overflow-y-auto space-y-3">{data.map(item => (<div key={item.id} className="flex items-center gap-3 p-3 border rounded-lg"><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><span className="text-xs font-medium">{item.name}</span>{getStatusBadge(item.status)}<Badge className="text-xs bg-muted">{CATEGORIES[item.category]}</Badge></div><p className="text-xs text-muted-foreground truncate">{item.quantity} kom — {item.size}</p></div><Button variant="ghost" size="icon" className="h-7 w-7 shrink-0" onClick={() => handleEdit(item)}><Pencil className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7 text-red-500 shrink-0" onClick={() => handleDelete(item.id)}><Trash2 className="h-3.5 w-3.5" /></Button></div>))}</div></CardContent></Card>
        )}
      </TabsContent>
    </Tabs>
    {!!detailId && (<Card className="sm:max-w-[500px]"><CardHeader><CardTitle className="flex items-center gap-2"><Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setDetailId(null)}><ArrowLeft className="h-4 w-4" /></Button>Detalji</CardTitle></CardHeader><CardContent>{detailItem && (<div className="space-y-3"><h3 className="text-sm font-semibold">{detailItem.name}</h3><div className="grid grid-cols-2 gap-3">{[['SKU', detailItem.sku],['Kategorija', CATEGORIES[detailItem.category]],['Dimenzije', detailItem.size],['Materijal', detailItem.material],['Boja', detailItem.color],['Količina', detailItem.quantity.toLocaleString()],['Cena/kom', `${detailItem.costPerUnit} RSD`],['Ukupno', `${(detailItem.quantity * detailItem.costPerUnit).toLocaleString()} RSD`],['Štampa', formatDate(detailItem.printDate)]].map(([l, v]) => (<div key={l} className="p-2 rounded-lg bg-muted/50"><div className="text-xs text-muted-foreground">{l}</div><div className="text-xs font-medium">{v}</div></div>))}</div><div className="p-2 rounded-lg bg-muted/50"><div className="text-xs text-muted-foreground mb-1">Status</div>{getStatusBadge(detailItem.status)}</div></div>)}</CardContent></Card>)}
  </div>)
}
