import type { Property } from './types'

export const INITIAL: Property[] = [
  { id: '1', propertyNo: 'NEK-001', title: 'Trosoban stan — Vračar', type: 'apartment', transactionType: 'sale', status: 'available', address: 'Nebojšina 45/7', city: 'Beograd', neighborhood: 'Vračar', area: 78, landArea: 0, price: 185000, pricePerSqm: 2372, bedrooms: 3, bathrooms: 1, floor: '3/5', yearBuilt: 1985, heating: 'gas', furnishing: 'unfurnished', parking: true, elevator: false, terrace: true, registered: true, agent: 'Milan Ristić', listedDate: '2024-06-01', views: 245, inquiries: 18, notes: 'Renoviran 2022 — nova kupatila, podovi' },
  { id: '2', propertyNo: 'NEK-002', title: 'Dvosoban stan — Novi Beograd', type: 'apartment', transactionType: 'rent', status: 'rented', address: 'Bulevar Mihajla Pupina 165/12', city: 'Beograd', neighborhood: 'Novi Beograd', area: 55, landArea: 0, price: 550, pricePerSqm: 10, bedrooms: 2, bathrooms: 1, floor: '8/16', yearBuilt: 2018, heating: 'central', furnishing: 'furnished', parking: true, elevator: true, terrace: true, registered: true, agent: 'Jelena Kovačević', listedDate: '2024-03-15', views: 512, inquiries: 42, notes: 'Zakup na godinu dana — zakupac zadovoljan' },
  { id: '3', propertyNo: 'NEK-003', title: 'Porodična kuća — Zvezdara', type: 'house', transactionType: 'sale', status: 'available', address: 'Koste Stamenkovića 28', city: 'Beograd', neighborhood: 'Zvezdara', area: 160, landArea: 350, price: 285000, pricePerSqm: 1781, bedrooms: 4, bathrooms: 2, floor: 'Prizemlje+sprat', yearBuilt: 2005, heating: 'gas', furnishing: 'semi_furnished', parking: true, elevator: false, terrace: true, registered: true, agent: 'Milan Ristić', listedDate: '2024-05-20', views: 189, inquiries: 12, notes: 'Dvorište, letnja kuhinja, garaža za 2 auto' },
  { id: '4', propertyNo: 'NEK-004', title: 'Lokal — Knez Mihailova', type: 'commercial', transactionType: 'both', status: 'available', address: 'Knez Mihajlova 28', city: 'Beograd', neighborhood: 'Centar', area: 120, landArea: 0, price: 4500, pricePerSqm: 37, bedrooms: 0, bathrooms: 1, floor: 'Prizemlje', yearBuilt: 1935, heating: 'electric', furnishing: 'unfurnished', parking: false, elevator: false, terrace: false, registered: true, agent: 'Nenad Stanković', listedDate: '2024-06-05', views: 378, inquiries: 25, notes: 'Izlog na ulicu, klima, alarm — idealan za prodavnicu' },
  { id: '5', propertyNo: 'NEK-005', title: 'Gradilište — Surčin', type: 'land', transactionType: 'sale', status: 'available', address: 'Put za Obrenovac bb', city: 'Beograd', neighborhood: 'Surčin', area: 0, landArea: 1500, price: 45000, pricePerSqm: 30, bedrooms: 0, bathrooms: 0, floor: '—', yearBuilt: 0, heating: 'none', furnishing: 'unfurnished', parking: false, elevator: false, terrace: false, registered: true, agent: 'Nenad Stanković', listedDate: '2024-05-10', views: 98, inquiries: 7, notes: 'Građevinsko zemljište, dozvoljena izgradnja P+2' },
  { id: '6', propertyNo: 'NEK-006', title: 'Garsonjera — Stari Grad', type: 'apartment', transactionType: 'rent', status: 'available', address: 'Gospodar Jevremova 22/4', city: 'Beograd', neighborhood: 'Stari Grad', area: 28, landArea: 0, price: 400, pricePerSqm: 14, bedrooms: 1, bathrooms: 1, floor: '2/4', yearBuilt: 1960, heating: 'electric', furnishing: 'furnished', parking: false, elevator: false, terrace: false, registered: true, agent: 'Jelena Kovačević', listedDate: '2024-06-12', views: 320, inquiries: 35, notes: '' },
  { id: '7', propertyNo: 'NEK-007', title: 'Luksuzni stan — Dedinje', type: 'apartment', transactionType: 'sale', status: 'reserved', address: 'Bulevar vojvode Bojovića 88', city: 'Beograd', neighborhood: 'Dedinje', area: 180, landArea: 0, price: 520000, pricePerSqm: 2889, bedrooms: 4, bathrooms: 2, floor: '5/6', yearBuilt: 2022, heating: 'central', furnishing: 'furnished', parking: true, elevator: true, terrace: true, registered: true, agent: 'Milan Ristić', listedDate: '2024-04-01', views: 456, inquiries: 28, notes: 'Rezervisan — čeka se depozit. Bazen, teretana, podrum' },
  { id: '8', propertyNo: 'NEK-008', title: 'Kancelarija — Niš', type: 'office', transactionType: 'rent', status: 'available', address: 'Vojvode Mišića 14', city: 'Niš', neighborhood: 'Centar', area: 85, landArea: 0, price: 800, pricePerSqm: 9, bedrooms: 0, bathrooms: 1, floor: '2/5', yearBuilt: 2010, heating: 'ac', furnishing: 'semi_furnished', parking: true, elevator: true, terrace: false, registered: true, agent: 'Ivana Đurić', listedDate: '2024-06-08', views: 145, inquiries: 9, notes: 'Open space, kuhinja, 2 parking mesta' },
]

export const STATUSES: Record<string, { color: string; label: string }> = { available: { color: 'bg-emerald-100 text-emerald-800', label: 'Dostupno' }, reserved: { color: 'bg-amber-100 text-amber-800', label: 'Rezervisano' }, sold: { color: 'bg-gray-100 text-gray-800', label: 'Prodato' }, rented: { color: 'bg-blue-100 text-blue-800', label: 'Iznajmljeno' }, off_market: { color: 'bg-red-100 text-red-800', label: 'Uklonjeno' } }
export const TYPES: Record<string, string> = { apartment: 'Stan', house: 'Kuća', commercial: 'Lokal', land: 'Zemljište', garage: 'Garaža', office: 'Kancelarija' }
