// Module group index - maps each module key to its group file
// This avoids importing all 124 modules at once, which crashes the bundler

export const moduleGroupMap: Record<string, string> = {
  // Core (12)
  'dashboard': 'core',
  'finance': 'core',
  'invoices': 'core',
  'inventory': 'core',
  'contacts': 'core',
  'reports': 'core',
  'settings': 'core',
  'calendar': 'core',
  'documents': 'core',
  'offers': 'core',
  'expenses': 'core',
  'automation': 'core',
  // HR (12)
  'employees': 'hr',
  'recruitment': 'hr',
  'leave': 'hr',
  'skills': 'hr',
  'approvals': 'hr',
  'workforce-planner': 'hr',
  'visitors': 'hr',
  'suggestions': 'hr',
  'time-tracking': 'hr',
  'time-billing': 'hr',
  'gamification': 'hr',
  'signatures': 'hr',
  // Finance (12)
  'accounting': 'finance',
  'bank-sync': 'finance',
  'payments': 'finance',
  'cash-register': 'finance',
  'pos': 'finance',
  'subscriptions': 'finance',
  'contracts': 'finance',
  'procurement': 'finance',
  'procurement-manager': 'finance',
  'returns': 'finance',
  'coupons': 'finance',
  'price-lists': 'finance',
  // Sales (12)
  'crm': 'sales',
  'support': 'sales',
  'email-marketing': 'sales',
  'sms-marketing': 'sales',
  'social-media': 'sales',
  'marketing-automation': 'sales',
  'surveys': 'sales',
  'events': 'sales',
  'loyalty': 'sales',
  'ratings': 'sales',
  'referrals': 'sales',
  'complaints': 'sales',
  // Projects (12)
  'projects': 'projects',
  'assets': 'projects',
  'maintenance': 'projects',
  'manufacturing': 'projects',
  'quality': 'projects',
  'protocol': 'projects',
  'plm': 'projects',
  'standards': 'projects',
  'labels': 'projects',
  'barcode': 'projects',
  'tenders': 'projects',
  'warranty': 'projects',
  // IT (12)
  'chat': 'it',
  'knowledge-base': 'it',
  'website': 'it',
  'blog': 'it',
  'forum': 'it',
  'spreadsheet': 'it',
  'notes': 'it',
  'integrations': 'it',
  'backup': 'it',
  'laws': 'it',
  'iot': 'it',
  'voip': 'it',
  // Logistics (12)
  'shipping': 'logistics',
  'fleet': 'logistics',
  'rent-a-car': 'logistics',
  'delivery': 'logistics',
  'routes': 'logistics',
  'loading-dock': 'logistics',
  'customs-docs': 'logistics',
  'trucks': 'logistics',
  'packaging': 'logistics',
  'measurements': 'logistics',
  'marketplace': 'logistics',
  'ecommerce': 'logistics',
  // Education (7)
  'education': 'education',
  'homework': 'education',
  'enrollment': 'education',
  'timetable': 'education',
  'library': 'education',
  'classroom': 'education',
  'tuition': 'education',
  // Hospitality (5)
  'restaurant': 'hospitality',
  'reservations': 'hospitality',
  'menu': 'hospitality',
  'kitchen': 'hospitality',
  'orders': 'hospitality',
  // Construction (4)
  'construction-site': 'construction',
  'blueprints': 'construction',
  'subcontractors': 'construction',
  'safety': 'construction',
  // Property (6)
  'property': 'property',
  'rentals': 'property',
  'property-viewings': 'property',
  'utilities': 'property',
  'work-orders': 'property',
  'valuation': 'property',
  // Medical (5)
  'patients': 'medical',
  'medical-records': 'medical',
  'prescriptions': 'medical',
  'lab': 'medical',
  'health-fund': 'medical',
  // Services (5)
  'service-center': 'services',
  'field-service': 'services',
  'appointments': 'services',
  'scheduler': 'services',
  'compliance': 'services',
  // Retail (8)
  'stores': 'retail',
  'client-portal': 'retail',
  'seo': 'retail',
  'reviews': 'retail',
  'cms': 'retail',
  'geolocation': 'retail',
  'cameras': 'retail',
  'messaging': 'retail',
}
