export const STATUS_CONFIG: Record<string, { label: string; color: string }> = {
  draft: {
    label: "Priprema",
    color: "bg-gray-100 text-gray-700 dark:bg-gray-900/30 dark:text-gray-400",
  },
  published: {
    label: "Objavljen",
    color: "bg-blue-100 text-blue-700 dark:bg-blue-900/30 dark:text-blue-400",
  },
  clarification: {
    label: "Razjašnjenje",
    color: "bg-cyan-100 text-cyan-700 dark:bg-cyan-900/30 dark:text-cyan-400",
  },
  submission_closed: {
    label: "Prijava zatvorena",
    color:
      "bg-amber-100 text-amber-700 dark:bg-amber-900/30 dark:text-amber-400",
  },
  evaluation: {
    label: "Evaluacija",
    color:
      "bg-purple-100 text-purple-700 dark:bg-purple-900/30 dark:text-purple-400",
  },
  awarded: {
    label: "Dodeljen",
    color:
      "bg-green-100 text-green-700 dark:bg-green-900/30 dark:text-green-400",
  },
  contract_signed: {
    label: "Ugovor potpisan",
    color:
      "bg-emerald-100 text-emerald-700 dark:bg-emerald-900/30 dark:text-emerald-400",
  },
  cancelled: {
    label: "Otkazan",
    color: "bg-red-100 text-red-700 dark:bg-red-900/30 dark:text-red-400",
  },
};

export const TYPE_CONFIG: Record<string, { label: string; icon: string }> = {
  goods: { label: "Roba", icon: "📦" },
  services: { label: "Usluge", icon: "🔧" },
  works: { label: "Radovi", icon: "🏗️" },
  concession: { label: "Koncesija", icon: "📜" },
  ppp: { label: "JPP", icon: "🤝" },
};

export const PROCEDURE_CONFIG: Record<
  string,
  { label: string; description: string }
> = {
  open: {
    label: "Otvoreni postupak",
    description: "Svi zainteresovani ponuđači mogu podneti ponudu",
  },
  restricted: {
    label: "Ograničeni postupak",
    description: "Samo pozvani ponuđači mogu učestvovati",
  },
  negotiated: {
    label: "Pregovarački postupak",
    description: "Direktni pregovori sa ponuđačima",
  },
  competitive_dialogue: {
    label: "Kompetitivni dijalog",
    description: "Složeni projekti sa više faza",
  },
  framework: {
    label: "Okvirni sporazum",
    description: "Dugoročni ugovor za ponavljajuće nabavke",
  },
  below_threshold: {
    label: "Ispod praga",
    description: "Nabavka ispod praga za javnu nabavku",
  },
};

export const SECTOR_CONFIG: Record<string, { label: string; icon: string }> = {
  it: { label: "IT & Telekomunikacije", icon: "💻" },
  construction: { label: "Građevinarstvo", icon: "🏗️" },
  health: { label: "Zdravstvo", icon: "🏥" },
  education: { label: "Obrazovanje", icon: "📚" },
  transport: { label: "Transport", icon: "🚛" },
  energy: { label: "Energetika", icon: "⚡" },
  defense: { label: "Odbrana", icon: "🛡️" },
  agriculture: { label: "Poljoprivreda", icon: "🌾" },
  environment: { label: "Zaštita životne sredine", icon: "🌱" },
  finance: { label: "Finansije", icon: "🏦" },
  other: { label: "Ostalo", icon: "📋" },
};

export const BIDDER_STATUS: Record<string, { label: string; color: string }> = {
  invited: { label: "Pozvan", color: "bg-gray-100 text-gray-700" },
  submitted: { label: "Podneo", color: "bg-blue-100 text-blue-700" },
  qualified: { label: "Kvalifikovan", color: "bg-green-100 text-green-700" },
  winner: { label: "Dobitnik", color: "bg-emerald-100 text-emerald-700" },
  disqualified: { label: "Diskvalifikovan", color: "bg-red-100 text-red-700" },
};

export const formatCurrency = (val: number, curr: string = "RSD") => {
  if (curr === "EUR")
    return `€${val.toLocaleString("sr-RS", { minimumFractionDigits: 2 })}`;
  return `${val.toLocaleString("sr-RS", { minimumFractionDigits: 2 })} RSD`;
};

export const mockTenders: Tender[] = [
  {
    id: "tnd-1",
    number: "JN-2025-001",
    title: "Nabavka server opreme za Data Center",
    description:
      "Nabavka 10 servera za potrebe novog Data Centra u Beogradu. Konfiguracija: 2x CPU, 256GB RAM, 4x 2TB NVMe.",
    type: "goods",
    procedureType: "open",
    status: "evaluation",
    priority: "high",
    sector: "it",
    buyerName: "Ministarstvo finansija",
    buyerPib: "100123456",
    buyerAddress: "Nemanjina 22, Beograd",
    estimatedValue: 15000000,
    currency: "RSD",
    cpvCode: "30200000-3",
    deadlineSubmission: "2025-01-25T23:59:00",
    deadlineClarification: "2025-01-15T23:59:00",
    openingDate: "2025-01-28T10:00:00",
    awardDate: "",
    contractSigningDate: "",
    requirements: [
      "Garancija minimum 3 godine",
      "SLA 99.9%",
      "Instalacija uključena",
      "Podrška 24/7",
    ],
    criteria: [
      { id: "c1", name: "Cena", weight: 40, type: "price" },
      {
        id: "c2",
        name: "Tehničke karakteristike",
        weight: 30,
        type: "technical",
      },
      { id: "c3", name: "Garancija i podrška", weight: 20, type: "quality" },
      { id: "c4", name: "Iskustvo ponuđača", weight: 10, type: "experience" },
    ],
    bidders: [
      {
        id: "b1",
        name: "Tech Solutions d.o.o.",
        pib: "200123456",
        price: 14500000,
        score: 87,
        status: "qualified",
        submittedAt: "2025-01-24T16:00:00",
        disqualified: false,
        disqualificationReason: "",
      },
      {
        id: "b2",
        name: "IT Systems d.o.o.",
        pib: "200789012",
        price: 15200000,
        score: 82,
        status: "qualified",
        submittedAt: "2025-01-25T10:00:00",
        disqualified: false,
        disqualificationReason: "",
      },
      {
        id: "b3",
        name: "DataCore d.o.o.",
        pib: "200345678",
        price: 13800000,
        score: 91,
        status: "winner",
        submittedAt: "2025-01-24T14:30:00",
        disqualified: false,
        disqualificationReason: "",
      },
    ],
    winnerId: "b3",
    notes: "DataCore ima najbolji odnos cena/kvalitet.",
    publishedAt: "2025-01-05T08:00:00",
    createdAt: "2025-01-04T10:00:00",
    updatedAt: "2025-01-28T11:00:00",
    timeline: [
      {
        id: "e1",
        action: "Objavljen",
        description: "Tender objavljen na portalu",
        performedBy: "Admin",
        timestamp: "2025-01-05T08:00:00",
      },
      {
        id: "e2",
        action: "Rok za razjašnjenje",
        description: "Rok za postavljanje pitanja",
        performedBy: "Sistem",
        timestamp: "2025-01-15T23:59:00",
      },
      {
        id: "e3",
        action: "Zatvorena prijava",
        description: "Rok za podnošenje ponuda",
        performedBy: "Sistem",
        timestamp: "2025-01-25T23:59:00",
      },
      {
        id: "e4",
        action: "Otvaranje ponuda",
        description: "Javno otvaranje ponuda",
        performedBy: "Komisija",
        timestamp: "2025-01-28T10:00:00",
      },
    ],
  },
  {
    id: "tnd-2",
    number: "JN-2025-002",
    title: "Izgradnja vrtića u Novom Sadu",
    description:
      "Kompletna izgradnja vrtića kapaciteta 120 dece, sa igralištem i parkingom.",
    type: "works",
    procedureType: "open",
    status: "published",
    priority: "high",
    sector: "construction",
    buyerName: "Gradska uprava Novi Sad",
    buyerPib: "100456789",
    buyerAddress: "Trg slobode 1, Novi Sad",
    estimatedValue: 85000000,
    currency: "RSD",
    cpvCode: "45200000-5",
    deadlineSubmission: "2025-02-20T23:59:00",
    deadlineClarification: "2025-02-05T23:59:00",
    openingDate: "2025-02-25T10:00:00",
    awardDate: "",
    contractSigningDate: "",
    requirements: [
      "Sertifikat ISO 9001",
      "Min 3 slična projekta u poslednjih 5 godina",
      "Garancija 5 godina",
      "Ročno osiguranje",
    ],
    criteria: [
      { id: "c5", name: "Cena", weight: 50, type: "price" },
      { id: "c6", name: "Tehničko rešenje", weight: 25, type: "technical" },
      { id: "c7", name: "Rok izgradnje", weight: 15, type: "time" },
      { id: "c8", name: "Reference", weight: 10, type: "experience" },
    ],
    bidders: [],
    winnerId: null,
    notes: "",
    publishedAt: "2025-01-10T08:00:00",
    createdAt: "2025-01-08T10:00:00",
    updatedAt: "2025-01-10T08:00:00",
    timeline: [
      {
        id: "e5",
        action: "Objavljen",
        description: "Tender objavljen",
        performedBy: "Admin",
        timestamp: "2025-01-10T08:00:00",
      },
    ],
  },
  {
    id: "tnd-3",
    number: "JN-2024-015",
    title: "Servisiranje medicinske opreme — KBC",
    description:
      "Godišnji servis i održavanje medicinske opreme za Klinički centar.",
    type: "services",
    procedureType: "negotiated",
    status: "contract_signed",
    priority: "medium",
    sector: "health",
    buyerName: "KBC Beograd",
    buyerPib: "100987654",
    buyerAddress: "Višegradska 26, Beograd",
    estimatedValue: 5000000,
    currency: "RSD",
    cpvCode: "50400000-2",
    deadlineSubmission: "2024-11-15T23:59:00",
    deadlineClarification: "2024-11-01T23:59:00",
    openingDate: "2024-11-18T10:00:00",
    awardDate: "2024-12-01",
    contractSigningDate: "2024-12-15",
    requirements: [
      "Licence za medicinsku opremu",
      "Sertifikovan serviser",
      "Dostupnost delova",
    ],
    criteria: [
      { id: "c9", name: "Cena", weight: 35, type: "price" },
      { id: "c10", name: "Kvalitet servisa", weight: 35, type: "quality" },
      { id: "c11", name: "Vreme odziva", weight: 30, type: "time" },
    ],
    bidders: [
      {
        id: "b4",
        name: "MedServis d.o.o.",
        pib: "200111222",
        price: 4200000,
        score: 89,
        status: "winner",
        submittedAt: "2024-11-14T12:00:00",
        disqualified: false,
        disqualificationReason: "",
      },
      {
        id: "b5",
        name: "HealthTech d.o.o.",
        pib: "200333444",
        price: 4800000,
        score: 78,
        status: "qualified",
        submittedAt: "2024-11-15T09:00:00",
        disqualified: false,
        disqualificationReason: "",
      },
    ],
    winnerId: "b4",
    notes: "Ugovor potpisan na 2 godine.",
    publishedAt: "2024-10-20T08:00:00",
    createdAt: "2024-10-18T10:00:00",
    updatedAt: "2024-12-15T16:00:00",
    timeline: [
      {
        id: "e6",
        action: "Objavljen",
        description: "Tender objavljen",
        performedBy: "Admin",
        timestamp: "2024-10-20T08:00:00",
      },
      {
        id: "e7",
        action: "Dodeljen",
        description: "Ponuđač MedServis d.o.o. odabran",
        performedBy: "Komisija",
        timestamp: "2024-12-01T14:00:00",
      },
      {
        id: "e8",
        action: "Ugovor",
        description: "Ugovor potpisan",
        performedBy: "Admin",
        timestamp: "2024-12-15T16:00:00",
      },
    ],
  },
  {
    id: "tnd-4",
    number: "JN-2025-003",
    title: "Nabavka办公si softvera za javnu upravu",
    description:
      "Licence za Office softver za 500 radnih stanica u državnoj upravi.",
    type: "goods",
    procedureType: "framework",
    status: "draft",
    priority: "low",
    sector: "it",
    buyerName: "Ministarstvo javne uprave",
    buyerPib: "100654321",
    buyerAddress: "Kneza Miloša 19, Beograd",
    estimatedValue: 8000000,
    currency: "RSD",
    cpvCode: "48000000-8",
    deadlineSubmission: "",
    deadlineClarification: "",
    openingDate: "",
    awardDate: "",
    contractSigningDate: "",
    requirements: [],
    criteria: [],
    bidders: [],
    winnerId: null,
    notes: "U pripremi — čeka odobrenje budžeta.",
    publishedAt: null,
    createdAt: "2025-01-18T10:00:00",
    updatedAt: "2025-01-18T10:00:00",
    timeline: [
      {
        id: "e9",
        action: "Kreiran",
        description: "Tender kreiran u režimu pripreme",
        performedBy: "Admin",
        timestamp: "2025-01-18T10:00:00",
      },
    ],
  },
  {
    id: "tnd-5",
    number: "JN-2024-012",
    title: "Održavanje puteva — Opština Zemun",
    description:
      "Zimsko održavanje i popravke puteva na teritoriji opštine Zemun.",
    type: "works",
    procedureType: "below_threshold",
    status: "cancelled",
    priority: "medium",
    sector: "transport",
    buyerName: "Opština Zemun",
    buyerPib: "100777888",
    buyerAddress: "Glavna 1, Zemun",
    estimatedValue: 3000000,
    currency: "RSD",
    cpvCode: "45230000-9",
    deadlineSubmission: "2024-10-01T23:59:00",
    deadlineClarification: "",
    openingDate: "",
    awardDate: "",
    contractSigningDate: "",
    requirements: ["Licenca za rad na putevima"],
    criteria: [],
    bidders: [],
    winnerId: null,
    notes: "Otkazano zbog nedostatka budžeta.",
    publishedAt: "2024-09-10T08:00:00",
    createdAt: "2024-09-08T10:00:00",
    updatedAt: "2024-09-25T10:00:00",
    timeline: [
      {
        id: "e10",
        action: "Objavljen",
        description: "Tender objavljen",
        performedBy: "Admin",
        timestamp: "2024-09-10T08:00:00",
      },
      {
        id: "e11",
        action: "Otkazan",
        description: "Tender otkazan — nedostatak budžeta",
        performedBy: "Admin",
        timestamp: "2024-09-25T10:00:00",
      },
    ],
  },
];

export const mockStats: TenderStats = {
  total: 48,
  open: 5,
  inEvaluation: 3,
  awarded: 32,
  cancelled: 8,
  totalValue: 125000000,
  avgBidders: 4.2,
  byType: [
    { type: "goods", count: 20, label: "Roba" },
    { type: "services", count: 15, label: "Usluge" },
    { type: "works", count: 10, label: "Radovi" },
    { type: "concession", count: 3, label: "Koncesija" },
  ],
  bySector: [
    { sector: "it", count: 14, label: "IT & Telecom" },
    { sector: "construction", count: 12, label: "Građevinarstvo" },
    { sector: "health", count: 8, label: "Zdravstvo" },
    { sector: "transport", count: 6, label: "Transport" },
    { sector: "education", count: 4, label: "Obrazovanje" },
    { sector: "energy", count: 2, label: "Energetika" },
    { sector: "other", count: 2, label: "Ostalo" },
  ],
  byStatus: [
    { status: "draft", count: 3, label: "Priprema" },
    { status: "published", count: 5, label: "Objavljeni" },
    { status: "clarification", count: 2, label: "Razjašnjenje" },
    { status: "evaluation", count: 3, label: "Evaluacija" },
    { status: "awarded", count: 24, label: "Dodeljeni" },
    { status: "contract_signed", count: 8, label: "Potpisani" },
    { status: "cancelled", count: 8, label: "Otkazani" },
  ],
  monthlyTrend: [
    { month: "Avg", opened: 6, awarded: 4, cancelled: 1 },
    { month: "Sep", opened: 8, awarded: 5, cancelled: 2 },
    { month: "Okt", opened: 7, awarded: 6, cancelled: 1 },
    { month: "Nov", opened: 5, awarded: 7, cancelled: 1 },
    { month: "Dec", opened: 3, awarded: 4, cancelled: 2 },
    { month: "Jan", opened: 4, awarded: 3, cancelled: 1 },
  ],
  topBuyers: [
    { buyer: "Ministarstvo finansija", count: 8, value: 35000000 },
    { buyer: "Gradska uprava Beograd", count: 6, value: 28000000 },
    { buyer: "KBC Beograd", count: 5, value: 18000000 },
    { buyer: "Ministarstvo odbrane", count: 4, value: 22000000 },
    { buyer: "JP Putevi Srbije", count: 3, value: 12000000 },
  ],
  upcomingDeadlines: [
    {
      id: "tnd-1",
      title: "Nabavka server opreme",
      deadline: "2025-01-25T23:59:00",
      daysLeft: 3,
    },
    {
      id: "tnd-2",
      title: "Izgradnja vrtića NS",
      deadline: "2025-02-20T23:59:00",
      daysLeft: 29,
    },
  ],
};

export const { activeCompanyId } = useAppStore();
