export const allModules: ModuleDef[] = [
  {
    id: "dashboard",
    icon: LayoutDashboard,
    labelKey: "sidebar.dashboard",
    group: "Overview",
  },
  {
    id: "finance",
    icon: Wallet,
    labelKey: "sidebar.finances",
    group: "Business",
  },
  {
    id: "invoices",
    icon: FileText,
    labelKey: "sidebar.invoices",
    group: "Business",
  },
  {
    id: "offers",
    icon: ClipboardList,
    labelKey: "sidebar.quotes",
    group: "Business",
  },
  {
    id: "inventory",
    icon: Warehouse,
    labelKey: "sidebar.warehouse",
    group: "Business",
  },
  {
    id: "procurement",
    icon: ShoppingCart,
    labelKey: "sidebar.procurement",
    group: "Business",
  },
  {
    id: "bank-sync",
    icon: Landmark,
    labelKey: "sidebar.bank",
    group: "Business",
  },
  { id: "pos", icon: Monitor, labelKey: "sidebar.pos", group: "Business" },
  {
    id: "shipping",
    icon: Truck,
    labelKey: "sidebar.shipping",
    group: "Business",
  },
  {
    id: "manufacturing",
    icon: Factory,
    labelKey: "sidebar.manufacturing",
    group: "Business",
  },
  {
    id: "expenses",
    icon: Receipt,
    labelKey: "sidebar.expenses",
    group: "Business",
  },
  {
    id: "subscriptions",
    icon: CreditCard,
    labelKey: "sidebar.subscriptions",
    group: "Business",
  },
  {
    id: "crm",
    icon: HeartHandshake,
    labelKey: "sidebar.crm",
    group: "CRM & Sales",
  },
  {
    id: "contacts",
    icon: Users,
    labelKey: "sidebar.partners",
    group: "CRM & Sales",
  },
  {
    id: "calendar",
    icon: CalendarDays,
    labelKey: "sidebar.calendar",
    group: "CRM & Sales",
  },
  {
    id: "marketplace",
    icon: Store,
    labelKey: "sidebar.marketplace",
    group: "CRM & Sales",
  },
  {
    id: "support",
    icon: HeadphonesIcon,
    labelKey: "sidebar.helpdesk",
    group: "CRM & Sales",
  },
  {
    id: "signatures",
    icon: PenTool,
    labelKey: "sidebar.sign",
    group: "CRM & Sales",
  },
  {
    id: "employees",
    icon: UserCog,
    labelKey: "sidebar.employees",
    group: "Organization",
  },
  {
    id: "leave",
    icon: Palmtree,
    labelKey: "sidebar.timeoff",
    group: "Organization",
  },
  {
    id: "recruitment",
    icon: Briefcase,
    labelKey: "sidebar.recruitment",
    group: "Organization",
  },
  {
    id: "referrals",
    icon: ThumbsUp,
    labelKey: "sidebar.referrals",
    group: "Organization",
  },
  {
    id: "projects",
    icon: FolderKanban,
    labelKey: "sidebar.projects",
    group: "Organization",
  },
  {
    id: "appointments",
    icon: CalendarClock,
    labelKey: "sidebar.appointments",
    group: "Organization",
  },
  {
    id: "scheduler",
    icon: CalendarRange,
    labelKey: "sidebar.planning",
    group: "Organization",
  },
  {
    id: "assets",
    icon: Building2,
    labelKey: "sidebar.assets",
    group: "Organization",
  },
  {
    id: "maintenance",
    icon: Wrench,
    labelKey: "sidebar.maintenance",
    group: "Organization",
  },
  {
    id: "quality",
    icon: ShieldCheck,
    labelKey: "sidebar.quality",
    group: "Organization",
  },
  {
    id: "documents",
    icon: Files,
    labelKey: "sidebar.documents",
    group: "Organization",
  },
  {
    id: "accounting",
    icon: BookOpen,
    labelKey: "sidebar.accounting",
    group: "Organization",
  },
  {
    id: "protocol",
    icon: FileText,
    labelKey: "sidebar.protocol",
    group: "Organization",
  },
  {
    id: "education",
    icon: GraduationCap,
    labelKey: "sidebar.education",
    group: "Organization",
  },
  {
    id: "knowledge-base",
    icon: BookMarked,
    labelKey: "sidebar.knowledge",
    group: "Organization",
  },
  {
    id: "email-marketing",
    icon: Mail,
    labelKey: "sidebar.emailMarketing",
    group: "Marketing",
  },
  {
    id: "social-media",
    icon: Share2,
    labelKey: "sidebar.social",
    group: "Marketing",
  },
  {
    id: "sms-marketing",
    icon: Megaphone,
    labelKey: "sidebar.sms",
    group: "Marketing",
  },
  {
    id: "events",
    icon: PartyPopper,
    labelKey: "sidebar.events",
    group: "Marketing",
  },
  {
    id: "marketing-automation",
    icon: Workflow,
    labelKey: "sidebar.mktAutomation",
    group: "Marketing",
  },
  {
    id: "surveys",
    icon: ClipboardCheck,
    labelKey: "sidebar.surveys",
    group: "Marketing",
  },
  {
    id: "fleet",
    icon: Car,
    labelKey: "sidebar.vehicleFleet",
    group: "Specialized",
  },
  {
    id: "restaurant",
    icon: UtensilsCrossed,
    labelKey: "sidebar.cafeRestaurant",
    group: "Specialized",
  },
  {
    id: "rent-a-car",
    icon: CarFront,
    labelKey: "sidebar.rentACar",
    group: "Specialized",
  },
  {
    id: "field-service",
    icon: MapPin,
    labelKey: "sidebar.fieldService",
    group: "Specialized",
  },
  {
    id: "chat",
    icon: MessageCircle,
    labelKey: "sidebar.discuss",
    group: "Communication",
  },
  {
    id: "notes",
    icon: StickyNote,
    labelKey: "sidebar.notes",
    group: "Communication",
  },
  {
    id: "approvals",
    icon: CheckCircle2,
    labelKey: "sidebar.approvals",
    group: "Communication",
  },
  {
    id: "skills",
    icon: Award,
    labelKey: "sidebar.skills",
    group: "Communication",
  },
  {
    id: "contracts",
    icon: FileSignature,
    labelKey: "sidebar.contracts",
    group: "Communication",
  },
  {
    id: "website",
    icon: Globe2,
    labelKey: "sidebar.website",
    group: "Web & IT",
  },
  { id: "blog", icon: PenLine, labelKey: "sidebar.blog", group: "Web & IT" },
  { id: "voip", icon: Phone, labelKey: "sidebar.voip", group: "Web & IT" },
  { id: "iot", icon: Wifi, labelKey: "sidebar.iot", group: "Web & IT" },
  {
    id: "messaging",
    icon: MessageCircleReply,
    labelKey: "sidebar.whatsapp",
    group: "Web & IT",
  },
  {
    id: "forum",
    icon: UsersRound,
    labelKey: "sidebar.forum",
    group: "Web & IT",
  },
  { id: "plm", icon: GitBranch, labelKey: "sidebar.plm", group: "Web & IT" },
  {
    id: "ecommerce",
    icon: ShoppingBag,
    labelKey: "sidebar.ecommerce",
    group: "Web & IT",
  },
  {
    id: "spreadsheet",
    icon: Table2,
    labelKey: "sidebar.spreadsheet",
    group: "Web & IT",
  },
  { id: "cms", icon: FileCode, labelKey: "sidebar.cms", group: "Web & IT" },
  { id: "ratings", icon: Star, labelKey: "sidebar.rating", group: "Extra" },
  {
    id: "gamification",
    icon: Gamepad2,
    labelKey: "sidebar.gamification",
    group: "Extra",
  },
  {
    id: "complaints",
    icon: ShieldAlert,
    labelKey: "sidebar.complaints",
    group: "Extra",
  },
  {
    id: "tenders",
    icon: Gavel,
    labelKey: "sidebar.tenders",
    group: "Extra",
  },
  {
    id: "warranty",
    icon: ShieldCheck,
    labelKey: "sidebar.warranties",
    group: "Extra",
  },
  {
    id: "service-center",
    icon: Wrench,
    labelKey: "sidebar.serviceCenter",
    group: "Extra",
  },
  {
    id: "compliance",
    icon: Shield,
    labelKey: "sidebar.compliance",
    group: "Extra",
  },
  {
    id: "loyalty",
    icon: Crown,
    labelKey: "sidebar.loyalty",
    group: "Extra",
  },
  {
    id: "workforce-planner",
    icon: CalendarRange,
    labelKey: "sidebar.workforce",
    group: "Extra",
  },
  {
    id: "visitors",
    icon: UserCheck,
    labelKey: "sidebar.visitors",
    group: "Extra",
  },
  {
    id: "suggestions",
    icon: Lightbulb,
    labelKey: "sidebar.suggestions",
    group: "Extra",
  },
  {
    id: "valuation",
    icon: Target,
    labelKey: "sidebar.appraisal",
    group: "Extra",
  },
  {
    id: "health-fund",
    icon: Heart,
    labelKey: "sidebar.healthFund",
    group: "Extra",
  },
  {
    id: "geolocation",
    icon: MapPin,
    labelKey: "sidebar.geolocation",
    group: "Extra",
  },
  { id: "cameras", icon: Camera, labelKey: "sidebar.cameras", group: "Extra" },
  {
    id: "procurement-manager",
    icon: PackageSearch,
    labelKey: "sidebar.procurementManager",
    group: "Extra",
  },
  {
    id: "reports",
    icon: BarChart3,
    labelKey: "sidebar.reports",
    group: "Analytics",
  },
  {
    id: "integrations",
    icon: Plug,
    labelKey: "sidebar.integrations",
    group: "Analytics",
  },
  { id: "laws", icon: Scale, labelKey: "sidebar.laws", group: "Analytics" },
  {
    id: "settings",
    icon: Settings,
    labelKey: "sidebar.settings",
    group: "System",
  },
];

export const { activeModule, setActiveModule } = useAppStore();

export const { isDesktopMode } = useWindowManager();
