'use client'
import { useState, useEffect, useCallback } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Badge } from '@/components/ui/badge'; import { Skeleton } from '@/components/ui/skeleton'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'; import { Label } from '@/components/ui/label'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Plus, Search, Trash2, Pencil, Eye, Store, MapPin, Phone, Clock, ArrowLeft } from 'lucide-react'; import { toast } from 'sonner'; import { formatDate } from '@/lib/helpers'

type StoreItem = { id: string; storeNo: string; name: string; code: string; city: string; address: string; phone: string; email: string; manager: string; type: string; status: string; openDate: string; area: number; employees: number; monthlyRevenue: number; notes: string }
const TYPES: Record<string, string> = { retail: 'Prodavnica', warehouse: 'Magacin', office: 'Biro', factory: 'Fabrika' }
const STATUSES: Record<string, { color: string; label: string }> = { active: { color: 'bg-emerald-100 text-emerald-800', label: 'Aktivna' }, closed: { color: 'bg-red-100 text-red-800', label: 'Zatvorena' }, renovation: { color: 'bg-amber-100 text-amber-800', label: 'Renoviranje' } }
function getStatusBadge(s: string) { const r = STATUSES[s]; return r ? <Badge className={`${r.color} text-xs`}>{r.label}</Badge> : <Badge className="text-xs">{s}</Badge> }

export function Stores() {
  const [data, setData] = useState<StoreItem[]>([]); const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState(''); const [statusFilter, setStatusFilter] = useState('')
  const [dialogOpen, setDialogOpen] = useState(false); const [editItem, setEditItem] = useState<StoreItem | null>(null)
  const [detailId, setDetailId] = useState<string | null>(null); const [form, setForm] = useState<Partial<StoreItem>>({}); const [activeTab, setActiveTab] = useState('pregled')

  const fetchData = useCallback(async () => {
    try {
      setLoading(true)
      const params = new URLSearchParams()
      if (search) params.set('search', search)
      if (statusFilter) params.set('status', statusFilter)
      const res = await fetch(`/api/stores?${params}`)
      if (!res.ok) throw new Error()
      const json = await res.json()
      setData(json)
    } catch { toast.error('Greška pri učitavanju') } finally { setLoading(false) }
  }, [search, statusFilter])

  useEffect(() => { fetchData() }, [fetchData])

  const filtered = data
  const handleDelete = async (id: string) => { if (!confirm('Obrisati?')) return; try { const res = await fetch(`/api/stores/${id}`, { method: 'DELETE' }); if (!res.ok) throw new Error(); toast.success('Obrisano'); fetchData() } catch { toast.error('Greška pri brisanju') } }
  const openCreate = () => { setEditItem(null); setForm({ name: '', code: '', city: '', address: '', phone: '', email: '', manager: '', type: 'retail', status: 'active', openDate: new Date().toISOString().split('T')[0], area: 50, employees: 2, monthlyRevenue: 0, notes: '' }); setDialogOpen(true) }
  const openEdit = (item: StoreItem) => { setEditItem(item); setForm({ ...item }); setDialogOpen(true) }
  const handleSave = async () => { if (!form.name || !form.city) { toast.error('Popunite obavezna polja'); return }; try { const url = editItem ? `/api/stores/${editItem.id}` : '/api/stores'; const res = await fetch(url, { method: editItem ? 'PUT' : 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(form) }); if (!res.ok) throw new Error(); toast.success(editItem ? 'Ažurirano' : 'Kreirano'); setDialogOpen(false); fetchData() } catch { toast.error('Greška pri čuvanju') } }
  if (loading) return <div className="space-y-4"><Skeleton className="h-8 w-64" /><Skeleton className="h-64" /></div>
  const detailItem = detailId ? data.find(i => i.id === detailId) : null
  const activeCount = data.filter(i => i.status === 'active').length; const totalEmployees = data.reduce((s, i) => s + i.employees, 0)

  return (<div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight">Poslovnice</h1><p className="text-sm text-muted-foreground">Lokacije, prodavnice, magacini i fabrike</p></div><Button size="sm" className="gap-2" onClick={openCreate}><Plus className="h-4 w-4" />Nova lokacija</Button></div>
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3"><Card className="p-4"><div className="text-xs text-muted-foreground mb-1 flex items-center gap-1"><Store className="h-3 w-3" />Ukupno</div><p className="text-2xl font-bold">{data.length}</p></Card><Card className="p-4"><div className="text-xs text-emerald-600 mb-1">Aktivnih</div><p className="text-2xl font-bold text-emerald-700">{activeCount}</p></Card><Card className="p-4"><div className="text-xs text-blue-600 mb-1">Gradova</div><p className="text-2xl font-bold text-blue-700">{new Set(data.map(i => i.city)).size}</p></Card><Card className="p-4"><div className="text-xs text-muted-foreground mb-1">Zaposlenih</div><p className="text-2xl font-bold">{totalEmployees}</p></Card></div>
    <Tabs value={activeTab} onValueChange={setActiveTab}><TabsList><TabsTrigger value="pregled">Pregled</TabsTrigger><TabsTrigger value="dodaj">Dodaj</TabsTrigger><TabsTrigger value="uredi">Uredi</TabsTrigger></TabsList>
      <TabsContent value="pregled" className="mt-4"><Card><CardHeader className="pb-3"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><CardTitle className="text-base">Lista lokacija</CardTitle><div className="flex gap-2 items-center"><div className="relative"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground" /><Input placeholder="Pretraga..." className="pl-8 h-8 w-44 text-xs" value={search} onChange={e => setSearch(e.target.value)} /></div><Select value={statusFilter || 'all'} onValueChange={v => setStatusFilter(v === 'all' ? '' : v)}><SelectTrigger className="w-28 h-8 text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Sve</SelectItem><SelectItem value="active">Aktivne</SelectItem><SelectItem value="renovation">Renoviranje</SelectItem><SelectItem value="closed">Zatvorene</SelectItem></SelectContent></Select></div></div></CardHeader><CardContent><div className="max-h-[480px] overflow-y-auto"><Table><TableHeader><TableRow><TableHead className="text-xs">Naziv</TableHead><TableHead className="text-xs hidden sm:table-cell">Tip</TableHead><TableHead className="text-xs hidden md:table-cell">Grad</TableHead><TableHead className="text-xs hidden md:table-cell">Zaposlenih</TableHead><TableHead className="text-xs hidden lg:table-cell">Menadžer</TableHead><TableHead className="text-xs">Status</TableHead><TableHead className="text-xs text-right">Akcije</TableHead></TableRow></TableHeader><TableBody>{filtered.length === 0 ? <TableRow><TableCell colSpan={7} className="text-center py-8 text-muted-foreground text-sm">Nema</TableCell></TableRow> : filtered.map(item => (<TableRow key={item.id}><TableCell className="text-xs font-medium">{item.name}</TableCell><TableCell className="text-xs text-muted-foreground hidden sm:table-cell">{TYPES[item.type]}</TableCell><TableCell className="text-xs hidden md:table-cell">{item.city}</TableCell><TableCell className="text-xs hidden md:table-cell">{item.employees}</TableCell><TableCell className="text-xs text-muted-foreground hidden lg:table-cell">{item.manager || '—'}</TableCell><TableCell>{getStatusBadge(item.status)}</TableCell><TableCell className="text-right"><div className="flex items-center justify-end gap-1"><Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setDetailId(item.id)}><Eye className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => openEdit(item)}><Pencil className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7 text-red-500" onClick={() => handleDelete(item.id)}><Trash2 className="h-3.5 w-3.5" /></Button></div></TableCell></TableRow>))}</TableBody></Table></div></CardContent></Card></TabsContent>
      <TabsContent value="dodaj" className="mt-4"><Card><CardHeader><CardTitle className="text-base">Nova lokacija</CardTitle></CardHeader><CardContent><div className="grid gap-4"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="grid gap-2"><Label className="text-xs">Naziv *</Label><Input className="text-xs" value={form.name || ''} onChange={e => setForm({ ...form, name: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Grad *</Label><Input className="text-xs" value={form.city || ''} onChange={e => setForm({ ...form, city: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Adresa</Label><Input className="text-xs" value={form.address || ''} onChange={e => setForm({ ...form, address: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Tip</Label><Select value={form.type || 'retail'} onValueChange={v => setForm({ ...form, type: v })}><SelectTrigger className="text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="retail">Prodavnica</SelectItem><SelectItem value="warehouse">Magacin</SelectItem><SelectItem value="office">Biro</SelectItem><SelectItem value="factory">Fabrika</SelectItem></SelectContent></Select></div><div className="grid gap-2"><Label className="text-xs">Površina (m²)</Label><Input className="text-xs" type="number" value={form.area || ''} onChange={e => setForm({ ...form, area: Number(e.target.value) })} /></div><div className="grid gap-2"><Label className="text-xs">Zaposlenih</Label><Input className="text-xs" type="number" value={form.employees || ''} onChange={e => setForm({ ...form, employees: Number(e.target.value) })} /></div><div className="grid gap-2"><Label className="text-xs">Menadžer</Label><Input className="text-xs" value={form.manager || ''} onChange={e => setForm({ ...form, manager: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Telefon</Label><Input className="text-xs" value={form.phone || ''} onChange={e => setForm({ ...form, phone: e.target.value })} /></div></div><Button size="sm" className="w-fit gap-2" onClick={handleSave}><Plus className="h-4 w-4" />Dodaj</Button></div></CardContent></Card></TabsContent>
      <TabsContent value="uredi" className="mt-4"><Card><CardHeader><CardTitle className="text-base">Uredi</CardTitle></CardHeader><CardContent><div className="max-h-[500px] overflow-y-auto space-y-3">{data.map(item => (<div key={item.id} className="flex items-center gap-3 p-3 border rounded-lg"><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><span className="text-xs font-medium">{item.name}</span>{getStatusBadge(item.status)}<Badge className="text-xs bg-muted">{TYPES[item.type]}</Badge></div><p className="text-xs text-muted-foreground truncate">{item.city} — {item.address}</p></div><Button variant="ghost" size="icon" className="h-7 w-7 shrink-0" onClick={() => openEdit(item)}><Pencil className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7 text-red-500 shrink-0" onClick={() => handleDelete(item.id)}><Trash2 className="h-3.5 w-3.5" /></Button></div>))}</div></CardContent></Card></TabsContent>
    </Tabs>
    {!!detailId && (<Card className="sm:max-w-[500px]"><CardHeader><div className="flex items-center gap-2"><Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setDetailId(null)}><ArrowLeft className="h-4 w-4" /></Button><CardTitle className="text-base">{detailItem?.name}</CardTitle></div></CardHeader>{detailItem && (<CardContent><div className="space-y-3"><div className="flex items-center gap-2">{getStatusBadge(detailItem.status)}<Badge className="text-xs bg-muted">{TYPES[detailItem.type]}</Badge></div><div className="grid grid-cols-2 gap-3">{[['Šifra', detailItem.code],['Grad', detailItem.city],['Adresa', detailItem.address],['Telefon', detailItem.phone],['Email', detailItem.email || '—'],['Menadžer', detailItem.manager],['Površina', `${detailItem.area} m²`],['Zaposlenih', String(detailItem.employees)],['Otvorena', formatDate(detailItem.openDate)],['Mesečni promet', detailItem.monthlyRevenue > 0 ? new Intl.NumberFormat('sr-RS', { style: 'currency', currency: 'RSD', maximumFractionDigits: 0 }).format(detailItem.monthlyRevenue) : '—']].map(([l, v]) => (<div key={l} className="p-2 rounded-lg bg-muted/50"><div className="text-xs text-muted-foreground">{l}</div><div className="text-xs font-medium">{v}</div></div>))}</div></div></CardContent>)}</Card>)}
    {dialogOpen && (<Card className="sm:max-w-[500px]"><CardHeader><div className="flex items-center gap-2"><Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setDialogOpen(false)}><ArrowLeft className="h-4 w-4" /></Button><CardTitle className="text-base">{editItem ? 'Uredi' : 'Nova'}</CardTitle></div></CardHeader><CardContent><div className="grid gap-4 py-4"><div className="grid grid-cols-2 gap-3"><div className="grid gap-2"><Label className="text-xs">Naziv *</Label><Input className="text-xs" value={form.name || ''} onChange={e => setForm({ ...form, name: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Status</Label><Select value={form.status || 'active'} onValueChange={v => setForm({ ...form, status: v })}><SelectTrigger className="text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="active">Aktivna</SelectItem><SelectItem value="renovation">Renoviranje</SelectItem><SelectItem value="closed">Zatvorena</SelectItem></SelectContent></Select></div></div></div><div className="flex justify-end gap-2 pt-4"><Button variant="outline" size="sm" onClick={() => setDialogOpen(false)}>Otkaži</Button><Button size="sm" onClick={handleSave}>Sačuvaj</Button></div></CardContent></Card>)}
  </div>)
}
