'use client'
import { useState, useEffect } from 'react'
import { Card, CardContent, CardHeader, CardTitle } from '@/components/ui/card'
import { Button } from '@/components/ui/button'; import { Input } from '@/components/ui/input'; import { Badge } from '@/components/ui/badge'; import { Skeleton } from '@/components/ui/skeleton'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '@/components/ui/tabs'; import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from '@/components/ui/dialog'
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from '@/components/ui/select'; import { Label } from '@/components/ui/label'
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from '@/components/ui/table'
import { Plus, Search, Trash2, Pencil, Eye, Store, MapPin, Phone, Clock } from 'lucide-react'; import { toast } from 'sonner'; import { formatDate } from '@/lib/helpers'

type StoreItem = { id: string; name: string; code: string; city: string; address: string; phone: string; email: string; manager: string; type: 'retail' | 'warehouse' | 'office' | 'factory'; status: 'active' | 'closed' | 'renovation'; openDate: string; area: number; employees: number; monthlyRevenue: number; notes: string }
const INITIAL: StoreItem[] = [
  { id: '1', name: 'Poslovnica Beograd — Centar', code: 'POS-BG-001', city: 'Beograd', address: 'Knez Mihailova 12', phone: '+381 11 321 4567', email: 'centar@reflection.rs', manager: 'Milan Ristić', type: 'retail', status: 'active', openDate: '2020-03-15', area: 120, employees: 8, monthlyRevenue: 2850000, notes: 'Flagship prodavnica — najveći promet' },
  { id: '2', name: 'Poslovnica Novi Sad', code: 'POS-NS-001', city: 'Novi Sad', address: 'Trg Slobode 7', phone: '+381 21 444 5566', email: 'novisad@reflection.rs', manager: 'Jelena Kovačević', type: 'retail', status: 'active', openDate: '2021-06-01', area: 85, employees: 5, monthlyRevenue: 1450000, notes: '' },
  { id: '3', name: 'Poslovnica Niš', code: 'POS-NI-001', city: 'Niš', address: 'Kopitareva 5', phone: '+381 18 222 3333', email: 'nis@reflection.rs', manager: 'Nenad Stanković', type: 'retail', status: 'active', openDate: '2022-01-10', area: 75, employees: 4, monthlyRevenue: 980000, notes: '' },
  { id: '4', name: 'Magacin Beograd — Surčin', code: 'MAG-BG-001', city: 'Beograd', address: 'Industrijska zona bb', phone: '+381 11 555 6666', email: 'magacin@reflection.rs', manager: 'Ivan Savić', type: 'warehouse', status: 'active', openDate: '2019-09-01', area: 500, employees: 12, monthlyRevenue: 0, notes: 'Centralni magacin — distribucija za sve prodavnice' },
  { id: '5', name: 'Fabrika Beograd — Rakovica', code: 'FAB-BG-001', city: 'Beograd', address: 'Industrijska 45', phone: '+381 11 777 8888', email: 'fabrika@reflection.rs', manager: 'Goran Đorđević', type: 'factory', status: 'active', openDate: '2018-05-20', area: 2000, employees: 45, monthlyRevenue: 0, notes: 'Proizvodnja — 3 linije' },
  { id: '6', name: 'Poslovnica Kragujevac', code: 'POS-KG-001', city: 'Kragujevac', address: 'Kralja Petra I 22', phone: '+381 34 333 4444', email: 'kragujevac@reflection.rs', manager: 'Ana Đurić', type: 'retail', status: 'renovation', openDate: '2023-03-01', area: 60, employees: 3, monthlyRevenue: 0, notes: 'Renoviranje do 01.08.2024 — otvaranje sa novim asortimanom' },
  { id: '7', name: 'Poslovnica Subotica — Zatvorena', code: 'POS-SB-001', city: 'Subotica', address: 'Trg Cara Jovana Nenada 8', phone: '', email: '', manager: '', type: 'retail', status: 'closed', openDate: '2021-09-15', area: 55, employees: 0, monthlyRevenue: 0, notes: 'Zatvorena 31.12.2023 — niska rentabilnost' },
  { id: '8', name: 'Biro Beograd — Stari Grad', code: 'BIR-BG-001', city: 'Beograd', address: 'Čika Ljubina 18', phone: '+381 11 888 9999', email: 'biro@reflection.rs', manager: 'Dragan Milić', type: 'office', status: 'active', openDate: '2018-01-15', area: 200, employees: 25, monthlyRevenue: 0, notes: 'Centrala — administracija, HR, finansije' },
]
const TYPES: Record<string, string> = { retail: 'Prodavnica', warehouse: 'Magacin', office: 'Biro', factory: 'Fabrika' }
const STATUSES: Record<string, { color: string; label: string }> = { active: { color: 'bg-emerald-100 text-emerald-800', label: 'Aktivna' }, closed: { color: 'bg-red-100 text-red-800', label: 'Zatvorena' }, renovation: { color: 'bg-amber-100 text-amber-800', label: 'Renoviranje' } }
function getStatusBadge(s: string) { const r = STATUSES[s]; return r ? <Badge className={`${r.color} text-[10px]`}>{r.label}</Badge> : <Badge className="text-[10px]">{s}</Badge> }

export function Stores() {
  const [data, setData] = useState<StoreItem[]>(INITIAL); const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState(''); const [statusFilter, setStatusFilter] = useState('')
  const [dialogOpen, setDialogOpen] = useState(false); const [editItem, setEditItem] = useState<StoreItem | null>(null)
  const [detailId, setDetailId] = useState<string | null>(null); const [form, setForm] = useState<Partial<StoreItem>>({}); const [activeTab, setActiveTab] = useState('pregled')
  useEffect(() => { setLoading(true); setTimeout(() => setLoading(false), 200) }, [])
  const filtered = data.filter(i => { const ms = !search || [i.name, i.city, i.code, i.manager].some(v => v.toLowerCase().includes(search.toLowerCase())); const ms2 = !statusFilter || i.status === statusFilter; return ms && ms2 })
  const handleDelete = (id: string) => { if (!confirm('Obrisati?')) return; setData(prev => prev.filter(i => i.id !== id)); toast.success('Obrisano') }
  const openCreate = () => { setEditItem(null); setForm({ name: '', code: '', city: '', address: '', phone: '', email: '', manager: '', type: 'retail', status: 'active', openDate: new Date().toISOString().split('T')[0], area: 50, employees: 2, monthlyRevenue: 0, notes: '' }); setDialogOpen(true) }
  const openEdit = (item: StoreItem) => { setEditItem(item); setForm({ ...item }); setDialogOpen(true) }
  const handleSave = () => { if (!form.name || !form.city) { toast.error('Popunite obavezna polja'); return }; if (editItem) { setData(prev => prev.map(i => i.id === editItem.id ? { ...i, ...form } as StoreItem : i)); toast.success('Ažurirano') } else { setData(prev => [{ id: Date.now().toString(), ...form } as StoreItem, ...prev]); toast.success('Kreirano') }; setDialogOpen(false) }
  if (loading) return <div className="space-y-4"><Skeleton className="h-8 w-64" /><Skeleton className="h-64" /></div>
  const detailItem = detailId ? data.find(i => i.id === detailId) : null
  const activeCount = data.filter(i => i.status === 'active').length; const totalEmployees = data.reduce((s, i) => s + i.employees, 0)

  return (<div className="space-y-6"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><div><h1 className="text-2xl font-bold tracking-tight">Poslovnice</h1><p className="text-sm text-muted-foreground">Lokacije, prodavnice, magacini i fabrike</p></div><Button size="sm" className="gap-2" onClick={openCreate}><Plus className="h-4 w-4" />Nova lokacija</Button></div>
    <div className="grid grid-cols-2 sm:grid-cols-4 gap-3"><Card className="p-4"><div className="text-xs text-muted-foreground mb-1 flex items-center gap-1"><Store className="h-3 w-3" />Ukupno</div><p className="text-2xl font-bold">{data.length}</p></Card><Card className="p-4"><div className="text-xs text-emerald-600 mb-1">Aktivnih</div><p className="text-2xl font-bold text-emerald-700">{activeCount}</p></Card><Card className="p-4"><div className="text-xs text-blue-600 mb-1">Gradova</div><p className="text-2xl font-bold text-blue-700">{new Set(data.map(i => i.city)).size}</p></Card><Card className="p-4"><div className="text-xs text-muted-foreground mb-1">Zaposlenih</div><p className="text-2xl font-bold">{totalEmployees}</p></Card></div>
    <Tabs value={activeTab} onValueChange={setActiveTab}><TabsList><TabsTrigger value="pregled">Pregled</TabsTrigger><TabsTrigger value="dodaj">Dodaj</TabsTrigger><TabsTrigger value="uredi">Uredi</TabsTrigger></TabsList>
      <TabsContent value="pregled" className="mt-4"><Card><CardHeader className="pb-3"><div className="flex flex-col sm:flex-row sm:items-center sm:justify-between gap-4"><CardTitle className="text-base">Lista lokacija</CardTitle><div className="flex gap-2 items-center"><div className="relative"><Search className="absolute left-2.5 top-2.5 h-3.5 w-3.5 text-muted-foreground" /><Input placeholder="Pretraga..." className="pl-8 h-8 w-44 text-xs" value={search} onChange={e => setSearch(e.target.value)} /></div><Select value={statusFilter || 'all'} onValueChange={v => setStatusFilter(v === 'all' ? '' : v)}><SelectTrigger className="w-28 h-8 text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="all">Sve</SelectItem><SelectItem value="active">Aktivne</SelectItem><SelectItem value="renovation">Renoviranje</SelectItem><SelectItem value="closed">Zatvorene</SelectItem></SelectContent></Select></div></div></CardHeader><CardContent><div className="max-h-[480px] overflow-y-auto"><Table><TableHeader><TableRow><TableHead className="text-xs">Naziv</TableHead><TableHead className="text-xs hidden sm:table-cell">Tip</TableHead><TableHead className="text-xs hidden md:table-cell">Grad</TableHead><TableHead className="text-xs hidden md:table-cell">Zaposlenih</TableHead><TableHead className="text-xs hidden lg:table-cell">Menadžer</TableHead><TableHead className="text-xs">Status</TableHead><TableHead className="text-xs text-right">Akcije</TableHead></TableRow></TableHeader><TableBody>{filtered.length === 0 ? <TableRow><TableCell colSpan={7} className="text-center py-8 text-muted-foreground text-sm">Nema</TableCell></TableRow> : filtered.map(item => (<TableRow key={item.id}><TableCell className="text-xs font-medium">{item.name}</TableCell><TableCell className="text-xs text-muted-foreground hidden sm:table-cell">{TYPES[item.type]}</TableCell><TableCell className="text-xs hidden md:table-cell">{item.city}</TableCell><TableCell className="text-xs hidden md:table-cell">{item.employees}</TableCell><TableCell className="text-xs text-muted-foreground hidden lg:table-cell">{item.manager || '—'}</TableCell><TableCell>{getStatusBadge(item.status)}</TableCell><TableCell className="text-right"><div className="flex items-center justify-end gap-1"><Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => setDetailId(item.id)}><Eye className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7" onClick={() => openEdit(item)}><Pencil className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7 text-red-500" onClick={() => handleDelete(item.id)}><Trash2 className="h-3.5 w-3.5" /></Button></div></TableCell></TableRow>))}</TableBody></Table></div></CardContent></Card></TabsContent>
      <TabsContent value="dodaj" className="mt-4"><Card><CardHeader><CardTitle className="text-base">Nova lokacija</CardTitle></CardHeader><CardContent><div className="grid gap-4"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><div className="grid gap-2"><Label className="text-xs">Naziv *</Label><Input className="text-xs" value={form.name || ''} onChange={e => setForm({ ...form, name: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Grad *</Label><Input className="text-xs" value={form.city || ''} onChange={e => setForm({ ...form, city: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Adresa</Label><Input className="text-xs" value={form.address || ''} onChange={e => setForm({ ...form, address: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Tip</Label><Select value={form.type || 'retail'} onValueChange={v => setForm({ ...form, type: v as StoreItem['type'] })}><SelectTrigger className="text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="retail">Prodavnica</SelectItem><SelectItem value="warehouse">Magacin</SelectItem><SelectItem value="office">Biro</SelectItem><SelectItem value="factory">Fabrika</SelectItem></SelectContent></Select></div><div className="grid gap-2"><Label className="text-xs">Površina (m²)</Label><Input className="text-xs" type="number" value={form.area || ''} onChange={e => setForm({ ...form, area: Number(e.target.value) })} /></div><div className="grid gap-2"><Label className="text-xs">Zaposlenih</Label><Input className="text-xs" type="number" value={form.employees || ''} onChange={e => setForm({ ...form, employees: Number(e.target.value) })} /></div><div className="grid gap-2"><Label className="text-xs">Menadžer</Label><Input className="text-xs" value={form.manager || ''} onChange={e => setForm({ ...form, manager: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Telefon</Label><Input className="text-xs" value={form.phone || ''} onChange={e => setForm({ ...form, phone: e.target.value })} /></div></div><Button size="sm" className="w-fit gap-2" onClick={handleSave}><Plus className="h-4 w-4" />Dodaj</Button></div></CardContent></Card></TabsContent>
      <TabsContent value="uredi" className="mt-4"><Card><CardHeader><CardTitle className="text-base">Uredi</CardTitle></CardHeader><CardContent><div className="max-h-[500px] overflow-y-auto space-y-3">{data.map(item => (<div key={item.id} className="flex items-center gap-3 p-3 border rounded-lg"><div className="flex-1 min-w-0"><div className="flex items-center gap-2"><span className="text-xs font-medium">{item.name}</span>{getStatusBadge(item.status)}<Badge className="text-[10px] bg-muted">{TYPES[item.type]}</Badge></div><p className="text-xs text-muted-foreground truncate">{item.city} — {item.address}</p></div><Button variant="ghost" size="icon" className="h-7 w-7 shrink-0" onClick={() => openEdit(item)}><Pencil className="h-3.5 w-3.5" /></Button><Button variant="ghost" size="icon" className="h-7 w-7 text-red-500 shrink-0" onClick={() => handleDelete(item.id)}><Trash2 className="h-3.5 w-3.5" /></Button></div>))}</div></CardContent></Card></TabsContent>
    </Tabs>
    <Dialog open={!!detailId} onOpenChange={() => setDetailId(null)}><DialogContent className="sm:max-w-[500px]"><DialogHeader><DialogTitle>{detailItem?.name}</DialogTitle></DialogHeader>{detailItem && (<div className="space-y-3"><div className="flex items-center gap-2">{getStatusBadge(detailItem.status)}<Badge className="text-[10px] bg-muted">{TYPES[detailItem.type]}</Badge></div><div className="grid grid-cols-2 gap-3">{[['Šifra', detailItem.code],['Grad', detailItem.city],['Adresa', detailItem.address],['Telefon', detailItem.phone],['Email', detailItem.email || '—'],['Menadžer', detailItem.manager],['Površina', `${detailItem.area} m²`],['Zaposlenih', String(detailItem.employees)],['Otvorena', formatDate(detailItem.openDate)],['Mesečni promet', detailItem.monthlyRevenue > 0 ? new Intl.NumberFormat('sr-RS', { style: 'currency', currency: 'RSD', maximumFractionDigits: 0 }).format(detailItem.monthlyRevenue) : '—']].map(([l, v]) => (<div key={l} className="p-2 rounded-lg bg-muted/50"><div className="text-[10px] text-muted-foreground">{l}</div><div className="text-xs font-medium">{v}</div></div>))}</div></div>)}</DialogContent></Dialog>
    <Dialog open={dialogOpen} onOpenChange={setDialogOpen}><DialogContent className="sm:max-w-[500px]"><DialogHeader><DialogTitle>{editItem ? 'Uredi' : 'Nova'}</DialogTitle></DialogHeader><div className="grid gap-4 py-4"><div className="grid grid-cols-2 gap-3"><div className="grid gap-2"><Label className="text-xs">Naziv *</Label><Input className="text-xs" value={form.name || ''} onChange={e => setForm({ ...form, name: e.target.value })} /></div><div className="grid gap-2"><Label className="text-xs">Status</Label><Select value={form.status || 'active'} onValueChange={v => setForm({ ...form, status: v as StoreItem['status'] })}><SelectTrigger className="text-xs"><SelectValue /></SelectTrigger><SelectContent><SelectItem value="active">Aktivna</SelectItem><SelectItem value="renovation">Renoviranje</SelectItem><SelectItem value="closed">Zatvorena</SelectItem></SelectContent></Select></div></div></div><DialogFooter><Button variant="outline" size="sm" onClick={() => setDialogOpen(false)}>Otkaži</Button><Button size="sm" onClick={handleSave}>Sačuvaj</Button></DialogFooter></DialogContent></Dialog>
  </div>)
}
