import type { Viewing } from './types'

export const INITIAL: Viewing[] = [
  { id: '1', propertyTitle: 'Trosoban stan — Vračar', clientName: 'Jovan Perić', phone: '+381 63 111 2222', agent: 'Milan Ristić', date: '2024-06-16', time: '17:00', duration: 45, status: 'scheduled', clientInterest: 'high', feedback: '', notes: 'Zainteresovan za kupovinu — ima finansiranje spremno' },
  { id: '2', propertyTitle: 'Trosoban stan — Vračar', clientName: 'Ana Milić', phone: '+381 64 333 4444', agent: 'Milan Ristić', date: '2024-06-14', time: '18:00', duration: 30, status: 'completed', clientInterest: 'medium', feedback: 'Stan je u redu ali nedostaje parking', notes: 'Možda se vrati nakon što drugi stanovi budu pogledani' },
  { id: '3', propertyTitle: 'Dvosoban stan — Novi Beograd', clientName: 'Marko Tomić', phone: '+381 65 555 6666', agent: 'Jelena Kovačević', date: '2024-06-13', time: '19:00', duration: 40, status: 'completed', clientInterest: 'high', feedback: 'Sve odgovara, nema primedbi', notes: 'Potpisao ugovor o zakupu istog dana' },
  { id: '4', propertyTitle: 'Kancelarija — Niš', clientName: 'IT Solutions DOO', phone: '+381 18 222 333', agent: 'Ivana Đurić', date: '2024-06-15', time: '11:00', duration: 60, status: 'cancelled', clientInterest: 'low', feedback: 'Premala površina za njihov tim od 15 ljudi', notes: 'Predložiti veći prostor kod drugog vlasnika' },
  { id: '5', propertyTitle: 'Lokal — Knez Mihajlova', clientName: 'Petar Lazarević', phone: '+381 62 777 8888', agent: 'Nenad Stanković', date: '2024-06-16', time: '10:00', duration: 45, status: 'scheduled', clientInterest: 'high', feedback: '', notes: 'Investor — planira kafeteriju' },
  { id: '6', propertyTitle: 'Garsonjera — Stari Grad', clientName: 'Student Jovan', phone: '+381 61 999 0000', agent: 'Jelena Kovačević', date: '2024-06-12', time: '16:00', duration: 20, status: 'no_show', clientInterest: 'none', feedback: '', notes: 'Nije se pojavio — 2x poziv, nema odgovora' },
  { id: '7', propertyTitle: 'Porodična kuća — Zvezdara', clientName: 'Mladen i Snežana', phone: '+381 63 444 5555', agent: 'Milan Ristić', date: '2024-06-17', time: '15:00', duration: 60, status: 'scheduled', clientInterest: 'high', feedback: '', notes: 'Porodica sa 2 dece — trače dvorište' },
  { id: '8', propertyTitle: 'Luksuzni stan — Dedinje', clientName: 'Goran Đurić', phone: '+381 64 222 3333', agent: 'Milan Ristić', date: '2024-06-10', time: '14:00', duration: 50, status: 'completed', clientInterest: 'high', feedback: 'Impresioniran kvalitetom — jedina primedba je sto koji je previše mali', notes: 'Pregledao ga i sa arhitektom za renovaciju' },
]

export const STATUSES: Record<string, { color: string; label: string }> = { scheduled: { color: 'bg-blue-100 text-blue-800', label: 'Zakazano' }, completed: { color: 'bg-emerald-100 text-emerald-800', label: 'Obavljeno' }, cancelled: { color: 'bg-red-100 text-red-800', label: 'Otkazano' }, no_show: { color: 'bg-amber-100 text-amber-800', label: 'Nije došao' } }
export const INTERESTS: Record<string, { color: string; label: string }> = { high: { color: 'bg-emerald-100 text-emerald-800', label: 'Visoko' }, medium: { color: 'bg-amber-100 text-amber-800', label: 'Srednje' }, low: { color: 'bg-gray-100 text-gray-800', label: 'Nisko' }, none: { color: 'bg-red-100 text-red-800', label: 'Nema' } }
